### ISSUE TITLE
Carpets are missing from a .nbt file

### ISSUE THREAD

**Issue by MrJeffOfficial** [maruohon/litematica#100]
Title

**Comment by vacla** [comment]
can you send your nbt file so we can check?
also version litematica, version minecraft?

**Comment by MrJeffOfficial** [comment]
Minecraft version 1.14.4 litematica version 1.14.4
https://drive.google.com/drive/folders/1CMhQ_doGTK-kv4qQdj60CxDBMqmGL4DC

**Comment by vacla** [comment]
is it litematica 0.0.0-dev.20191222.014040?

**Comment by MrJeffOfficial** [comment]
Yes

**Comment by vacla** [comment]
I can't seem to be able to download, can you make it a public download?

**Comment by MrJeffOfficial** [comment]
there it is : https://drive.google.com/open?id=1CMhQ_doGTK-kv4qQdj60CxDBMqmGL4DC

**Comment by vacla** [comment]
you need to change the nbt file so the names under pallete in the entries is for example black_carpet and do the properties away

**Comment by rebane2001** [comment]
This guy is coming from MapartCraft and I'm pretty sure he just selected the wrong MC version on there

**Comment by MrJeffOfficial** [comment]
but in mcedit the carpets are there so its not the MapartCraft's problem plus i choosed the "1.13/1.14" option

**Comment by rebane2001** [comment]
Mcedit Unified is for 1.12 anyways  
You did not choose the 1.13/1.14 option as it has the proper carpet mappings, I just tested it for myself

**Comment by MrJeffOfficial** [comment]
well i dont know why it doesnt work. anyway heres some pictures : 
https://imgur.com/gallery/l4OMzQr

**Comment by vacla** [comment]
did you open the latest one not in mcedit since the one you send here was definitely an 1.12.2 version.

**Comment by MrJeffOfficial** [comment]
no i didnt open the new nbt file in mcedit

**Comment by maruohon** [comment]
That schematic file indicates Minecraft 1.12.2 DataVersion, and the block palette is in the <= 1.12.2 format. As to why, no idea, if you selected the 1.13/1.14 format. Automatic conversion between MC versions should become possible in future version of the mod, after I get all the block state conversion stuff done.

Here is that map converted to the 1.14 format: 
https://pena2.dy.fi/tmp/minecraft/gh100_image_1.litematic

**Comment by MrJeffOfficial** [comment]
oh thanks it worked. also btw how did you convert those? i have a couple more i need to convert

**Comment by rebane2001** [comment]
Press ctrl+shift+r on MapartCraft and make sure you select the 1.13/1.14 version. I have confirmed myself that it works, you're  doing something wrong on your end

**Comment by MrJeffOfficial** [comment]
somehow it magically worked. i didnt know what i did wrong. thanks

**Comment by maruohon** [comment]
@rebane2001 It does seem like the site is a bit buggy. All the hover texts are off by 1 element, and when I download a map in the 1.13/1.14 format first, the block palette is correct, but the `DataVersion` in the file is still 1343 ie. 1.12.2. And then if I just change the MC version to 1.13/1.14 and download it again, it still gives me the same 1.13+ format palette.

@MrJeffOfficial Since that file was in the 1.12 format, I just loaded it in 1.12 Litematica and exported it in the Schematica format, and then I loaded that file in 1.14.4 Litematica and imported it into the Litematica format. With only that few blocks it would actually probably be faster to just change the block palette manually in the file with NBTExplorer though.

**Comment by maruohon** [comment]
Hmm that's weird, in the HTML the hover tips are on the correct elements, yet they appear wrong by one element when I hover over stuff... And now that I refreshed the page, they are correct... what?!

**Comment by rebane2001** [comment]
@maruohon
The off-by-one labels is a weird glitch with the tooltip library if you activate presets for the first time, it doesn't affect the functionality
I should add the dataversion thing, but it should still work in 1.14 even without it - block names are mapped correctly for later versions

**Comment by vacla** [comment]
for me version as "selected" doesn't get updated

**Comment by maruohon** [comment]
Without the correct `DataVersion` it's a lot more annoying for any program or mod to try to detect the original MC version of the file and know how to convert the block palette to the target version.

For reference, here are the DataVersions of the recent MC versions I just copied from the wiki:
```
1.12.0: 1139
1.12.1: 1241
1.12.2: 1343
1.13.0: 1519
1.13.1: 1628
1.13.2: 1631
1.14.0: 1952
1.14.1: 1957
1.14.2: 1963
1.14.3: 1968
1.14.4: 1976
1.15.0: 2225
1.15.1: 2227
```

I guess you mainly care about 1.12.0, 1.13.0, 1.14.0 etc. if you support new blocks added in each new MC version.

**Comment by rebane2001** [comment]
Thanks for the info, I'll be implementing it soon
