### ISSUE TITLE
1.15 wont work?

### ISSUE THREAD

**Issue by Toffelz** [maruohon/litematica#104]
I tried downloading litematica for 1.15.2 but it just gives me that msg évrey time i try to open it. Seems like theres files missing?

**Comment by Toffelz** [comment]
![Udklip](https://user-images.githubusercontent.com/60294130/73123216-ea2d5700-3f8d-11ea-9b6e-ec12479e5cd7.PNG)
I tried downloading litematica for 1.15.2 but it just gives me that msg évrey time i try to open it

**Comment by vacla** [comment]
you also need to get malilib from https://masa.dy.fi/mcmods/client_mods/
