### ISSUE TITLE
NBT decoding

### ISSUE THREAD

**Issue by SuhEugene** [maruohon/litematica#119]
I decoded .litematica file as nbt, and got json. In the *BuildingPlacementName* i have  **"BlockStates"**, "Position" ... **"BlockStatePalette"** ... "TIleEntities".
How to decode **"BlockStates"**?

Part of **"BlockStates"**
```json
...
[-2147483648,39321606],
[31738240,1131675659],
[0,236716032],
[49670500,1074724864],
[575344131,-1607475524],
[14448,15],
[-1517211076,0],
[698705,-1894364040],
[-507510784,3989872],
[2013265920,0],
[21132521,-744009628],
...
```

**Comment by maruohon** [comment]
It's a bit-packed array if IDs that refer to the palette indices. it was previously discussed a bit here: https://github.com/maruohon/litematica/issues/53

**Comment by SuhEugene** [comment]
Oh, I'm sorry.
I seem to be blind
