### ISSUE TITLE
Area selection moving with mouse movement (visual glitch)

### ISSUE THREAD

**Issue by r1ckrck** [maruohon/litematica#120]
![2020-03-05_10 10 53](https://user-images.githubusercontent.com/42771757/75948514-aa7d5780-5ec9-11ea-817d-806c8aebc1fc.png)
![2020-03-05_10 11 03](https://user-images.githubusercontent.com/42771757/75948528-afdaa200-5ec9-11ea-98b0-0830c0a4b109.png)

Both are the same selection and they move as I move. But the area actually selected doesn't change. I checked by the check block feature.

**Comment by vacla** [comment]
@r1ckrck did you update malilib to arne.4? And litematica to 20200302?

**Comment by r1ckrck** [comment]
Yeah my bad. That fixed it.
Thanks.
