### ISSUE TITLE
schematica is not avaible in minecraft controls

### ISSUE THREAD

**Issue by tiiziix** [maruohon/litematica#121]
i wan't to edit the key binds but schematica is not in my control settings, how can i fix that?

**Comment by maruohon** [comment]
My mods use the fully custom keybind system from malilib, not the vanilla controls. The keybinds can be configured in Litematica's config menu. You can get to it from the Litematica main menu `M`, or directly with `M + C`. If you are in 1.14+ and have the Mod Menu mod installed, then you can also use the gear icon in there to open the config menus of my mods.

**Comment by aelfwyne** [comment]
Really wish this would be reconsidered, because of this choice it's incredibly difficult to solve keybind conflicts with Litematica.

**Comment by maruohon** [comment]
@aelfwyne If you mean "reconsider ditching your own keybind system and using the vanilla system", that is simply not going to happen, as the vanilla system does not do basically anything of what I need the keybinds to be able to do.

But there are plans to add detection for conflicts with vanilla keybinds and show them in my keybind conflict hover text.

And also it's a slight possibility that I may add some kind of redirect fake keybind button to the vanilla Controls menu that opens my custom config screen. But again it's not feasible to put all my keybinds to the vanilla menu, as 1) they work entirely differently, and 2) I have such an insane number of keybinds in my mods...
