### ISSUE TITLE
Bottom left "selection mode" text not visible when toolItem is selected

### ISSUE THREAD

**Issue by jwheel** [maruohon/litematica#122]
This means i also can't do any sort of selection. I also have tweakeroo installed (grasping at straws as to why this isn't working....). All hotkey bindings are set to their defaults. 

![image](https://user-images.githubusercontent.com/16859462/76046550-ca426900-5f25-11ea-9361-ad433f15228f.png)
![image](https://user-images.githubusercontent.com/16859462/76046749-65d3d980-5f26-11ea-921b-21f89183b499.png)

**Comment by vacla** [comment]
Do you have litematica rendering enabled?

**Comment by maruohon** [comment]
There are two things that can disable the tool: the tool item toggle option (`M + T` or Generic -> `toolItemEnabled`), and disabling the Litematica main rendering option (`M + R` or Visuals -> `enableRendering`).

**Comment by jwheel** [comment]
> There are two things that can disable the tool: the tool item toggle option (`M + T` or Generic -> `toolItemEnabled`), and disabling the Litematica main rendering option (`M + R` or Visuals -> `enableRendering`).

It was M+R....

Thanks!
