### ISSUE TITLE
Saving issue 1.14.4 fabric

### ISSUE THREAD

**Issue by sattibunny** [maruohon/litematica#123]
Hey, I'm sure I'm being stupid but I'm stuck! I have a void creative world for testing I have build a farm on a quartz platform in an otherwise empty void world. I have made my selection fine but when I attempt to save no file is created, I attempted to analyze the selection and I get missing chunk errors. However I am stood in the relevant chunk and the entire build is in one chunk and about 8 blocks.  I don't have any other selections or sub selections. Could you please advise? Love the mod btw would be lost without it ✌️

**Comment by maruohon** [comment]
If you are left with the message about missing chunks, then it probably means that at least some sub-regions are somewhere outside of you current selection.

For example, are you aware of the two separate selection modes, Simple vs. Normal? It's hard to try to guess more without more information, like a screenshot of the Area Editor and the tool HUD etc.

**Comment by sattibunny** [comment]
I'll get you some screenshots in the morning, I rage quit 😜 and it's kinda late thanks for the speedy reply.

**Comment by maruohon** [comment]
Also if you use Discord, then there is a channel dedicated for the feedback and user support etc. related to my mods on the SciCraft Discord server: https://discord.gg/scicraft Basically that would probably just be slightly easier and faster for user support.

**Comment by sattibunny** [comment]
Thanks I'll work from the discord server and close it here 👍
