### ISSUE TITLE
for some reasons i have only 3 modes area editor ,schematic placement,rebuild schematic

### ISSUE THREAD

**Issue by shrutumhatre** [maruohon/litematica#129]
can i know why i have only 3 modes out of 9 out there

**Comment by vacla** [comment]
In survival, you can use only 3 modes, if you are in creative you can use the rest of them too, since they are more for creative

**Comment by shrutumhatre** [comment]
so i cant use it in sky block ?

**Comment by vacla** [comment]
if you are in survival mode, you can only use those that are available.

**Comment by shrutumhatre** [comment]
thankyou for you time
