### ISSUE TITLE
selection box moves around screen

### ISSUE THREAD

**Issue by bottobotty** [maruohon/litematica#131]
i am currently using version 1.15.2 of litematica and i have followed numerous tutorials on how to use it and they all do the same thing, so i do what they say and i always end up with the selection box moving around the screen instead of being in a solid position. if anyone can help that would be great. thank you :)

**Comment by vacla** [comment]
You need to update litematica or malilib to latest version

**Comment by bottobotty** [comment]
thank you so much:) made my days a lot easier :D
