### ISSUE TITLE
single layer rendering does not work

### ISSUE THREAD

**Issue by bottobotty** [maruohon/litematica#132]
ive loaded a schematic and it has loaded, but i toggled the single layer mode and the schematic fully disappeared. i then used pgup and pgdn but nothing came up.
any fixes?

**Comment by vacla** [comment]
Did you check if there was something rendering at that y level since you need to go up/down till there is something for to render.

**Comment by maruohon** [comment]
Use the Render Layers menu (or the `layerSetHere` hotkey if you have assigned it) to move the layer selection to your position. By default the values start from 0, so the single layer mode would be at y = 0.

**Comment by bottobotty** [comment]
> Use the Render Layers menu (or the `layerSetHere` hotkey if you have assigned it) to move the layer selection to your position. By default the values start from 0, so the single layer mode would be at y = 0.

ahhh i thought "y=0" was relative to your schematic. thank you :D

**Comment by maruohon** [comment]
They are absolute world coordinates, because you can have an arbitrary number of placements loaded at once, so there isn't just a single schematic/placement to make it relative to. Personally I think I also kind of prefer it this way anyway.
