### ISSUE TITLE
Can only select mode 1, 2, and 9 

### ISSUE THREAD

**Issue by AppleGUY2812** [maruohon/litematica#138]

**Comment by eatmyvenom** [comment]
This is due to you being in survival mode and therefore those are the only modes you would want in survival making this intended behavior. In order to access the other modes you would need to enter creative.

**Comment by AppleGUY2812** [comment]
Oh. I have another issue. When I click on the material list on a schematic placement nothing is there.

**Comment by SunSerega** [comment]
Please close issue's when they are resolved.
And yeah, separate issue's, but i see you already did.
