### ISSUE TITLE
When I click on the material list on a schematic placement nothing is there. 

### ISSUE THREAD

**Issue by AppleGUY2812** [maruohon/litematica#139]
![Screen Shot 2020-04-09 at 1 21 46 PM](https://user-images.githubusercontent.com/54564743/78937335-2d637600-7a65-11ea-9707-e05ec66611aa.png)
![Screen Shot 2020-04-09 at 1 21 51 PM](https://user-images.githubusercontent.com/54564743/78937340-2f2d3980-7a65-11ea-83d9-a00739ac4bf5.png)
![Screen Shot 2020-04-09 at 1 21 57 PM](https://user-images.githubusercontent.com/54564743/78937343-305e6680-7a65-11ea-9a81-6298530c086f.png)

**Comment by vacla** [comment]
Is the area loaded?

**Comment by SunSerega** [comment]
Provide more info. Screenshots, version of both game and litematica, etc.

Then, as you can imagine - for most people this is not the case, as material list is one of essential features and so it would be generally working. So you need to find and provide info for which way your case is unique, for devs to understand what's going on.

To gather this info - try testing everything you can come up with, like loading/unloading and enabling/disabling stuff.

**Comment by vacla** [comment]
To make up the material list, it counts first all blocks which are there in the world and then substracts them of the count of the schematic and that makes the material list

**Comment by maruohon** [comment]
There are two types of material lists, a material list that is generated directly for a schematic (these are opened from the Load Schematics menu by clicking on the schematic and then the Material List button), and a material list that is generated for a schematic placement (these are opened from the schematic placement configuration menu, or using the material list hotkey after changing the selected placement). I know this distinction between these (or even the fact that these are actually two separate things) is currently not clear for the end user, as I think the only thing indicating this difference is the title of the material list gui. The material list in general will receive a whole bunch of changes and improvements in the future, including changes to how this works.

So the difference between these modes is that the list generated directly for a schematic doesn't count anything from the world, it just gets the number of unique block states directly from the schematic and then converts those to items. So it does not track progress in any way, as it does not have world context and a placement to refer to. Whereas the material list generated for a placement counts the expected and already found blocks from the world within the placement that the list belongs to, so it can track progress and also it can respect the current render layer range if that option in enabled. To count the blocks from the world it then obviously needs to see the chunks from that area, so if the schematic is large then you may need to fly around to load all the chunks for it to count the blocks in them. You will get a HUD at the bottom right to indicate the missing chunks.

**Comment by AppleGUY2812** [comment]
so it is because my schematic is too large because it only shows the list of it on the bottom right of my minecraft screen.

**Comment by AppleGUY2812** [comment]
> There are two types of material lists, a material list that is generated directly for a schematic (these are opened from the Load Schematics menu by clicking on the schematic and then the Material List button), and a material list that is generated for a schematic placement (these are opened from the schematic placement configuration menu, or using the material list hotkey after changing the selected placement). I know this distinction between these (or even the fact that these are actually two separate things) is currently not clear for the end user, as I think the only thing indicating this difference is the title of the material list gui. The material list in general will receive a whole bunch of changes and improvements in the future, including changes to how this works.
> 
> So the difference between these modes is that the list generated directly for a schematic doesn't count anything from the world, it just gets the number of unique block states directly from the schematic and then converts those to items. So it does not track progress in any way, as it does not have world context and a placement to refer to. Whereas the material list generated for a placement counts the expected and already found blocks from the world within the placement that the list belongs to, so it can track progress and also it can respect the current render layer range if that option in enabled. To count the blocks from the world it then obviously needs to see the chunks from that area, so if the schematic is large then you may need to fly around to load all the chunks for it to count the blocks in them. You will get a HUD at the bottom right to indicate the missing chunks.
