### ISSUE TITLE
1.15.2 bug

### ISSUE THREAD

**Issue by 222Jakob** [maruohon/litematica#147]
Hi masa :),

im playing with the newest version:  v0.0.0-dev.20200409.182607.

I have problems with the stick command "Delete".
As soon as I use it, no chat commands are written out.
Here is a video of the situation:
https://streamable.com/msw7b1

Best regards :-)

Jakob

**Comment by maruohon** [comment]
Okay so the Fill task (and thus also the Delete task) accidentally disabled the `sendCommandFeedback` GameRule even in single player. It was only supposed to do that in multiplayer where it uses the vanilla commands.

I uploaded a fixed build here: https://masa.dy.fi/mcmods/litematica/litematica-fabric-1.15.2-0.0.0-dev.20200412.213317.jar
I won't upload this to CurseForge yet for this small of a change.
You will also need to re-enable that GameRule yourself in an existing world where it got turned off.

**Comment by 222Jakob** [comment]
Wow thx so much masa for the fast fix!
It works perfectly.

Cya in your stream. :-)
