### ISSUE TITLE
Game crashed - Version 1.15.2

### ISSUE THREAD

**Issue by dani690e** [maruohon/litematica#152]
Hi, I was trying to use Litematica by following the video https://youtu.be/aMZSXAKZzpo?t=17. But when I have the Litematica mod installed I get the following popup when i try to start Minecraft 1.15.2

Error
Game crashed
An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.

What I have done:
I have tried removing all mods and then fabric works.
+ It only crashed when loading the mod litematica every other mod it worked fine (Have tried with different versions).

**Comment by maruohon** [comment]
Did you get the correct, latest 1.15.2 Fabric version of malilib? I uploaded a Forge version too a few days ago, so make sure you didn't get that one.

**Comment by dani690e** [comment]
You were right I got the Forge Version instead of Fabric. Thanks for the help :)
