### ISSUE TITLE
Missing Blocks

### ISSUE THREAD

**Issue by Purplecolors** [maruohon/litematica#154]
So.. every time i Load a schematic into Minecraft, it's missing Log blocks.
can i get help? 
(Also sorry for the bad English..)

**Comment by vacla** [comment]
Duplicate of #125

**Comment by maruohon** [comment]
If you are on 1.15.2, then update to the latest version uploaded on 2020-04-09 (`litematica-fabric-1.15.2-0.0.0-dev.20200409.182607.jar`) which fixed this issue.
