### ISSUE TITLE
Materialist List not showing up or refreshing

### ISSUE THREAD

**Issue by Treeeop** [maruohon/litematica#155]
So i just go to my materialist list on my schematics placement menu but it just doesn't appear, i refresh it and it doesn't work either.
It does this from time to time, i don't know if it happens to a lot of people but it happens a lot to me and it's kind of annoying because i don't know how to solve this :/

thanks in advance!!

**Comment by maruohon** [comment]
Is it a large schematic? The mod needs to see all of the chunks where the schematic is, to be able to check how many blocks still need to be placed. So if the schematic goes outside of the client's loaded area, then you get the HUD on the bottom right corner indicating which chunks the mod hasn't yet seen, so you need to move/fly around to load all of those chunks, and then the material list will get populated.

There are lots of changes and improvements still planned for how the material list stuff works, for example the mod should just always count the total number of needed items from the schematic directly, and then later on update the missing item counts from the chunks in the world, if the player even wants to see those. You can currently also open the material list directly for a schematic without the mod counting anything from the chunks, if you click the material list button in the Load Schematics menu. If you open the material list from the placement configuration menu, then it will count the blocks from the world. This is also pretty obscure if you don't know about it, and it's among the things that will get improved.
