### ISSUE TITLE
Unable to find tools.jar

### ISSUE THREAD

**Issue by scarifyFX** [maruohon/litematica#156]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_251 contains a valid JDK installation.
```

I have tried putting tools.jar when I install java and tools.jar doesn't come pre-installed.

**Comment by vacla** [comment]
you can get here the latest version: https://masa.dy.fi/mcmods/client_mods/

**Comment by scarifyFX** [comment]
I know, that's where I usually get my litematica mods not from curse forge. the problem is when I use CMD for gradlew.

**Comment by maruohon** [comment]
You need a JDK to compile stuff. Get the latest Java 8 JDK.

**Comment by eatmyvenom** [comment]
You have a JRE and you need a JDK
look here: https://jdk.java.net/

**Comment by scarifyFX** [comment]
i have JRE and JDK but i have JDK 14

**Comment by scarifyFX** [comment]
**Solution:**
Installing JDK 8

**Comment by scarifyFX** [comment]
how do i resolve it?

**Comment by eatmyvenom** [comment]
your java home is not pointed toward the directory with a jdk in it
