### ISSUE TITLE
Bug, with lots of trouble shooting.

### ISSUE THREAD

**Issue by Mrcakes251** [maruohon/litematica#157]
I just installed Litematica to do map art with, and I have the NBT files in my schematics folder. Every menu works properly, I go to load schematics and my schematics show up, but when I go to select and load the schematic nothing happens. I mean nothing. No error message, nothing. I spam the button 60 times nothing happens, strangely the materials list doesn't work either. Kinda weird since my friend uses the same files and it works on 1.15.2, the same version.

**Comment by maruohon** [comment]
Do you mean they are in the vanilla structure block `*.nbt` format? So you don't see any messages in-game, and they don't appear in the Loaded Schematics list? Any messages in the game console? (You probably have to enable the option to show and keep open the console in your launcher options.) Are the files in-tact for sure and not corrupted during download? (Although that would probably give errors then when trying to load them.)

**Comment by Mrcakes251** [comment]
No errors, they show up in the schematics list but, when I click them nothing happens. No error message, they don't show up in the loaded. They are normal .nbt files. Don't know how to open the game consle

**Comment by maruohon** [comment]
There is an option in the launcher profile to open and keep open the console. Could you send me one of those schematics?

**Comment by Mrcakes251** [comment]
[Misty_Bottom.nbt.zip](https://github.com/maruohon/litematica/files/4526406/Misty_Bottom.nbt.zip)

Here is the file

**Comment by Mrcakes251** [comment]
Sorry about the delay, I have been really sick

**Comment by vacla** [comment]
just for whoever looks to it further, it gets an net.minecraft.util.InvalidIdentifierException: Non [a-z0-9_.-] character in namespace of location: Minecraft:cobblestone when it tries to Structure.loadPalettedBlockInfo()

**Comment by maruohon** [comment]
Yep I was just also looking at the file, for some reason the cobblestone entry in the palette has a capital M for minecraft. And looks like Litematica is just eating the exception. This is a bug in the mapartcraft program/site.

Here is a fixed version:
[Misty_Bottom_fixed.zip](https://github.com/maruohon/litematica/files/4530484/Misty_Bottom_fixed.zip)

I also added an error message to Litematica when it fails to load a vanilla structure block template file.

**Comment by Mrcakes251** [comment]
Thank you so much! I was just getting so frustrated because nothing was happening. You both are so helpful!

**Comment by Mrcakes251** [comment]
Is there any way in the future in using map art craft that when getting the file, I could change the capital M to a lower case m? I know its caused by the bug, but how do I decompile it and make the capital m a lower case.

**Comment by vacla** [comment]
You can change it in a program named nbtexplorer.
