### ISSUE TITLE
1.12.2 Doesnt work

### ISSUE THREAD

**Issue by p96xl** [maruohon/litematica#158]
I can get into minecraft, but when I try to load a world I get black screen and a crash. Sorry if this might be a little noobish.

Running on forge 14.23.5.2768
Mod List: 
CubicChunks 1.12.2-0.0.1055.0-SNAPSHOT
CubicGen 1.12.2-0.0.115.0-SNAPSHOT
Effortless Builing 1.12.2-2.16
JournyMap 1.12.2-5.7.0
Let's Encrypt Craft
LunatriusCore 1.2.0.42
MalisisCore 1.12..2-6.5.1-SNAPSHOT
Schematica 1.8.0.169
Terra 1 - 1 0.1
VanillaFix 1.0.10-150
WorldEdit 6.1.10-SNAPSHOT;8c1f930

ps. I have tried it without schematica, and still the same thing

**Comment by eatmyvenom** [comment]
Well first why do you have schematica and litematica which i dont even see in there? And also do you have malilib? Third a `latest.log` is always helpful

**Comment by p96xl** [comment]
[debug-4.log](https://github.com/maruohon/litematica/files/4498440/debug-4.log)

**Comment by eatmyvenom** [comment]
It seems that you dont have the correct versions of both mods
Make sure you malilib is up to date as well as litematica
[Here is masa's site](https://masa.dy.fi/tmp/minecraft/mods/client_mods/?mcver=1.12.2)

**Comment by p96xl** [comment]
[debug-5.log](https://github.com/maruohon/litematica/files/4498444/debug-5.log)

**Comment by maruohon** [comment]
`malilib-forge-1.12.2-0.10.0-dev.23-deobf.jar`
`litematica-forge-1.12.2-0.0.0-dev.20200418.234108.jar`

I assume you compiled these yourself? At least the malilib version is not the correct file, you are not supposed to use the `-deobf` version in the normal obfuscated game instance.

**Comment by maruohon** [comment]
Also why did you compile malilib `dev.23` yourself? There is already a build of that version on my server (liked above). Unless you merged the current master branch (LiteLoader) to the forge branch,  there is also no point building Litematica again from the currently pushed forge branch, as that code is already in the December builds on my server.

**Comment by p96xl** [comment]
I downloaded it from your site, that's how it came. I tried the version that isn't deobf but still is the same issue.

**Comment by maruohon** [comment]
Then post the crash log for the version from my site.

**Comment by p96xl** [comment]
Found the issue, It was VanillaFix. There seems to be an initiation when the world loads and vanillaFix thinks that minecraft crashed.
