### ISSUE TITLE
Can't Place Blocks

### ISSUE THREAD

**Issue by 17oClokk** [maruohon/litematica#16]
After creating my first schematic, I deleted all of the corners and origin point and can not place any blocks using my mouse. I can break blocks, and pick blocks, but can not place. Wondering what keybinds I need to use because it is not specified anywhere.

**Comment by 17oClokk** [comment]
Okay so that fixed it, I didn't even realise that I had that option set as true.

**Comment by SunSerega** [comment]
You can close your issues yourself, if it was a problem on your side.

**Comment by maruohon** [comment]
I probably need to re-work the Easy Place mode, as I can see this becoming a really common issue for people, as it's not at all obvious that this is a side effect of it trying to prevent wrongly placed blocks. I can probably at least allow right clicks outside the schematic areas.

**Comment by SunSerega** [comment]
Also, maybe it would help do give some warning if player makes, for instance, 100 RMB clicks that do nothing, because of easy placement?

**Comment by maruohon** [comment]
Yep I have also considered adding some kind of generic system to track unsuccessful or blocked input (mouse & keyboard) actions, and try to give an info popup about what might be the causes. But making that system generic enough for it to be easily usable for most things might be somewhat tricky.
