### ISSUE TITLE
litematica 1.14.4 not opening

### ISSUE THREAD

**Issue by Caddyshop** [maruohon/litematica#163]
ive installed litematica along with worldedit on 1.14.4 but when i press m to open litematica menu it does not open. I have looked if my controls were set to another bind but i cannot even find anything about litematica in my settings

**Comment by vacla** [comment]
If you have an azerty keyboard, you might need to press`, + C`

**Comment by maruohon** [comment]
Litematica uses the custom keybind system in malilib, that's why it's not in the vanilla controls menu.

Is this issue still unsolved?

**Comment by Caddyshop** [comment]
after posting this issue i kinda forgot about it but i saw this in my mails and checked it out and it works so it is solved, thanks for helping :D
