### ISSUE TITLE
Litematica paste perm

### ISSUE THREAD

**Issue by VekSan24** [maruohon/litematica#164]
Hello there, 

First of all, thank you for your time and for this great job. 

I have a question, we are starting to create a server with some friends, but i can't use the "paste" option. i have a message saying that i should contact the server admin.
 
What should i change in the perms to grant my account this option ? 

I tried to search on internet before posting here, but i can"'t manage to find the solution. 

Thank you very much.

**Comment by vacla** [comment]
You need to have permission to do /setblock (vanilla command)

**Comment by VekSan24** [comment]
Thanks ! i'll try this.
