### ISSUE TITLE
Still can't export as .schematic

### ISSUE THREAD

**Issue by RockyMkII** [maruohon/litematica#165]
When are you planning to implement that ? We really need it for Baritone ! 
Thanks in advance.

**Comment by maruohon** [comment]
There is support for 4 different formats in the main development version on 1.12.2 (see: https://www.curseforge.com/minecraft/mc-mods/litematica?comment=818).

But exporting to the old MCEdit/Schematica format on 1.13+ will also need me to finish the conversion support between 1.12 <-> 1.13+ first, and obviously it's not possible to keep any of the 1.13+ blocks if you export back to the old format. But if you actually mean the `*.schem` format, then that will be covered by the changes already done in the 1.12.2 versions, which just need to be ported over to the newer versions of the mod.

**Comment by RockyMkII** [comment]
I understand, thanks for the fast answer !
