### ISSUE TITLE
cant check claims with sticks 

### ISSUE THREAD

**Issue by cjw1207** [maruohon/litematica#166]
im playing on a public server and they have a claim protection mod and you can check claims by right clicking with a stick but i cant check because the mod doesnt allow you to right click with sticks anymore any fixes like a keybind to dissable the menu until i need it???

**Comment by vacla** [comment]
You need to disable `toolItemEnabled` in the configs in the generic tab of litematica.

**Comment by SunSerega** [comment]
Can't you also just change a tool? I think heard a few times now something like "it's a stick, unless you change a tool", though never questioned myself how to do that.

**Comment by vacla** [comment]
you can also indeed change the tool in Generic for using a different item

**Comment by maruohon** [comment]
Yes you can either change the tool item in Generic -> `toolItem` to any other item, or an empty hand (by leaving the field empty or using the literal `empty`). You can also toggle on/off the tool item functionality, either in the Generic config menu, or using a hotkey (by default `M + T` for "tool").
