### ISSUE TITLE
[Request] Way to export .litematic to the old .schematic format

### ISSUE THREAD

**Issue by Azkaii** [maruohon/litematica#167]
I need to use one of my schematics in mcEdit and it is only for 1.11 so I can only use .schematic

**Comment by maruohon** [comment]
I have been working on schematic conversion support between MC versions in the past couple of weeks. In the current development code I can convert schematics between MC versions in the `*.litematic` format. And also in the main development version in 1.12.2 it has been possible to export schematics to the `*.schematic` format from almost the very beginning of the mod.

So in other words if you need a schematic converted, you can send it to me for now and I can try to convert it, until the conversion support is ready and comes to a public build (1.12.2 at first).

**Comment by Azkaii** [comment]
Oh alright, thanks for the info. Here is the schematic I was hoping to convert: https://mega.nz/file/XLpBXQ5T#bhQCrpJmhSSibwlnO4dgLI-Z_L2tVebQ-_aCgchKl84

**Comment by SunSerega** [comment]
For file this light - you can just dran-and-drop into your answer here, on github.
Though you would probably need to pack it into .zip archive.

**Comment by maruohon** [comment]
Here is the converted file:
[Aspire_Legacy_1.12.2.schematic.zip](https://github.com/maruohon/litematica/files/4674550/Aspire_Legacy_1.12.2.schematic.zip)

**Comment by Azkaii** [comment]
It seems like MCEdit and WorldEdit both cannot open the converted schematic file. Could you test if its a problem on my end or if the file is corrupted?

**Comment by maruohon** [comment]
Okay took me a while to figure out *why* it was invalid for both MCEdit-Unified and World Edit. They actually require the root compound tag to be named `Schematic`, but the vanilla NBT utility methods don't by default expose a way of naming the root compound tag.

Here is the fixed version:
[Aspire_Legacy_1.12.2.schematic.zip](https://github.com/maruohon/litematica/files/4678818/Aspire_Legacy_1.12.2.schematic.zip)

**Comment by Azkaii** [comment]
Thank you very much! And I hope this helps anyone who finds this on google in the future?
