### ISSUE TITLE
Right clicking with easy-place mode enabled adds a ghost block to the schematic

### ISSUE THREAD

**Issue by Duffilufagus** [maruohon/litematica#168]
Maybe this is an option that I just can't seem to find, but when i attempt to use easy-place mode it won't actually add a physical block. It just seems to add to the schematic and won't let me place anything.

**Comment by maruohon** [comment]
Then you must be in the Schematic Rebuild mode, which is meant for editing schematics. Switch out from that mode for normal use, basically to any other mode. Usually when you are working with schematics in survival you would be in the Schematic Placement mode, where the tool item can be used for controlling the positioning of placements.
