### ISSUE TITLE
Is there a printer?

### ISSUE THREAD

**Issue by AppleGUY2812** [maruohon/litematica#175]
too lazy to build

**Comment by vacla** [comment]
@AppleGUY2812 if you are in singleplayer or have creative and op then you can just use paste mode, just press execute hotkey to execute the paste mode then

**Comment by kylerchin** [comment]
`M` is the default Hotkey to open menu, click config, click hotkeys, and change the executeOperation to a button or combo of your choice.
Issue can be closed.
