### ISSUE TITLE
Rendering problems, Strange "Area Selection" Rotations

### ISSUE THREAD

**Issue by NadeoWolf** [maruohon/litematica#176]
Hi,

i have some Problems using Litematica with Version 1.15.2.

When I select an area, it is displayed, but as soon as I move the mouse the selection rotates uncontrolled. I think it is moving in the oposit mouse direction.

At the same time I get a lot of these error messages:

[18:08:31] [Thread-13/INFO]: OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. View frustum must not have a zero values of: (right-left), (top-bottom), or (zFar-zNear).

Client: MultiMC 5 Version 0.6.11 - 1430
Mods:
  [✔️] Litematica-Mod-Fabric-1.15.2
  [✔️] malilib-fabric-1.15.2-0.10.0-dev.21+arne.2

One possible problem: I'm using AdoptOpenJDK => jdk-8.0.242.08-openj9

Is that a Problem? 

Thx for help, NadeoWolf
![2020-05-12_19 05 55](https://user-images.githubusercontent.com/9130089/81723958-e9102f00-9483-11ea-9941-38316db27ff8.png)
![2020-05-12_19 05 55_2](https://user-images.githubusercontent.com/9130089/81723959-ea415c00-9483-11ea-86fb-e28b09a1f1b0.png)
![2020-05-12_19 05 56](https://user-images.githubusercontent.com/9130089/81723961-ead9f280-9483-11ea-8adb-0c8eb0bc8eaa.png)
![2020-05-12_19 05 56_2](https://user-images.githubusercontent.com/9130089/81723962-eb728900-9483-11ea-9dad-d904710696f4.png)

**Comment by vacla** [comment]
@NadeoWolf which version of Litematica-Mod-Fabric-1.15.2?

**Comment by vacla** [comment]
also are you sure you aren't using malilib 1.15.2 0.10.0-dev.20+arne.2, since the latest is malilib 1.15.2 0.10.0-dev.21+arne.1

**Comment by NadeoWolf** [comment]
Litematica i tried the last version from the homepage and now the last dev build:
litematica-fabric-1.15.2-0.0.0-dev.20200507.230651.jar

malilib is this one: malilib-fabric-1.15.2-0.10.0-dev.21+arne.2.jar
Source: https://www.curseforge.com/minecraft/mc-mods/malilib
there is the arne2 version online...

**Comment by vacla** [comment]
do you have optifine or something?

**Comment by NadeoWolf** [comment]
i tried it, but i removed it completly

**Comment by maruohon** [comment]
This does look like the older Litematica build with the latest malilib, or vice versa. Which version does it display in the Litematica main menu currently?

**Comment by NadeoWolf** [comment]
in Litematica it sais: v0.0.0-dev.20200212.174750

... 

Ok problem solved. I downloaded the Mod from the curseforge site about 2 weeks ago. i didnt used it before today. 
later i tried the newest litematic version, but it only downloaded the mod and not activated it in the launcher. 

Newest Version from malilib and litematic fixed my problem. 

Thx for the fast response.  i dont know why i didnt saw the bad version before ;)
