### ISSUE TITLE
Hotkeys not working

### ISSUE THREAD

**Issue by SwaggMillionaire** [maruohon/litematica#18]
Hi

I have some issues with this mod on 1.13.2. 
I have te last version of Rift, Litematica and MaLiLib. 

1) The hotkeys M, M + C, M + A does not work! Nothing happen. I don't have te hotkey menu in the settings of Minecraft. The hotkey that works is "?", it opens the Litematica main menu.

2) I want to create a litematica-schematic (as you said) but I can't select my schematica because the hotkeys don't work...

**Comment by SunSerega** [comment]
Maybe it would help if you would send `config` folder... It contains all keybinds.

**Comment by SunSerega** [comment]
(i'm not dev, i another user. so i don't think it can be called support)

**Comment by SwaggMillionaire** [comment]
> 
> 
> (i'm not dev, i another user. so i don't think it can be called support)

No problem, i will wait.

**Comment by SunSerega** [comment]
idk, i can't find anything wrong with it.
I looked at differences with mine using TortoiseGit dif finder, and only things that was different - is what i changed after successfully testing it.

Maybe you installed it somehow wrong... Try also giving your `.minecraft\versions\*1.13.2 with rift folder*` and `home\...\mods` folder, i would check it same way.

**Comment by SwaggMillionaire** [comment]
[mods.zip](https://github.com/maruohon/litematica/files/2779314/mods.zip)
[1.13.2-rift-1.0.4-SNAPSHOT.zip](https://github.com/maruohon/litematica/files/2779315/1.13.2-rift-1.0.4-SNAPSHOT.zip)

**Comment by vacla** [comment]
which keyboard type do you have? examples are azerty, qwerty, qwertz

**Comment by SunSerega** [comment]
Well your version litematica isn't last. There is 2019 version and yours from 2018.

[mods.zip](https://github.com/maruohon/litematica/files/2779421/mods.zip)

**Comment by SunSerega** [comment]
Though... Your version of these folders works fine for me.

**Comment by maruohon** [comment]
I don't actually even know how the layout affects things. Does it just mean that the keycode stays the same for the key in the same position in the keyboard, but basically just the key it says it is, and the character it produces, are different? So for example are A and Q swapped in function/behaviour in AZERTY vs. QWERTY layout? So can you open the Litematica main menu if you press whatever key in your keyboard layout is in the same position as M is in QWERTY?

The keybinds in my LiteLoader and Rift mods don't use the vanilla keybind system because it's way too limited in functionality for my needs, that's why they are not in the vanilla controls menu. So you need to change them through the per-mod in-game config GUIs.

**Comment by vacla** [comment]
https://gyazo.com/798a5eebe8a1f2238a8e611de6c91d33 for example openGuiMainMenu is for me on keyboard for example "," because i have AZERTY.

**Comment by maruohon** [comment]
Does the game show the correct key names in the vanilla controls menu? Or if you rebind something there, does it use and show the correct key name?

**Comment by vacla** [comment]
no, it also uses the QWERTY layout there for me.

**Comment by SunSerega** [comment]
Actually... Layout isn't a build in thing for keyboards. It's something you can edit:
https://www.microsoft.com/en-US/download/details.aspx?id=22339

**Comment by vacla** [comment]
this only happens since 1.13 and in 1.12 there are no issues with keybinding even in vanilla.

**Comment by SunSerega** [comment]
I see... Well yeah, in 1.13 i think engine got updated, and a lot changed. I still can't get my clicking(+pressing) scripts to work.

@maruohon maybe then some lower level functions gonna work... Like this one:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getkeystate
This one works same everywhere, even without form.

I don't know how exactly to use WinAPI functions in java, but my java friend was using this function. Maybe you can decompile he's project:
[Eugene's auto clicker.zip](https://github.com/maruohon/litematica/files/2780101/Eugene.s.auto.clicker.zip)

**Comment by maruohon** [comment]
Windows-specific stuff doesn't really help, as there are also linux and mac users. And afaik you can't use native APIs from Java anyway, unless it's already built into Java/the JVM.

**Comment by SwaggMillionaire** [comment]
My keyboard is AZERTY and the hotkeys to play the game works fine.
Cool it's working now! x) I pressed on "?" + "C" and it opens the config menu (with hotkeys, ...), Now I can select a box! 

Thanks guys for the support!
