### ISSUE TITLE
Crash on rendering schematic 20w21a

### ISSUE THREAD

**Issue by LuisVervaet** [maruohon/litematica#182]
**NOTE: Please don't post "How do I do X?" type issues on this issue tracker. Such help requests should happen on Discord instead: https://discord.gg/VNVG3Wk (or if the previous link is broken: https://discord.gg/scicraft -> #masas-mods)**

**Describe the bug**
When looking at schematic render the game crashes.

**To Reproduce** (if not clear from the description already)
1. Load a schematic
2. look at loaded schematic
3. Crash
**Expected behavior** (if not clear from the description)
It dosent Crash

Pastebin: https://pastebin.com/G0Z95Bie

**Comment by BunnyBread** [comment]
This happens for me too, but only when looking at loaded schematics with entities. There is no crash when loading schematics without entities, or with the "ignore entities" box checked.

**Comment by maruohon** [comment]
I uploaded a new build about an hour ago that should fix at least the two entity rendering crashes that I've seen reported thus far.
