### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by shatteredcon** [maruohon/litematica#19]
It's been installed but keeps crashing, won't open minecraft at all. I have rift, created the profile for it. I downloaded malilib with litematica and moved them into my mods folder. It's specifically the litematica mod because when I remove it from my mod folder minecraft lods but it won't if litematica is in the mod folder.

**Comment by vacla** [comment]
do you have a crash report log?

**Comment by maruohon** [comment]
Did you download the correct (MC 1.13.2) versions of the mods? And you are on MC 1.13.2 and not 1.13? If so, please post (pastebin) the crash log, without one I can't know anything about the issue.

**Comment by shatteredcon** [comment]
> do you have a crash report log?


15:43:45 | launcher | main | info | Preparing to launch minecraft client for 1.13-rift-1.0.4-66
-- | -- | -- | -- | --
15:43:46 | launcher | main | warn | Couldn't get hash for org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar from https://www.dimdev.org/maven/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar.sha1: HTTP 404: Not Found
15:43:46 | launcher | main | warn | Have local file C:/Users\allis\AppData\Roaming\.minecraft\libraries\org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar but don't know what size or hash it should be. Have to assume it's good.
15:43:46 | launcher | main | info | Checking installations.
15:43:46 | launcher | main | info | Minecraft client 1.13-rift-1.0.4-66 is ready to start.
15:43:46 | launcher | main | info | Starting!
15:43:47 | launcher | main | info | Using default game log configuration client-1.12.xml (outputs XML)
15:43:47 | LaunchWrapper | main | info | Loading tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
15:43:47 | LaunchWrapper | main | info | Using primary tweak class name org.dimdev.riftloader.launch.RiftLoaderClientTweaker
15:43:47 | LaunchWrapper | main | info | Calling tweak class org.dimdev.riftloader.launch.RiftLoaderClientTweaker
15:43:47 | RiftLoader | main | info | Searching mods on classpath
15:43:47 | RiftLoader | main | info | Loaded mod 'rift'
15:43:47 | RiftLoader | main | info | Searching for mods in C:\Users\allis\AppData\Roaming\.minecraft\mods
15:43:47 | RiftLoader | main | info | Loaded mod 'litematica'
15:43:47 | RiftLoader | main | info | Loaded mod 'malilib'
15:43:47 | RiftLoader | main | info | Loaded 4 mods
15:43:47 | RiftLoader | main | info | Initializing mods
15:43:47 | org.dimdev.rift.Rift | main | info | Loading Rift!
15:43:47 | mixin | main | info | SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/allis/AppData/Roaming/.minecraft/libraries/org/dimdev/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
15:43:48 | mixin | main | info | FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
15:43:48 | mixin | main | info | Compatibility level set to JAVA_8
15:43:48 | RiftLoader | main | info | Done initializing mods
15:43:48 | LaunchWrapper | main | info | Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
15:43:48 | LaunchWrapper | main | info | Loading tweak class name org.dimdev.riftloader.OptifineLoader$Tweaker
15:43:48 | LaunchWrapper | main | info | Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
15:43:48 | LaunchWrapper | main | info | Calling tweak class org.dimdev.riftloader.OptifineLoader$Tweaker
10:43:48 | game |   | error | OptiFine ClassTransformer OptiFine ZIP file: C:\Users\allis\AppData\Roaming\.minecraft\mods\OptiFine_1.13.2_HD_U_E5.jar   <log4j:Event logger="mixin" timestamp="1548276228413" level="INFO" thread="main">     <log4j:Message><![CDATA[A re-entrant transformer 'org.dimdev.riftloader.RiftAccessTransformer' was detected and will no longer process meta class data]]></log4j:Message>   </log4j:Event>
10:43:48 | monitor | Process Monitor | error | expected <
10:43:48 | game |   | error | java.io.IOException: MD5 not matching, name: cwr.class, saved: 335e0240d00e535490570d9758b32b91, patched: 38cf4202efa2172a64f31de9a86a95ff 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:184) 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:108) 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:72) 	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1674) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) java.io.IOException: Base resource not found: cwt.class 	at optifine.Patcher.applyPatch(Patcher.java:143) 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:173) 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:108) 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:72) 	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1674) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)   <log4j:Event logger="mixin" timestamp="1548276228504" level="WARN" thread="main">     <log4j:Message><![CDATA[Error loading class: cwt (java.lang.ClassNotFoundException: The specified class 'cwt' was not found)]]></log4j:Message>   </log4j:Event>
10:43:48 | monitor | Process Monitor | error | expected <
15:43:48 | mixin | main | warn | @Mixin target cwt was not found mixins.litematica.json:IMixinRenderChunk
10:43:48 | game |   | error | optifine.xdelta.PatchException: truncated source file, aborting 	at optifine.xdelta.GDiffPatcher.copy(GDiffPatcher.java:181) 	at optifine.xdelta.GDiffPatcher.runPatch(GDiffPatcher.java:125) 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:67) 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:63) 	at optifine.Patcher.applyPatch(Patcher.java:149) 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:173) 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:108) 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:72) 	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1674) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) optifine.xdelta.PatchException: truncated source file, aborting 	at optifine.xdelta.GDiffPatcher.copy(GDiffPatcher.java:181) 	at optifine.xdelta.GDiffPatcher.runPatch(GDiffPatcher.java:125) 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:67) 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:63) 	at optifine.Patcher.applyPatch(Patcher.java:149) 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:173) 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:108) 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:72) 	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1674) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) java.io.IOException: Base resource not found: crb.class 	at optifine.Patcher.applyPatch(Patcher.java:143) 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:173) 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:108) 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:72) 	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1674) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)   <log4j:Event logger="mixin" timestamp="1548276228512" level="WARN" thread="main">     <log4j:Message><![CDATA[Error loading class: crb (java.lang.ClassNotFoundException: The specified class 'crb' was not found)]]></log4j:Message>   </log4j:Event>
10:43:48 | monitor | Process Monitor | error | expected <
15:43:48 | mixin | main | warn | @Mixin target crb was not found mixins.litematica.json:MixinChunkProviderClient
10:43:48 | game |   | error | optifine.xdelta.PatchException: truncated source file, aborting 	at optifine.xdelta.GDiffPatcher.copy(GDiffPatcher.java:181) 	at optifine.xdelta.GDiffPatcher.runPatch(GDiffPatcher.java:125) 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:67) 	at optifine.xdelta.GDiffPatcher.<init>(GDiffPatcher.java:63) 	at optifine.Patcher.applyPatch(Patcher.java:149) 	at optifine.OptiFineClassTransformer.getOptiFineResourcePatched(OptiFineClassTransformer.java:173) 	at optifine.OptiFineClassTransformer.getOptiFineResource(OptiFineClassTransformer.java:108) 	at optifine.OptiFineClassTransformer.transform(OptiFineClassTransformer.java:72) 	at org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:71) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:388) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:352) 	at org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:432) 	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:1674) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:908) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)   <log4j:Event logger="mixin" timestamp="1548276228517" level="FATAL" thread="main">     <log4j:Message><![CDATA[Mixin prepare failed preparing MixinMinecraft in mixins.litematica.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Mixin target type mismatch: cft is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@19b843ba]]></log4j:Message>     <log4j:Throwable><![CDATA[org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: cft is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@19b843ba 	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:514) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:917) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ]]></log4j:Throwable>   </log4j:Event>
10:43:48 | monitor | Process Monitor | error | expected <
15:43:48 | LaunchWrapper | main | error | Unable to launch java.lang.ClassNotFoundException: net.minecraft.client.main.Main 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	at java.lang.Class.forName0(Native Method) 	at java.lang.Class.forName(Class.java:348) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.litematica.json:MixinMinecraft] from phase [DEFAULT] in config [mixins.litematica.json] FAILED during PREPARE 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	... 6 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Mixin target type mismatch: cft is an interface in org.spongepowered.asm.mixin.transformer.MixinInfo$SubType$Standard@19b843ba 	at org.spongepowered.asm.mixin.transformer.MixinInfo$SubType.validateTarget(MixinInfo.java:514) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTarget(MixinInfo.java:917) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:891) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856) 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:809) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:506) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) 	... 12 more

**Comment by maruohon** [comment]
`Preparing to launch minecraft client for 1.13-rift-1.0.4-66` that is MC 1.13, not 1.13.2. The Litematica and malilib mods only work on 1.13.2.

**Comment by vacla** [comment]
this is for rift 1.13.2 with minecraft launcher: https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar

**Comment by shatteredcon** [comment]
Ah crud, thanks so much I am an idiot.
