### ISSUE TITLE
Glass Does not render in 20w22a.

### ISSUE THREAD

**Issue by LuisVervaet** [maruohon/litematica#191]
**NOTE: Please don't post "How do I do X?" type issues on this issue tracker. Such help requests should happen on Discord instead: https://discord.gg/VNVG3Wk (or if the previous link is broken: https://discord.gg/scicraft -> #masas-mods)**

**Describe the bug**
Glass Does not appear as visible it is just a blue outline.

**To Reproduce** (if not clear from the description already)
1. Look at glass

**Expected behavior** (if not clear from the description)
Glass is rendered

**Screenshots**
![2020-05-31_15 35 39](https://user-images.githubusercontent.com/39219859/83361193-e1da9380-a354-11ea-8912-4e843e390e6e.png)
![2020-05-31_15 35 43](https://user-images.githubusercontent.com/39219859/83361194-e30bc080-a354-11ea-8b6a-2dc1b1f4d31d.png)

**Comment by vacla** [comment]
do you have other mods than malilib and litematica? if so can you send a list with versions?

**Comment by maruohon** [comment]
This might be due to the new shader-based blending using framebuffers or whatever, which they added in 20w22a. It seems to render if the overlay is disabled...

**Comment by LuisVervaet** [comment]
The only other mods I have are carpet and tweakeroo, the issue also appears to be with slime blocks, I'm guessing its an issue with transparent blocks  
![2020-05-31_19 04 21](https://user-images.githubusercontent.com/39219859/83364787-b87c3080-a371-11ea-97ca-c4c06414603e.png)

**Comment by maruohon** [comment]
It's with any translucent blocks like stained glass, slime blocks, water, nether portals etc. and has to do with the rendering order and the render layers and sorting of them.

**Comment by maruohon** [comment]
This should be fixed in the latest (1.16.1) builds.
