### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by Emerqld** [maruohon/litematica#193]
**Minecraft version**
1.15.2
**Mod version and malilib version**
litematica-fabric-1.15.2-0.0.0-dev.20200515.184506.jar
malilib-fabric-1.15.2-0.10.0-dev.21+arne.2.jar

**Description of the bug**
When I try to launch my game with these 2 mods in my forge folder, it says that this is a fabric mod and cannot be loaded. I'm sure this has happened before I just want to know how to fix it.
---

**To Reproduce** (if not clear from the description already)
Not sure

**Screenshots**

![Screenshot (280)](https://user-images.githubusercontent.com/66695132/84186600-c3fce500-aa5e-11ea-9421-ff2d9792a5fe.png)

**Comment by maruohon** [comment]
Like it says, that Litematica version is made for the Fabric mod loader, not for Forge. Thus it will not work under Forge. Forge versions are planned, but it's not yet possible to make those ports, before Forge starts shipping with the Mixin library.

**Comment by Emerqld** [comment]
Thanks!
