### ISSUE TITLE
Fabric doesnt recognize or load the mod. I 

### ISSUE THREAD

**Issue by drewberni** [maruohon/litematica#203]
**NOTE**:
* Before reporting an issue, please make sure it has not already been fixed in a later version! Also make sure you have the latest version of **both Litematica and malilib!** There are occasionally changes that **will require** both mods to be updated at the same time, or something will break! The very latest development versions are available here: https://masa.dy.fi/mcmods/client_mods/ so you can quickly check if you have the latest builds. The versions on CurseForge are not usually the very latest builds, but important bugfixes will also be uploaded there.
* Please don't post simple questions like "How do I do X?" on this issue tracker. Such help requests should happen on Discord instead: https://discord.gg/VNVG3Wk (or if the previous link is broken: https://discord.gg/scicraft -> `#masas-mods`)
* Don't post issues for mod versions made for Minecraft snapshots on this tracker. The snapshot versions aren't "properly" supported or tested, they are provided as quick ports (when I have the time to make them) in a "might work, mostly" basis, and those issues should rather be handled on Discord as well.

**Minecraft version**
Which Minecraft version are you playing on?
1.16.1
**Mod version and malilib version**
Which **exact** mod version are you using? Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
**"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.
litematica-fabric-1.16.1-0.0.0-dev.20200630.022912 and malilib-fabric-1.16.1-0.10.0-dev.21+arne.1
**Description of the bug**
fabric just doesnt load the mods at all. if I have just litematica without malilib it will crash and say i need it. if i have malilib it will load minecraft with fabric but the mod isnt loaded
---

You can remove this and all the following non-applicable sections of this template (and the first paragraph notice)!

---

**Expected behavior** (if not clear from the description)
the mod to be loaded and working...
**To Reproduce** (if not clear from the description already)
not sure if you would be able to reproduce this...

**Screenshots**

**Additional context**
i am on a macbook pro and the 1.15 version has worked for me in the past

**Comment by maruohon** [comment]
Do you have Mod Menu installed to see if the mods appear on that list? Is the Litematica text not on the F3 screen and/or does the Litematica menu or config menu not open at all?

**Comment by drewberni** [comment]
yes i do and they dont appear in the mod menu

**Comment by maruohon** [comment]
Well I don't have any ideas why they wouldn't show up. But if it crashes without malilib, that points to  Litematica trying to get loaded. Did you check the F3 screen for the Litematica text, or try the Litematica main menu hotkey `M` or the config menu hotkey `M + C`.

**Comment by drewberni** [comment]
the new version u released today works for me so all good :)
