### ISSUE TITLE
Any axis rotation

### ISSUE THREAD

**Issue by JxM-92** [maruohon/litematica#210]
Dear maruohon,

It would be really useful to rotate schematics not only on Y axis, but also on X and Z axis...
if it already can, I don't know how... 

Sincerely,
Joe X

**Comment by maruohon** [comment]
This planned. Duplicate of https://github.com/maruohon/litematica/issues/190

**Comment by JxM-92** [comment]
oh ok, sorry...
should have look for it...
thanks! :)

**Comment by JxM-92** [comment]
But, until then...
do you know any workaround for now? not necessarily have to be a plugin, if you know a website that can do it once, even better...

**Comment by eatmyvenom** [comment]
1) paste in world with worldedit 
2) apply transformations
3) copy new schematic with litematica

**Comment by 0xt452** [comment]
Ive created a fork with a button to accomplish this.

[https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main](https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main)
