### ISSUE TITLE
litematica keeps crashing

### ISSUE THREAD

**Issue by destroyer4teen** [maruohon/litematica#213]
so bassically, litematica keeps crashing, it wont even open, and it doesnt say why, i have installed all the required mods for 1,15.2. please help

**Comment by vacla** [comment]
make sure if you have the latest malilib, can you also give the crashlog in a pastebin.com if this was the case?

**Comment by destroyer4teen** [comment]
it didnt give me a crashlog, and i did install the latest version of malilib

**Comment by vacla** [comment]
Can you give the latest.log then?

**Comment by destroyer4teen** [comment]
umm, idk, im not using it anymore as i found a workaround, thank you for helping tho
