### ISSUE TITLE
Loading schematic fail/ blocks not rendering at all

### ISSUE THREAD

**Issue by lemon2lice** [maruohon/litematica#220]
When i load any schematic even one i just created it loads in weird shapes and has none of the blocks looking correctly. i will attach a photo example, it makes the mod impossible to use..
![Minecraft_ 1 16 2 - Singleplayer 8_30_2020 5_49_14 PM](https://user-images.githubusercontent.com/70490728/91670206-4ab6e080-eae9-11ea-9056-79e02e70a25e.png)

**Comment by maruohon** [comment]
Disable Render Regions in Optifine, or if that doesn't work then disable shaders.

**Comment by lemon2lice** [comment]
I tried that i have both disabled still looks like this

**Comment by lemon2lice** [comment]
I also went through a lot of the optifine video settings to see if that helped and couldnt figure it out

**Comment by maruohon** [comment]
Does it get fixed if you take out Optifine and OptiFabric completely?

**Comment by lemon2lice** [comment]
yes i took out optifine and restarted and now its looking normal thank you!

**Comment by maruohon** [comment]
That's strange, I thought it should get fixed just disabling Render Regions and/or shaders. Not sure if you need to restart after disabling those.
