### ISSUE TITLE
Feature Request: display model in layers for easier Survival building

### ISSUE THREAD

**Issue by graemeg** [maruohon/litematica#23]
I'm totally new to schematics and litematica - actually only used schematics for 2 days so far. It is brilliant though. I mostly play in survival mode. Maybe there is already the feature I'm looking for, but if not, it would be very useful for building large schematics.

In survival play, it would be super useful if I could load and place my schematic, then toggle "layer 1" so it only shows me the bottom 1 level of blocks of the schematic. I could then place all required blocks (and do landscaping where needed). Then toggle the next layer up. Place all blocks etc and repeat. This would make it really easy to build large schematics from the bottom up - in survival game mode (where flying is not an option).

As I said, I'm totally new to using schematics, so apologies in advance if this feature already exists (would like to know how to do it then), or if I'm simply using schematics incorrectly. I'm still learning. :)

**Comment by maruohon** [comment]
This does already exist, yes. You can access/change it via the `Render Layers` tab in the in-game config GUI (which by default opens with `M + C` [on the QWERTY layout, I think it's `? + C` or something in AZERTY for example?]). And in Hotkeys you can set/change the hotkeys to cycle the layer mode, and to change the selected/current layer.

**Comment by jysocial** [comment]
Changing layer mode is M+PgUp(prior) and M+PgDown(next) by default, if I'm remembering correctly. You can use this to change to Single Layer mode, or the (imo) more helpful All Below mode. Once in these modes you can use PgUp and PgDown (sometimes known as Prior and Next) to change the layer of the schematic that is rendered. Note that the values here are world Y values, so it will start at Y = 0, not the first layer of the schematic itself.

**Comment by graemeg** [comment]
Awesome! Thanks @maruohon and @jysocial  for the quick responses. I'll give it a try tonight. It will make building large (tall) schematics *much* easier. :)

**Comment by graemeg** [comment]
Works perfectly. Thank you so much. LiteMatica is brilliant!

**Comment by maruohon** [comment]
The funny thing is that personally I consider the current 1.13.2 release (which I assume you are using?) to be complete trash compared to the current development version on 1.12. There are just so many small and also some a bit bigger improvements and additions and tweaks all over the place. I'm hoping to clear my TODO list for the next version in a reasonable time so I can also update the 1.13.2 version... as the current version even has some crash bugs, at least with the `pickBlockLast` hotkey (ie. don't enable that).

**Comment by graemeg** [comment]
Yes, I'm using the 1.13.2 version. As I said, totally new to minecraft schematics, so I have nothing to compare it against. I just completed my first large build using LiteMatica - it worked a treat. If you say more improvements are coming, I can't wait! It's already brilliant as far as I'm concerned. :)   :+1:
