### ISSUE TITLE
Show "fake" blocks as transparent

### ISSUE THREAD

**Issue by mfnalex** [maruohon/litematica#232]
Hi, thanks for this awesome plugin :)

Would it be possible to render the "fake" blocks from schematics in transparent, so that the player can see what blocks are behind?

**Comment by SunSerega** [comment]
There already is an option for that in visuals tab of M+C. I think it was closer to the end of that tab.

**Comment by maruohon** [comment]
In Visuals the `renderBlocksAsTranslucent` option, together with the `ghostBlockAlpha` value.

**Comment by mfnalex** [comment]
Thank you, I didn't find that option! :)
