### ISSUE TITLE
Strange Rendering Errors when placing a schematic

### ISSUE THREAD

**Issue by mark-d-holmberg** [maruohon/litematica#233]
**Minecraft version**
Which Minecraft version are you playing on?
1.16.3 

**Mod version and malilib version**
Which **exact** mod version are you using? Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
**"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.
* `malilib-fabric-1.16.3-0.10.0-dev.21+arne.1.jar`
* `minihud-fabric-1.16.3-0.19.0-dev.20200912.222204.jar`
* `litematica-fabric-1.16.3-0.0.0-dev.20200920.161640.jar`

**Description of the bug**
Strange rendering errors when loading a schematic into a world. See the images from the google drive link.

**Expected behavior** (if not clear from the description)
It should render the schematic without crazy visual glitches

**To Reproduce** (if not clear from the description already)
1. Load a schematic in 1.16.3 
2. Observe

**Screenshots**
https://drive.google.com/drive/folders/1YrXyiLt1Ar3jCBNOfAvlT82w851TgaGG?usp=sharing

**Additional context**
This is on a BSkyBlock world running BentoBox on a Sigot SMP Bungee Server.

**Comment by 0xfeeddeadbeef** [comment]
Turning shaders off can help.

**Comment by mark-d-holmberg** [comment]
I'm not using shaders.

**Comment by maruohon** [comment]
The rendering looks exactly like the issues that the changed vertex format from shaders causes. Check that you have shaders set to `OFF` instead of `Internal`. Or another thing that might fix it is disabling the Render Regions option. You will probably need to at least re-log or even restart the game after disabling the option(s).

**Comment by mark-d-holmberg** [comment]
That fixed it!
