### ISSUE TITLE
The "ToolItem" the stick, no longer works. 

### ISSUE THREAD

**Issue by mooneless** [maruohon/litematica#241]
**NOTE**:
* Before reporting an issue, please make sure it has not already been fixed in a later version! Also make sure you have the latest version of **both Litematica and malilib!** There are occasionally changes that **will require** both mods to be updated at the same time, or something will break! The very latest development versions are available here: https://masa.dy.fi/mcmods/client_mods/ so you can quickly check if you have the latest builds. The versions on CurseForge are not usually the very latest builds, but important bugfixes will also be uploaded there.
* Please don't post simple questions like "How do I do X?" on this issue tracker. Such help requests should happen on Discord instead: https://discord.gg/VNVG3Wk (or if the previous link is broken: https://discord.gg/scicraft -> `#masas-mods`)
* Don't post issues for mod versions made for Minecraft snapshots on this tracker. The snapshot versions aren't "properly" supported or tested, they are provided as quick ports (when I have the time to make them) in a "might work, mostly" basis, and those issues should rather be handled on Discord as well.

**Minecraft version**
Which Minecraft version are you playing on?

**Mod version and malilib version**
Which **exact** mod version are you using? Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
**"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.

**Description of the bug**

---

You can remove this and all the following non-applicable sections of this template (and the first paragraph notice)!

---

**Expected behavior** (if not clear from the description)

**To Reproduce** (if not clear from the description already)
2. Do X '....'
3. See error

**Screenshots**

**Additional context**

Yesterday i played just fine whit the schematics, used the stick as the "toolitem", i easily moved stuff around and created schematics whit no problem. I exit the game normal, i didnt do anything special, but today when i logged in, first thing i did was to enter my creative world and started to build, when i was done i wanted to create a schematics, i choose my stick (the tool item), but when i press down CTRL and scroll (just like i did yesterday), insetad of changing tool mode, the character in game just changes hotkey. The stick that are supposed to work as an toolitem, is just a stick. I checked the configuration menu, and the toolitem is listed as stick.

Also normaly when i choose the tool item in my hand, some text shows up down left corner, but nothing shows up today. Its like tool item dosent exist. (picture, red circle is where the text is supposed to show when i have the toolitem in hand)

Also tried changing the toolitem to other items, but still wont work as an toolitem.

I can no longer create schematics, since i need the toolitem to fill in the eria i want to make into schematics. Pressing M+R also did not fix problem. I tried googling, ask for help on reddit, and even youtube comments. But no one else got my problem.

I have tried deleting the mod and reinstalling, but does not work. The god damn toolitem do not exist anymore, and i have tried everything i know of, nothing fixes the problem. Also tried starting game whit no shaders on, but toolitem still dosent function. 

![2020-10-11_12 40 13](https://user-images.githubusercontent.com/72690817/95676630-c2375f80-0bbf-11eb-9f51-3fdc38f5d359.png)

![Stick](https://user-images.githubusercontent.com/72690817/95676620-b21f8000-0bbf-11eb-83e8-17dbafac5d56.PNG)

(sry bad english, not my native language)

**Comment by vacla** [comment]
Can you check if the toolItemEnabled is on true in your config in the generic tab?

**Comment by mooneless** [comment]
oh my good, youre a god. i asked so many people for help, but no one knew what to do :D so easy fix, thanks a lot. Still a noob when it comes to schematics. Do you want me to delete this post? since its fixed. and again, thanks a lot.

**Comment by vacla** [comment]
You can leave it, just click close so we know it is fixed, button should be nearby the comment button
