### ISSUE TITLE
Coral fans render stragely when on top of a block.

### ISSUE THREAD

**Issue by Megaminx12** [maruohon/litematica#244]
Coral fans render stragely when on top of a block. Can be seen from screenshot.

Playing on 1.16.3, mods are in a screenshot. Mod versions:

Litematica | 0.0.0-dev.20200920.161640  | 2020-09-20 16:16:49
MaLiLib | 0.10.0-dev.21+arne.1 | 2020-09-12 22:10:07

(copied and pasted from masa's website, just downlaoded them to test in newest version)

Schematic link: https://discordapp.com/channels/594920796867133446/594921911276929027/763065248650756126

Expected behaviour is for the coral fan to be limited to one block

To reproduce:
1) Load up a schematic that contains a coral fan on the top face of a block (e.g. tnt based farm with duper - fallen breath's farms have the coral fan on the top face of a block)
2) Observe coral fan.

This can be an issue if there is a block next to the coral fan.

![mods](https://user-images.githubusercontent.com/68545280/96011364-bdcaab00-0e3a-11eb-9606-dbaf4dafbfa3.JPG)

![2020-10-14_16 30 34](https://user-images.githubusercontent.com/68545280/96011435-cf13b780-0e3a-11eb-818b-a6f611e40501.png)

**Comment by maruohon** [comment]
That is just how the vanilla model is made. The colored missing block overlay in Litematica uses the quads (rectangles) from the model directly, there are no custom special cases or handling done to it. This same thing can be seen in both normal and redstone torches.

The best solution would be to just make a better custom model for them in a resource pack, which uses better sized quads and not "full 16x16 pixel quads" if the actual used texture area is smaller (such as in torches).

**Comment by Megaminx12** [comment]
Thanks.
