### ISSUE TITLE
How to rotate Schematic

### ISSUE THREAD

**Issue by pixel48200** [maruohon/litematica#245]
I know there is an option for rotating the schematic but only on X and Y axis, I have an mapart thats Vertical and i need to put it on ground.

**Comment by vacla** [comment]
Duplicate of #190

**Comment by pixel48200** [comment]
So it isnt in mod yet ?

**Comment by vacla** [comment]
No, not yet, it is on the todo list

**Comment by maruohon** [comment]
Closing as duplicate

**Comment by 0xt452** [comment]
Ive created a fork with a button to accomplish this.

[https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main](https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main)
