### ISSUE TITLE
Litematica bad block rendering

### ISSUE THREAD

**Issue by PottersGame** [maruohon/litematica#251]
![2020-10-22_08 19 17](https://user-images.githubusercontent.com/69338453/96833118-2d92f400-1440-11eb-8a06-6200bf235bb3.png)
Thanks for all help

**Comment by DeadlyMC** [comment]
Do you hv shaders on with optifine? You may also need to disable Render Regions and Fast Render as well to fix other rendering issues.

**Comment by vacla** [comment]
See #247

**Comment by PottersGame** [comment]
I dont use shaders but i may disable fast render.

**Comment by PottersGame** [comment]
i had internal shader on so i turned them off a int worked thanks
