### ISSUE TITLE
Schematics not loading properly.

### ISSUE THREAD

**Issue by LyfHax420** [maruohon/litematica#255]
A couple days ago I downloaded litematica to use some schematics, well, I did as the tutorial said and I could place a schematic perfectly, now, I wanted to try a few others and they are just not loading correctly. It justs loads like if the file was corrupt or something. I am using the lastest version of the game (1.16.3) and the mod, all supports mods are up to date and shadders are turned off as well. I will now post a picture so you guys can see.

https://imgur.com/2lud1GB

**Comment by maruohon** [comment]
You must have shaders enabled (maybe on Internal instead of OFF)? Set them to OFF and restart the game.

**Comment by LyfHax420** [comment]
Oh yeah it was this, thank you bro.
