### ISSUE TITLE
Material List

### ISSUE THREAD

**Issue by smartin1018** [maruohon/litematica#26]
SUGGESTION: An option to export the material list as a CSV file.

**Comment by maruohon** [comment]
Implemented in the latest builds.

**Comment by chonkey821** [comment]
where is the txt file saved for material list

**Comment by maruohon** [comment]
@chonkey821  Currently they go to `.minecraft/config/litematica/`. You can also click the link in chat to directly open it.

**Comment by chonkey821** [comment]
ok i found it...thanks for the quick reply

**Comment by maruohon** [comment]
@Greg-J Hold shift when you click on the write to file button. The tooltip also mentions this.
