### ISSUE TITLE
Actions don't work in Rift 1.13.2

### ISSUE THREAD

**Issue by Kermalis** [maruohon/litematica#27]
... in the dev version you uploaded and when I clone and build myself.

addSelectionBox (M+A) instead opens the menu (M) after I stop moving left (A)
toolPlaceCorner1 (BUTTON_1) and toolPlaceCorner2 (BUTTON_2) do not cause anything to happen or even move the player's hand
I do not have easy place enabled

I'm unable to test other features of this mod because these are what are needed to get started

**Comment by maruohon** [comment]
For M + A to work, you need to be in the Area Selection mode. You didn't say if that is the case. And then after that, for the tool corner actions to do something, you must have an element (either the origin point, or a sub-region box) selected.

The upcoming version simplifies and improves especially the Area Selection mode quite a bit... currently it can be somewhat mysterious/confusing for new users.

**Comment by Kermalis** [comment]
Yep, I'm in area selection (1/7)
I tried to follow the pastebin and the twitch vod

**Comment by maruohon** [comment]
Did you also create a new selection via the selection browser? And it should also be selected in the browser (white outline), and then you should also see that name on the tool HUD.

**Comment by Kermalis** [comment]
Ah, that was the part I was missing. I did create a new selection, but I was under the impression that I had to double click it (which deselected it and I wasn't realizing)
Thanks for the help, sorry for assuming it was an issue with the mod :P
