### ISSUE TITLE
Building a placed schematic in survival

### ISSUE THREAD

**Issue by Wirelli** [maruohon/litematica#270]
So while building a schematic in survival, if I don't place a block from above, and even sometimes then, it will change one of the surrounding hologram blocks to that block in question. Is there a way to turn this off? I have the schematic locked, and restriction mode on, yet it still does it. Only way I've found to undo it is to reload the schematic.

**Comment by maruohon** [comment]
It sounds like you are in the Schematic Rebuild mode? That mode is meant for editing the schematics. So just switch to any other mode, usually you would be in the Schematic Placement mode while working with loaded schematics. I do need to rename the Schematic Rebuild mode to Schematic Edit mode to avoid this confusion... The reasoning for that name was that it allows you to re-build parts of the schematic, by removing or adding blocks or changing block types.

**Comment by Wirelli** [comment]
That was the issue, thanks for the quick response, really appreciate it!
