### ISSUE TITLE
Is there a way to rotate schematics the other way ?

### ISSUE THREAD

**Issue by john13210** [maruohon/litematica#280]
from vertical to horizontal plane

**Comment by maruohon** [comment]
Duplicate of #190 (which is even pinned). TL;DR; Not yet, but it's planned.

**Comment by 0xt452** [comment]
Ive created a fork with a button to accomplish this.

[https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main](https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main)
