### ISSUE TITLE
Missing blocks !

### ISSUE THREAD

**Issue by Squidammo** [maruohon/litematica#285]
Whenever I'm loading a big schematic, it's missing many blocks. It's very annoying to have a lot of holes in our builds.

**Comment by Squidammo** [comment]
All of my schematics are .schematics, they are from My solo worlds, I'm using Litematica 1.16.4 and My schematics are from 1.9 and more. (I saved them with the schematica mod)

**Comment by maruohon** [comment]
Are they missing certain block types completely, or are they more like missing some section entirely?
If you have Optifine, then disable the Render Regions setting, and also set shaders to OFF and restart the game.
If that's not the case, then can you provide screenshots and also post some of the schematics to test with?

**Comment by Squidammo** [comment]
So It's missing some sections, not certain block types and I'm not using optifine. I will send you a screenshot of a Panda I built in 1.12 and saved with schematica.

![2021-01-18_18 08 10](https://user-images.githubusercontent.com/77607566/104970056-3bf99900-59b8-11eb-9747-d7a8d7f60f6b.png)

I can't post schematics here since the website does not support .schematics files

So as you can see, there's a big hole with 2-3 little holes. many of my builds have the same problem and it happens on any type of blocks.

**Comment by maruohon** [comment]
I think you can put the schematics into a zip archive to post them here. Or alternatively put them to Google Drive, Dropbox or MediaFire or something. I can't do anything or know what exactly is wrong if I don't have the original schematic to compare to. Based on this screenshot alone I don't even know where blocks are missing, and what block types those were supposed to be.

**Comment by Squidammo** [comment]
https://www.mediafire.com/file/t2e3iezruzy8wdb/TerraForming_Panda_%2528D%2529.schematic/file
Here's my schematic link
Also the part missing is the hole where we can see some orange wool in the background, it's supposed to be grass blocks and some stone / clay / dirt

**Comment by maruohon** [comment]
No, there is a separate option `pasteReplaceBehavior` you can change to decide how blocks get replaced when pasting (you can quickly cycle it by default with `Ctrl + M`).

The paste command is only used in multiplayer pasting, and you can't change it to anything that has different arguments than the normal setblock command. That option is mostly useful if there are some custom setblock commands that have special properties, such as not causing block updates.

**Comment by Squidammo** [comment]
Alright thank you, I hope you find the problem with the missing blocks too :)

**Comment by maruohon** [comment]
It looks like the schematic just doesn't have those blocks.

Here is that schematic loaded with the 1.12.2 version of Litematica:
![2021-01-20_02 20 21](https://user-images.githubusercontent.com/2331050/105110307-0099c000-5ac7-11eb-9047-76f6e9b7c344.png)

And here it is loaded with Schematica (so obviously in 1.12.2 as well):
![2021-01-20_02 26 12](https://user-images.githubusercontent.com/2331050/105110376-1d35f800-5ac7-11eb-9798-238575f7fd2a.png)

**Comment by Squidammo** [comment]
Well that's weird but I guess I'll have to re-build them and save them again, Thank you for your time, have a good day / night :)
