### ISSUE TITLE
Crash when joining the world

### ISSUE THREAD

**Issue by dijmapushnya** [maruohon/litematica#292]
I'm using litematica-fabric-1.16.4-0.0.0-dev.20210120.213004, malilib-fabric-1.16.4-0.10.0-dev.21+arne.2 and fabric_api_0.29.41.16. Minecraft 1.16.4 Fabric 0.11.1
When i join the world with enablerender off everything is ok, or if there is no loaded schematics. But if i load any schematic my minecraft crashing(i tried on different worlds). So there is log
Description: Unexpected error

> java.lang.NoSuchMethodError:` com.google.common.util.concurrent.Futures.addCallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureCallback;)V
> 	at fi.dy.masa.litematica.render.schematic.ChunkRenderWorkerLitematica.processTask(ChunkRenderWorkerLitematica.java:188)
> 	at fi.dy.masa.litematica.render.schematic.ChunkRenderDispatcherLitematica.updateChunkNow(ChunkRenderDispatcherLitematica.java:176)
> 	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.setupTerrain(WorldRendererSchematic.java:368)
> 	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewisePrepareAndUpdate(LitematicaRenderer.java:320)
> 	at net.minecraft.class_761.handler$zik000$onPostSetupTerrain(class_761.java:5615)
> 	at net.minecraft.class_761.method_3273(class_761.java:1401)
> 	at net.minecraft.class_761.method_22710(class_761.java:1552)
> 	at net.minecraft.class_757.method_3188(class_757.java:1022)
> 	at net.minecraft.class_757.method_3192(class_757.java:693)
> 	at net.minecraft.class_310.method_1523(class_310.java:1048)
> 	at net.minecraft.class_310.method_1514(class_310.java:681)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
> 
-

> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at fi.dy.masa.litematica.render.schematic.ChunkRenderWorkerLitematica.processTask(ChunkRenderWorkerLitematica.java:188)
> 	at fi.dy.masa.litematica.render.schematic.ChunkRenderDispatcherLitematica.updateChunkNow(ChunkRenderDispatcherLitematica.java:176)
> 	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.setupTerrain(WorldRendererSchematic.java:368)
> 	at fi.dy.masa.litematica.render.LitematicaRenderer.piecewisePrepareAndUpdate(LitematicaRenderer.java:320)
> 	at net.minecraft.class_761.handler$zik000$onPostSetupTerrain(class_761.java:5615)
> 	at net.minecraft.class_761.method_3273(class_761.java:1401)
> 	at net.minecraft.class_761.method_22710(class_761.java:1552)
> 	at net.minecraft.class_757.method_3188(class_757.java:1022)
> 
> -- Affected level --
> Details:
> 	All players: 1 total; [class_746['gayshit'/161, l='ClientLevel', x=1297.99, y=107.46, z=324.23]]
> 	Chunk stats: Client Chunk Cache: 1089, 729
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (-96,4,128), Chunk: (at 0,0,0 in -6,8; contains blocks -96,0,128 to -81,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 8009058 game time, 6000 day time
> 	Server brand: fabric
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.class_638.method_8538(class_638.java:617)
> 	at net.minecraft.class_310.method_1587(class_310.java:2239)
> 	at net.minecraft.class_310.method_1514(class_310.java:704)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
> 
-

> Fabric Mods: 
> 		fabric: Fabric API 0.29.4+1.16
> 		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
> 		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
> 		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
> 		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
> 		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
> 		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
> 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
> 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
> 		fabricloader: Fabric Loader 0.11.1
> 		java: Java HotSpot(TM) 64-Bit Server VM 8
> 		litematica: Litematica 0.0.0-dev.20210120.213004
> 		malilib: MaLiLib 0.10.0-dev.21+arne.2
> 		minecraft: Minecraft 1.16.4
> 		mm: Manningham Mills 2.1
> 		optifabric: OptiFabric 1.8.16
> 		plasmovoice: PlasmoVoice 0.0.2
> 		su_plo_voice_common: common 0.0.16
> 		voxelmap: VoxelMap 1.10.14
> 		worldedit: WorldEdit 7.2.2+fc3c499

Please help.

**Comment by maruohon** [comment]
No idea why this would happen, kind of seems like a library mismatch of some kind. Make sure you have at least 2 GB of memory allocated to the game. Then maybe try re-downloading Litematica. If those don't help, then try disabling any other mods, although I tested it with everything else on the list shown except whatever those plasmovoice and su_plo_voice_common mods are.

If you are using the vanilla launcher, then maybe try deleting this file:
![image](https://user-images.githubusercontent.com/2331050/106050060-803f1480-60ef-11eb-96e6-fb2db54e4d34.png)

**Comment by dijmapushnya** [comment]
> No idea why this would happen, kind of seems like a library mismatch of some kind. Make sure you have at least 2 GB of memory allocated to the game. Then maybe try re-downloading Litematica. If those don't help, then try disabling any other mods, although I tested it with everything else on the list shown except whatever those plasmovoice and su_plo_voice_common mods are.
> 
> If you are using the vanilla launcher, then maybe try deleting this file:
> ![image](https://user-images.githubusercontent.com/2331050/106050060-803f1480-60ef-11eb-96e6-fb2db54e4d34.png)

Problem was with this plasmovoice mod. Thanks for help.
