### ISSUE TITLE
Forge update please

### ISSUE THREAD

**Issue by Antyss77** [maruohon/litematica#293]
**Is your feature request related to a problem? Please describe.**
Hello, can you make the mod compatible with forge? Fabric is not used/useful for everyone

**Describe the solution you'd like**
I would like to give you a ready-made solution, unfortunately I don't have the skills, but please know that I love and support your project.

**Describe alternatives you've considered**
I don't know if there are really alternatives sorry

**Additional context**

**Comment by maruohon** [comment]
See #234.

Basically yes, Forge ports are coming, but there is still a lot of work left before the code is ready to be even ported from 1.12.2 to the later MC versions again, and the Forge ports will be done from that new code.
