### ISSUE TITLE
cant make selections

### ISSUE THREAD

**Issue by sapppho** [maruohon/litematica#298]
im on fabric 1.16.5.

most of the time when i join either a singleplayer world or a survival server, im unable to make selections. the stick doesn't allow me to change modes (i can do that in the menu, no problem). but when i go to make a selection, which i know how to do, and normally works, nothing happens. theres no selection to edit. i can't use the stick to edit the nonexistent selection. ive tried relogging but it wont fix. is there any way to fix this other than just waiting?

im using malilib 1.16.4, as the 1.16.5 version isnt out yet. i should add that ive been having this issue since i had 1.16.1 in BOTH mods. i downloaded litematica 1.16.5 as well, though for some reason the file name says 1.16.4

**Comment by maruohon** [comment]
Do you see the Tool HUD on the bottom left when you are holding the tool? If not, then the tool is not "active". There are basically three requirements for the tool to be recognized as active:

* The mod main rendering option has to be enabled (`M + R`)
* The tool item must be enabled (`M + T`)
* You must be holding the currently configured tool item (it can be set in Generic configs). Note that the check is NBT-sensitive - if for example the server adds some lore text to items, then configured tool items with no NBT data would not be recognized. You can also use an empty hand as a tool, by either leaving the field empty, or putting in the literal string `empty`.

**Comment by sapppho** [comment]
i didnt see any HUD - your tips worked tho, tysm!
