### ISSUE TITLE
I unbound the Settings hotkey (M + C) and can't change it due to obvious reasons.

### ISSUE THREAD

**Issue by Cooloop10** [maruohon/litematica#30]
(Read Title) Please help, this mod is by far the best client-side ANYTHING i have come across and i just really want to use it

**Comment by jysocial** [comment]
Need a little more info to be able to help you. What version of the game are you running - 1.13.2 or 1.12?

**Comment by Cooloop10** [comment]
> Need a little more info to be able to help you. What version of the game are you running - 1.13.2 or 1.12?

Running Version 1.13.2

**Comment by vacla** [comment]
@Cooloop10 go to .minecraft/config/litematica.json , there you can set it back to the hotkey.

**Comment by SunSerega** [comment]
Keybinds are in file:
`.minecraft\home\1.13\config\litematica.json`
or just:
`.minecraft\config\litematica.json`

This file can be opened with any text editor.

File these lines:
```
    "openGuiSettings": {
      "keys": "M,C",
      "settings": {
        "activate_on": "PRESS",
        "context": "INGAME",
        "allow_extra_keys": false,
        "order_sensitive": true,
        "exclusive": false,
        "cancel": true
      }
    },
```
For you, line `"keys":` probably contains nothing. Close your game, add `"M,C"` back and start game again.

**Comment by maruohon** [comment]
(In the next version there is also a button to the settings menu in the main menu).

For now you'll just have to add the hotkey manually to the config file, or alternatively (if you don't have many other config changes you want to keep), just delete the config file and then launch the game and it will generate a new default config. In the Rift version the config file is located at `.minecraft/config/litematica.json` . Inside the `Hotkeys` object is an entry for `openGuiSettings`. And then you can do what the others already ninja'd above :P

**Comment by Cooloop10** [comment]
Thank you guys
