### ISSUE TITLE
Schematica cutting blocks off?

### ISSUE THREAD

**Issue by Gonzuwu** [maruohon/litematica#300]
![image](https://user-images.githubusercontent.com/64500209/107362082-f759ad00-6ae0-11eb-8474-9c6c93a349a3.png)
So im trying to make a huge sugar cane farm and the schematica is cutting allot of stuff of like in the picture. 
Any ideas why?

**Comment by maruohon** [comment]
Which MC version and mod version are you using? Can you send me the schematic to test with?

**Comment by Gonzuwu** [comment]
Im using 1.12.2 and yes fo sure

**Comment by Gonzuwu** [comment]
[sugar.zip](https://github.com/maruohon/litematica/files/5951307/sugar.zip)

**Comment by maruohon** [comment]
Okay if you are in 1.12.2, and the title says `Schematica`, you do actually mean the Schematica mod and not Litematica? In that case you posted this issue in the wrong repository, as Litematica is a totally different mod... that does mostly the same thing as Schematica though, plus some more. And from the looks of it Schematica is not getting updated or maintained anymore.

If you want to try out Litematica, you can find the 1.12.2 versions here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.12.2 You will also need malilib from there for Litematica to work.

**Comment by Gonzuwu** [comment]
Oky sorry and thank you :)

**Comment by maruohon** [comment]
But as to your schematic, it does actually only contain that small part:
![2021-02-09_14 33 52](https://user-images.githubusercontent.com/2331050/107364291-ebbbb580-6ae3-11eb-9bc7-ae1cd8acce2e.png)
