### ISSUE TITLE
i know how to use mcedit with . schematic files but what about .schem ones ?

### ISSUE THREAD

**Issue by ItsDidzz** [maruohon/litematica#303]

**Comment by maruohon** [comment]
Please use either Discord or the Discussions board here on GitHub for questions like this, this is not an issue report or even directly related to Litematica.

And the answer is that you can't directly use `*.schem` files with MCEdit, as far as I know. MCEdit only works for 1.12.2 and older stuff, and the Sponge schematics (`*.schem`) are mainly used in 1.13+. So you would instead want to use the new Amulet map editor with those, possibly. I'm not sure if it supports that format already, and how many editing features it has implemented at this point. Or alternatively paste the schem to a temporary world with World Edit, and then use Amulet to downgrade that world to 1.12.2 format, and then use  MCEdit there, depending on what and in which MC version you are actually working on.
