### ISSUE TITLE
.litematica files not fully rendering

### ISSUE THREAD

**Issue by sapppho** [maruohon/litematica#308]
Which Minecraft version are you playing on?
i am playing on minecraft 1.16.5, with 1.16.5 litematica and 1.16.5 malilib

i made a big selection today, brought it into my creative world, pasted it, and only about half of the blocks are actually showing up
![2021-03-04_19 55 59](https://user-images.githubusercontent.com/78660899/110056478-83e43d80-7d24-11eb-8194-9977eb54c9ad.png)
looks like this. is there anything i can do to fix this?

**Comment by maruohon** [comment]
That does appear like half of the schematic is somehow just empty. Was it saved from single player or server? Was that part of the selection properly loaded when you saved it?

**Comment by sapppho** [comment]
it was saved from a server, but I'm not sure if it was fully loaded when i saved it. ill try that when i log on

**Comment by maruohon** [comment]
Normally the save task should not even complete unless the mod sees all the chunks, but some (spigot variant) servers seem to do weird things with chunk syncing, and there are also some other client-side mods that might mess with the "is this chunk loaded?" check in Litematica, possibly causing it to save from chunks that are not actually loaded yet.

**Comment by sapppho** [comment]
thanks!
