### ISSUE TITLE
clamping mode does not work

### ISSUE THREAD

**Issue by D1mushka** [maruohon/litematica#309]
So, the problem is that in previous versions of litematica, when I turned on easy place mode, I could just hold down the right mouse button and build, now I need to click on it constantly to put blocks. I'm playing on the latest version 1.16.5 before I played on 1.16.3. I don't know, maybe there is an option somewhere that fixes this?

Post scriptum: English is not my native language, so there may be mistakes somewhere.

**Comment by maruohon** [comment]
Do you have the `easyPlaceHoldEnabled` option still enabled? Without that you will need to click for every block.

**Comment by D1mushka** [comment]
hank you very much, I did not know that this is possible! ;)
