### ISSUE TITLE
Right mouse button Doesn't work outside of inventory

### ISSUE THREAD

**Issue by Cooloop10** [maruohon/litematica#31]
Rmb only working in inventory and menus indicates that its something along the lines of bind conflict because if i bind "use item/place block" to another key, it works.
Please help thanks

**Comment by maruohon** [comment]
You probably have either the Easy Place mode or Placement Restriction mode enabled. Those prevent placing blocks/right clicking outside the schematic areas, to try to prevent wrongly placed blocks. In the latest dev versions they only take effect when right clicking on blocks within 2 blocks of a schematic sub-region, and they also give you a warning message... so in general things will be a lot less mysterious and confusing in the next version.

**Comment by Cooloop10** [comment]
oh all good problem solved thanks!

**Comment by maruohon** [comment]
Btw if you have further questions, there is a `#masa-mods-feedback` channel on the SciCraft Discord (https://discord.gg/scicraft) which is a bit more convenient for question type issues or if you need usage help.
