### ISSUE TITLE
Crash with Colormatic and Litematica

### ISSUE THREAD

**Issue by helpimnotdrowning** [maruohon/litematica#310]
Running:
- Minecraft 1.16.5
- Litematica v0.0.0-dev.20210215.172138
- MaLiLib v0.10.0-dev.21+arne.5
- Colormatic v2.2.8+mc1.16.3

**Description of the bug**
Game crashes when placing schematic containing water and joining world with a loaded schematic containing water

**Expected behavior**
Game shouldnt crash

**To Reproduce**
1. Go to "load schematics"
2. Load schematic with water
3. Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/35247379/110531455-30d20800-80e1-11eb-84ce-c855abc39738.png)
![image](https://user-images.githubusercontent.com/35247379/110531467-3596bc00-80e1-11eb-9da8-d47a29324f78.png)
![image](https://user-images.githubusercontent.com/35247379/110531472-36c7e900-80e1-11eb-93bc-63afa82e464e.png)
![image](https://user-images.githubusercontent.com/35247379/110531478-37f91600-80e1-11eb-97c7-f301195c1dfe.png)

**Crash Report**
[crash-2021-03-09_14.10.00-client.txt](https://github.com/maruohon/litematica/files/6111165/crash-2021-03-09_14.10.00-client.txt)

**Additional context**
- Considering its probably a problem with water tinting, it might also affect schematics with grass blocks/tall grass/leaves
- Might need a resource pack that makes use of colormaps, am using [Classic Alternative](https://www.planetminecraft.com/texture-pack/classic-alternative/)

**Comment by kvverti** [comment]
The 1.17 (future) release of Colormatic should no longer have this incompatibility.

**Comment by helpimnotdrowning** [comment]
Yep, no crashes with Colormatic 2.2.9 for 1.16
