### ISSUE TITLE
The schematic dont show in the menu and i dont have files in %appdata% .minecraft at schematics

### ISSUE THREAD

**Issue by SilmoPlays** [maruohon/litematica#326]
Help me please
![imagine_2021-04-02_205507](https://user-images.githubusercontent.com/81825802/113440764-b487c780-93f5-11eb-9759-431b72f55de2.png)
![2021-04-02 (3)](https://user-images.githubusercontent.com/81825802/113440778-bf425c80-93f5-11eb-9c1a-8f93f379e392.png)

**Comment by maruohon** [comment]
That schematic is most likely in the Sponge schematic format, which is currently only supported in the 1.12.2 version of Litematica.  So currently you would need to paste it to a temporary world with World Edit and then save it from that with Litematica.
Here is a quick howto on that: https://github.com/maruohon/litematica/issues/265#issuecomment-736019447

**Comment by maruohon** [comment]
Closing this, since it's basically the same as #327
