### ISSUE TITLE
(Request)    Request for a Schematic to Litematic file converter

### ISSUE THREAD

**Issue by Cooloop10** [maruohon/litematica#33]
(Or a way to use schematic files).

**Comment by maruohon** [comment]
These already exist in the 1.12.x version, and I'll try to implement the importing and exporting again for the next 1.13.2 version, but it won't work 100% correctly due to the flattening (block renames and changes) that happened in vanilla 1.13.

**Comment by Cooloop10** [comment]
okie

**Comment by JxM-92** [comment]
Would this be implemented for the new versions?
for example having a ".schematic" file from 1.12.2 and using it on litematica  in 1.16.1?

**Comment by maruohon** [comment]
Loading old 1.12 (or older) `*.schematic` files is actually the only cross-MC version support that works properly atm (mostly). It exists for all the 1.13.2+ Litematica versions, ie. 1.13.2, 1.14.4, 1.15.2 and 1.16.1. All other schematic formats currently can't be loaded across the 1.12.2 <-> 1.13+ version boundary without lots of blocks vanishing. There is WIP support for proper cross-MC-version conversion in my 1.12.2 dev code, but that code still needs a lot more work before it's complete and there are no public builds of that yet.

And yes everything from 1.12.2 will come to the later versions too, the only question is when I'll have things ready to be ported again...
