### ISSUE TITLE
An legit mode option

### ISSUE THREAD

**Issue by BrennoMaturino1** [maruohon/litematica#340]
Legit mode is an option that dont use /setblock, it will allow the player to use the mod in non-op servers and survival worlds, it will build the file automatically by walking and sending place block packets

baritone doenst support .litematic files

**Comment by maruohon** [comment]
Uhh what. Based on the title I thought you wanted to block/remove the Easy Place mode as being too cheaty. But instead this is a feature request for a printer?

The current plan is to rip out the Easy Place mode into a separate small extension mod, and the printer will also be another separate extension mod. And there is no timeline for when it might be (or even any kind of guarantee that it will ever be) implemented, as it will come after all the other hundreds of things on my todo list...

There is currently already a printer extension mod by EatMyVenom. And there is also a fork of the mod with a printer added, but it doesn't seem to really pull upstream changes actively, so it's behind on some other upstream features and fixes.

**Comment by maruohon** [comment]
The issue #25 tracks the implementation of a printer (which will actually be in a separate extension mod).
