### ISSUE TITLE
I wanna rotate shematic what i downloaded

### ISSUE THREAD

**Issue by enloken** [maruohon/litematica#341]
I downloaded the pixel art scheme, but it is vertical, how can I rotate it horizontally?

**Comment by maruohon** [comment]
That functionality is not yet implemented in Litematica (hopefully in the next bigger update). For now you would need to use World Edit to flip it.

**Comment by maruohon** [comment]
Closing this, as issue #190 tracks the planned/requested extra rotation support.

**Comment by 0xt452** [comment]
Ive created a fork with a button to accomplish this.

[https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main](https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main)
