### ISSUE TITLE
Blocks Not Replaced While Pasting

### ISSUE THREAD

**Issue by Coolbizzaro** [maruohon/litematica#348]
I am not very knowledgeable about this mod and I got it pretty recently. Is there an option to replace blocks with blocks from the schematic instead of just not building there. Thanks.

**Comment by maruohon** [comment]
There is a `pasteReplaceBehavior` option in the Generic config category. You can also quickly cycle the value by default with `Ctrl + M`, and the current value is show on the "tool HUD" on the bottom left when you are in the Paste mode.

**Comment by Coolbizzaro** [comment]
Tysm I tested it and it works!
