### ISSUE TITLE
Printer For Survival Mode

### ISSUE THREAD

**Issue by BooyahSquadians69** [maruohon/litematica#349]
Can You Add A Printer For Survival Mode?

I Want To Build An Awesome Build And I Have All Materials For It But When I Try To Use Bariotine for autobuild it shows it needs a item called null and there is no item null in game 

Can You Put Auto Build IN Litematica? So That We Can Just Auto Build Huge Things

Or Can You Tell How To Fix That Null Problem That I Told You

**Comment by SkarDeWitt** [comment]
Baritone is kinda broken since 1.12.2+, it will not load schematics and will give you this error. There will not be a printer option in this mod for some time, although it is on the author's checklist.

**Comment by maruohon** [comment]
The issue #25 tracks the implementation of a printer (which will actually be in a separate extension mod).
