### ISSUE TITLE
selection Tool not working

### ISSUE THREAD

**Issue by LUKDUCK** [maruohon/litematica#351]
1.16.4 20201103.184101 Litmatica
1.16.4-0.10.0  malilib

(masa: removed issue template fluff)

**Comment by maruohon** [comment]
Do you mean the tool does not work at all and you don't even see the "tool HUD" on the bottom left when you hold the item? In that case you either have the tool  disabled (`M + T`) or the main rendering disabled (`M + R`) or the tool is not recognized (does it have NBT data on it?).

If you mean you are unable to control a selection box, then if you are in the "Normal" selection mode, then you first need to create or select an area via the Area Selection Browser. Or if you are or will switch to the "Simple" selection mode (in the main menu, middle left), then you only have one generic selection and box, and you don't need the Area Selection Browser and the individual selections created via it.

**Comment by LUKDUCK** [comment]
Sorry I'm kinda stupid. I had all rendering  off. Turned that on and worked thanks for the help though.
