### ISSUE TITLE
Rotate over multiple axis.

### ISSUE THREAD

**Issue by LordVenom77** [maruohon/litematica#357]
The option to rotate and mirror the schematic works great, however it only seems to rotate and mirror over one axis (zed). I'd like to be able to change which axis the schematic rotates and mirrors on to x or y, not just zed.

**Comment by maruohon** [comment]
This is planned, and will likely be added during the upcoming (partial) rewrite of the mod.

Closing as duplicate of #190. (Although that one doesn't specifically mention rotation around any axis, but the planned implementation should allow transforming in any possible orientation.)

**Comment by 0xt452** [comment]
Ive created a fork with a button to accomplish this.

[https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main](https://github.com/0xt452/Litematica-Vertical-Rotation/tree/main)
