### ISSUE TITLE
`enableRendering` feature breaks entity distance

### ISSUE THREAD

**Issue by NoComment1105** [maruohon/litematica#359]
**Minecraft version**
1.16.5

**Mod version and malilib version**
litematica-fabric-1.16.4-0.0.0-dev.20210120.213004
malilib-fabric-1.16.3-0.10.0-dev.21+arne.1

**Description of the bug**
With the Entity distance set to 500% and being 1 block outside the distance limit for 75% entities do not render. Turning off this feature makes the entities render. If you have this feature on and go forward a block the entities then render

**Expected behavior** (if not clear from the description)
Entities to render even 1 block outside the 75% range using 500% render distance

**To Reproduce** (if not clear from the description already)
1. Have an entity in a fixed position
2. Set Entity distance to 75% and run backwards until the entity disappears
3. Set the entity distance to 500%. Observe no entity
4. Walk forward 1 block, Observe entity
5. Go back 1 block and turn `enableRendering` off. Observe entity this time

**Screenshots**
1 Block outisde 75% entity distance range. 500% render distance set. `enableRendering`: true
![2021-06-12_08 25 14](https://user-images.githubusercontent.com/67918617/121768981-0321b280-cb59-11eb-95d7-57863863bc51.png)
1 block outside 75% entity distance range. 500% render distance set. `enableRendering`: false
![2021-06-12_08 25 27](https://user-images.githubusercontent.com/67918617/121769009-28162580-cb59-11eb-8717-df1336b743b3.png)
1 block **inside** 75% entity distance range. 500% entity distance set. `enableRendeing`: true
![2021-06-12_08 26 03](https://user-images.githubusercontent.com/67918617/121769060-614e9580-cb59-11eb-8429-cda5bbf9c860.png)

**Additional context**
I am running sodium, although im 99% sure this does not play a part in the issue

**Comment by maruohon** [comment]
I uploaded a new version with the fix for this issue.

**Comment by NoComment1105** [comment]
Okay, I'll test soon

**Comment by NoComment1105** [comment]
We good
