### ISSUE TITLE
Ctrl scroll not working

### ISSUE THREAD

**Issue by LegoRaft** [maruohon/litematica#369]
I've recently updated my litematica to 1.17, but my control scroll wheel isn't working, I've already tried moving tweakeroo and minihud out of my mods folder and using a newer litematica version but it still isn't working.

**Comment by maruohon** [comment]
Do you see the "tool HUD" on the bottom left when you hold the tool item?

If not, then the tool isn't active or recognized. Both the main rendering toggle (`M + R`) and tool item toggle (`M + T`) turn it off. Currently in 1.13+ items with NBT data are not recognized. (If you have a server that adds some lore data for example.)

If you see the HUD but just can't scroll to change the mode, then is the `operationModeChangeModifier` hotkey still bound to left control?

**Comment by maruohon** [comment]
Was this solved?
