### ISSUE TITLE
Litematic in blank?

### ISSUE THREAD

**Issue by SrPeterr** [maruohon/litematica#37]
Hello

Well something weird happened, I had this one litematic that I created in single player and then wanted to use on the server, I created it with no problems and could clearly see it on the server.
Went off to create another litematic, no problem creating it. But when I logged back to the server non of my litematics that normally works were working, I created them but it shows as its air, here is a picture: hhttps://i.imgur.com/tIrlHDB.png Yes, there are 2 loaded, but even if there is only 1 its still the same :/

Thanks for your time!

**Comment by maruohon** [comment]
Are you in a layer rendering mode such as Single Layer, or did you toggle off the schematic rendering (M + G by default)?

**Comment by SrPeterr** [comment]
> 
> 
> Are you in a layer rendering mode such as Single Layer, or did you toggle off the schematic rendering (M + G by default)?

Okey I had M + G off, now it works but, it only show me part of the schem, will it load bit by bit?
https://i.imgur.com/h41uNG3.jpg

**Comment by maruohon** [comment]
Does the missing part render if you move closer to it? Or is it simply missing from the schematic? In the current 1.13.2 version the saving is done all at once, which means that the entire area would have to fit into the client's loaded chunks range. If it doesn't, then you would have to save it in smaller pieces.

In the later 1.12 versions the saving was changed to happen in per-chunk pieces, which removes that size limitation and allows saving arbitrarily large areas, you would just have to move around to load all the chunks once, just like the verifier works. So this change will come to the next 1.13.2 version as well, when I have time to finish the remaining things from my TODO list first and then start the next 1.13.2 ports.

**Comment by SrPeterr** [comment]
Nope, it does not render if i go near it :( So I have to do it bit by bit :/
Okey, thanks for your time!

**Comment by maruohon** [comment]
If you created the schematic from single player, then you should be able to just (temporarily) increase your render distance enough so that the entire build fits to the render distance.

**Comment by SrPeterr** [comment]
Okey, its working perfect now, thanks! :)
