### ISSUE TITLE
Translucent Schematic Not Working

### ISSUE THREAD

**Issue by HappyCrafter156** [maruohon/litematica#371]
I am in 1.17, running the newest update, and whenever I click my keybind for toggleTranslucentRendering, it doesn't do anything.

I'm assuming this is a bug, but it's really bothering me.

**Comment by ScorchedPsyche** [comment]
The rendering is basically not working for 1.17 for now. See https://github.com/maruohon/litematica/issues/253#issuecomment-860090344 for more info.

**Comment by maruohon** [comment]
Closing as duplicate of #368
