### ISSUE TITLE
Problems placing a schematic underwater

### ISSUE THREAD

**Issue by KweebecNode** [maruohon/litematica#375]
When I try to put a schematic underwater it does that. I built it on land but i want to build it again in a survival world (and underwater), but it keeps doing that, how I know wich block is wich?
![2021-07-04_11 22 45](https://user-images.githubusercontent.com/86920216/124388807-db86bb80-dcba-11eb-98f1-a87274ee60ad.png)

**Comment by maruohon** [comment]
In the Visuals config category, enable both `ignoreExistingFluids` and `renderCollidingSchematicBlocks` to be able to properly see schematics under water.

**Comment by KweebecNode** [comment]
> In the Visuals config category, enable both `ignoreExistingFluids` and `renderCollidingSchematicBlocks` to be able to properly see schematics under water.

It worked, thanks! :D
