### ISSUE TITLE
Singler Layer Y value automatically sets alone

### ISSUE THREAD

**Issue by lyi26** [maruohon/litematica#380]
When i set the render layers option to singler layer i can see the same layer of my y level, and not the one under my feet. Even while pressing the next layer or previus layer shortcut, the layer i can see doesn't change. Sorry for mt bad english

**Comment by maruohon** [comment]
What does that mean?

**Comment by lyi26** [comment]
> What does that mean?

Sorry my bad, is my first time exposing an issue. I just described the problem, hopefully you can see it.

**Comment by maruohon** [comment]
Do you not even get the message about the layer being changed (above the hotbar)? Did you change those next/previous layer hotkeys? If you are using the 1.16 Forge port, then I noticed that basically none of the hotkey changes take effect properly, unless you log out of the world and back in. If you are not using that version, then which MC version are you on? Are other hotkeys from Litematica working properly?

**Comment by lyi26** [comment]
> Do you not even get the message about the layer being changed (above the hotbar)? Did you change those next/previous layer hotkeys? If you are using the 1.16 Forge port, then I noticed that basically none of the hotkey changes take effect properly, unless you log out of the world and back in. If you are not using that version, then which MC version are you on? Are other hotkeys from Litematica working properly?



> Do you not even get the message about the layer being changed (above the hotbar)? Did you change those next/previous layer hotkeys? If you are using the 1.16 Forge port, then I noticed that basically none of the hotkey changes take effect properly, unless you log out of the world and back in. If you are not using that version, then which MC version are you on? Are other hotkeys from Litematica working properly?

All the other hotkeys perfectly work, and yes, i get the message above the hotbar. When i press the hotkeys to change layer, the next or previous layer appears for a moment, and after it is back to normal. Im using MC 1.17.1 and im not using forge. I installed fabric.

**Comment by maruohon** [comment]
In that case did you enable the `layerModeFollowsPlayer` option in the Generic category? That would always keep moving the layer to the player's y-position.

**Comment by lyi26** [comment]
> In that case did you enable the `layerModeFollowsPlayer` option in the Generic category? That would always keep moving the layer to the player's y-position.

Omg thank you so much, i disabled it and now it works.
