### ISSUE TITLE
Schematica Bug

### ISSUE THREAD

**Issue by DMELNGD** [maruohon/litematica#383]
Hi I'm having this issue Where i put my schematica build map But its not showing on My Load schematica

![2021-07-24 (1)](https://user-images.githubusercontent.com/87886613/126856028-33824558-0ed8-488a-ac43-90b16707036c.png)
![2021-07-24_11 24 03](https://user-images.githubusercontent.com/87886613/126856033-70b2a85b-922c-462c-b3a3-418210f20909.png)

**Comment by maruohon** [comment]
The `*.schem` schematics are in the Sponge schematic format, which is currently only supported in the 1.12.2 version of Litematica. In the 1.13+ versions your would currently need to use World Edit to paste those and then save with Litematica from that pasted version. See #327
