### ISSUE TITLE
MaterialListHudScale bug

### ISSUE THREAD

**Issue by Redostrike** [maruohon/litematica#384]
**Minecraft version**
Which Minecraft version are you playing on?
1.17.1

**Mod version**
litematica-fabric-1.17.1-0.0.0-dev.20210713.103711.jar

**Description of the bug**
Icons and background box are not showing correctly when adjusting "materialListHudScale" to something other than 1.0 in Info Overlays.

**Screenshots**
A picture is better than 1000 words.
![2021-07-25_09 04 32](https://user-images.githubusercontent.com/2196686/126890894-d85db9b4-6673-421f-b538-d84ebc4dd9ee.png)

Additional info:
Voxelmap is on but turning that off does not change it, so they are not interfering with each other.

**Comment by maruohon** [comment]
This should be fixed since the 2021-09-06 release.
