### ISSUE TITLE
Structure not able to paste in creative

### ISSUE THREAD

**Issue by ProkopRandacek** [maruohon/litematica#39]
Structure with 1 M block volume is not able to paste in a creative world. Just says "scheduled task added..." and nothing happens. (version 1.13.2; 0.0.0-dev.20190203.221737)

**Comment by SunSerega** [comment]
You sure you are not pasting air? Give an example structure.

**Comment by jysocial** [comment]
I believe that in the current 1.13.2 build, the entire schematic needs to be loaded at the same time for the paste action to successfully complete. If the schematic extends beyond your render distance then it will not complete and will just say "Scheduled task added".

**Comment by ProkopRandacek** [comment]
Oh just took more than 10 minutes to process :D I'm sorry

**Comment by maruohon** [comment]
Is the server frozen, or does it simply not paste it at all? Are you sure the structure doesn't go below y = 0 or above y = 255 (or outside the world border)? The current build will just silently fail if the schematic goes outside the world bounds, the upcoming version should at least give some meaningful errors.

Also I think the current version has some bugs in how it checks the y bounds. To avoid those issues until the next build (which might come later today actually...), you should set the first corner (red corner) as the lower corner, and also keep the origin point at the same y level as the red/first corner (of the lowest sub-region, if there are multiple).

As to the chunks being loaded... I believe it should just load the entire area in single player while pasting the schematic, as there are no checks for that. I could rewrite the paste to happen in per-chunk pieces, but that would cause any scheduled ticks/running system to get out-of-sync.

**Comment by maruohon** [comment]
Okay 10 minutes is a lot... I have seen it take a rather long time even for smaller schematics, but that is just excessive... I should probably check if I can optimize it, maybe by omitting light calculations at first and running them all at once at the end.

**Comment by ProkopRandacek** [comment]
> Is the server frozen, or does it simply not paste it at all? Are you sure the structure doesn't go below y = 0 or above y = 255 (or outside the world border)? The current build will just silently fail if the schematic goes outside the world bounds, the upcoming version should at least give some meaningful errors.
> 
> Also I think the current version has some bugs in how it checks the y bounds. To avoid those issues until the next build (which might come later today actually...), you should set the first corner (red corner) as the lower corner, and also keep the origin point at the same y level as the red/first corner (of the lowest sub-region, if there are multiple).
> 
> As to the chunks being loaded... I believe it should just load the entire area in single player while pasting the schematic, as there are no checks for that. I could rewrite the paste to happen in per-chunk pieces, but that would cause any scheduled ticks/running system to get out-of-sync.

It was weird because I didn't spot any tps or fps drop while processing so I thought that something is broken.

**Comment by maruohon** [comment]
Well you wouldn't be able to *see* the TPS drop, because the server thread will be literally hung on the pasting code until it finishes. So nothing else would get processed on the server thread, including sending the TPS data via any means. And on the other hand the client thread wouldn't see any difference or be affected until the paste completes.
