### ISSUE TITLE
Minecraft 1.17.1 not starting after downloading litematica mod

### ISSUE THREAD

**Issue by Cavafox** [maruohon/litematica#390]
After installing the mod litematica for 1.17.1 and trying to run it with Fabric Loader and Fabric api the minecraft launcher just crashes. here are some screens: 
![Schermata 2021-08-05 alle 22 17 19](https://user-images.githubusercontent.com/88512187/128416029-127b6f54-61bc-404f-8c0d-3884d1289a43.png)
![Schermata 2021-08-05 alle 22 16 51](https://user-images.githubusercontent.com/88512187/128416037-5f562beb-5781-4f62-89b0-64b3d04873d1.png)

**Comment by maruohon** [comment]
Did you also get the malilib mod? Litematica requires it.

Also that file name kinda suggests you got it from 9minecraft or similar mod repost site? Those sites are basically ripping off modders, and depending on the site they might even add some malware to the files. You should only get Litematica from CurseForge (or from my server, which is linked from the CurseForge description).

**Comment by Cavafox** [comment]
> Did you also get the malilib mod? Litematica requires it.
> 
> 
> 
> Also that file name kinda suggests you got it from 9minecraft or similar mod repost site? Those sites are basically ripping off modders, and depending on the site they might even add some malware to the files. You should only get Litematica from CurseForge (or from my server, which is linked from the CurseForge description).

Ok I'll do it right now. I'll download the mod from forge and then I'll get mailib. Thank you so much! ;)
