### ISSUE TITLE
"renderOverlayThroughBlocks" in "Hotkeys" does not work in Minecraft 1.17.1

### ISSUE THREAD

**Issue by bilichijing** [maruohon/litematica#393]
I used this feature in version 1.16, and all my settings in 1.17.1 are the same as those in 1.16, but it doesn't work when I try to use this feature in 1.17.1.
litematica version:fabric-1.17.1-0.0.0-dev.20210713.103711
![image](https://user-images.githubusercontent.com/88570723/128588469-328ed3c1-5c52-4366-a848-ede27e61c675.png)

**Comment by maruohon** [comment]
This should be fixed since the 2021-09-06 release.
