### ISSUE TITLE
When info hud is enabled, models in inventories have less of a shadow on the right side

### ISSUE THREAD

**Issue by RandomGgames** [maruohon/litematica#395]
**Minecraft version**
1.17.1

**Version Info**
malilib-fabric-1.17.1-0.10.0-dev.24 uploaded to CurseForge Jul 13, 2021
litematica-fabric-1.17.1-0.0.0-dev.20210713.103711 uploaded to CurseForge Jul 13, 2021

**Description of the bug**
When a schematic is loaded, the material list menu is gone to, and the info hud is enabled, all items with 3d models in chests (stone, dirt, beds, etc..) have less of a shadow than usual on their right side.

**Expected behavior** (if not clear from the description)
3d modeled items in chests should not have their darker right side lightened. 

**To Reproduce** (if not clear from the description already)
1. Load schematic
2. Enable material list hud
3. Look at block items in chest/creative items inventory
4. Notice the right side that is dark isn't as dark as usual

**Screenshots**
https://imgur.com/a/WF6Mdkf

**Additional context**
Windows 10 Home
Fabric Loader 0.11.6-1.17.1
RTX 2070 - 3.2.0 Nvidia 471.41
16x Ryzen 7 5800X 8-core

**Comment by maruohon** [comment]
This should be fixed since the 2021-09-06 release.
