### ISSUE TITLE
Minecraft Does Not Start with Litematica Installed.

### ISSUE THREAD

**Issue by Duonic** [maruohon/litematica#397]
**Minecraft version**
1.17.1 (Fabric Loader 0.11.6)

**Mod version and malilib version**
litematica-fabric-1.16.4-0.0.0-dev.20210716.154721
malilib-fabric-1.16.4-0.10.0-dev.21+arne.8

**Description of the bug**
Whenever I start Minecraft, the launcher restarts with an error code and Minecraft doesn't start.

**Screenshots**
![image](https://user-images.githubusercontent.com/88924159/129439068-a15abcc8-5197-4c28-b1ce-5d24b649b205.png)

**Additional context**
I just have Fabric API, Litematica and MiLiLib Installed.

**Comment by ZiiMs** [comment]
you are using litematica and malilib for 1.16.4 

Use these:
![Litematica 1.17.1](https://www.curseforge.com/minecraft/mc-mods/litematica/files/3387062)
![Malilib 1.17.1](https://www.curseforge.com/minecraft/mc-mods/malilib/files/3387061)
