### ISSUE TITLE
Schematic doesn't move all together in placement, looks like it broke apart

### ISSUE THREAD

**Issue by RizRizRizu** [maruohon/litematica#400]
So i download litematica recently because i wantend to do a large build in a server( playing on 1.17.1 ) i converted a schematica to litematica and it renders fine its just when i try to move it only parts of it moves. (see first pic)
![Screenshot (1)](https://user-images.githubusercontent.com/89339543/130352288-2411f9a8-608e-41e0-b834-da6ee7b19dfb.png)

and when i unload it to start over it doesn't change, when i load it again somewhere in the same area it renders with some bits of the last one glitching in.
![Screenshot (2)](https://user-images.githubusercontent.com/89339543/130352397-e4a101ad-fda6-4610-bfa1-54d93c8b90fb.png)

With a small build it works fine i only seem to have trouble with this large one.
both Litematica, MaLiLib are 1.17.1

**Comment by Narnianknight** [comment]
A temporary solution is turning rendering off and on again any time it happens.

**Comment by maruohon** [comment]
This should be fixed since the 2021-09-06 release.
