### ISSUE TITLE
1.14.2 build

### ISSUE THREAD

**Issue by ardentcrest** [maruohon/litematica#41]
Getting this error

> FAILURE: Build failed with an exception.

* Where:
Build file 'E:\New folder\litematica-fabric_1.14.2\build.gradle' line: 2

* What went wrong:
Plugin [id: 'fabric-loom', version: '0.2.3-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/4.9/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (snapshot plugin versions are not supported)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

>

**Comment by maruohon** [comment]
I fixed/updated the build scripts, the builds now work. There are now also builds here: https://pena2.dy.fi/tmp/minecraft/mods/client_mods/ (no compatible Tweakeroo for the new malilib yet... tons of Mixins to port still >_>)
