### ISSUE TITLE
pasting huge schemas crashes mc

### ISSUE THREAD

**Issue by end-user** [maruohon/litematica#412]
I have a huge schema (500x500x200) that I'm trying to paste into a single player world.  After about 5 minutes, the game just gives up and crashes.  Is there a way to do it in stages?  Or break up the schema externally?

MC 1.17.1
litematica-fabric-1.17.1-0.0.0-dev.20210713.103711
malilib-fabric-1.17.1-0.10.0-dev.24

**Comment by maruohon** [comment]
Try the latest version (`2021-09-06`), I changed the paste task to work in per-chunk pieces in that version.

**Comment by end-user** [comment]
Yeah, it works great now!  Should have checked for an updated version first.
