### ISSUE TITLE
Skyblock

### ISSUE THREAD

**Issue by BadSpikeMC** [maruohon/litematica#415]
**Is your feature request related to a problem? Please describe.**
In hypixel skyblock, i want to build something on my island but i cant use the mod because the stick used to move the schematic is not a vanilla stick its a skyblock stick with the common tag
**Describe the solution you'd like**
can you add support for the skyblock stick
**Describe alternatives you've considered**

**Additional context**

**Comment by maruohon** [comment]
You can use whatever item you want as the tool, including an empty hand, by using the `toolItem` config in the Generic category. And then just toggle on/off the tool functionality for the item (by default with `M + T`) when needed. And you don't even *need* the tool for anything in survival mode, although it can make nudging the placement more convenient
