### ISSUE TITLE
Conflicts with worldshell

### ISSUE THREAD

**Issue by supersaiyansubtlety** [maruohon/litematica#418]
**Minecraft version**
1.17.1

**Mod version and malilib version**
  - litematica-fabric-1.17.1-0.0.0-dev.20210906.183617
  - malilib-fabric-1.17.1-0.10.0-dev.25
  - fabric-api-0.40.1+1.17
  - worldshell-0.1.2-rayon-fix

**Description of the bug**
When installed alongside [worldshell](https://github.com/Snakefangox/worldshell/issues/3), loading into a world and looking around a tiny bit causes a crash. 

---

**Additional context**
the version of worldshell I'm using can be downloaded from [here](https://github.com/Sorenon/worldshell/releases/tag/v0.1.2-rayon-fix)

[latest.log](https://paste.myst.rs/qvdmdwpr)

**Comment by maruohon** [comment]
Try if this build works: https://masa.dy.fi/mcmods/litematica/litematica-fabric-1.17.1-0.0.0-dev.20210916.035741.jar

**Comment by supersaiyansubtlety** [comment]
That fixes it, thanks!
