### ISSUE TITLE
Block Render Error

### ISSUE THREAD

**Issue by fumiondesu** [maruohon/litematica#428]
Hello,

Recently, i've met this bug
when i use litematica, the placed block color should be back to normal, but instead of that, the color is still the same as the schematic blocks until i reload my chunk using F3 + A
how do i fix this? it's difficult to build in the day since i dont know what block have i placed until i reload my chunk and it's making the progress slowly
sorry for my bad english, any help would be appreciated!

**Comment by shiraoowa** [comment]
> You didn't really provide any information such as the mod version you are using. There was a bug like this in 1.17.1, if you also had a recent version of Lithium (0.7.4+) installed. It was fixed in the 2021-09-06 version of Litematica. Make sure you have that version of later, if you are on 1.17.1.

thank you, i fixed it by reinstalling the mods. maybe because i used the older version without notice since my friends gave me.
