### ISSUE TITLE
failed to load chinese-named .litematic file

### ISSUE THREAD

**Issue by bAdOoWindy** [maruohon/litematica#430]
**Minecraft version**
.1.17.1

**Mod version and malilib version**
litematica-fabric-1.17.1-0.0.0-dev.20210927.173826
malilib-fabric-1.17.1-0.10.0-dev.25
fabric-loader-0.11.7-1.17.1
[1.17.1] Fabric API 0.41.0
Java i'm using Minecraft Launcher included

**Description of the bug**
in main world load chinese-named .litematic file is ok
after "Save & Quit to Title"
load world again file name is  garbled code 
and show red text
Failed to read schematic from file '.minecraft\schematics\"garbled code".litematic'

![tmp](https://user-images.githubusercontent.com/4119845/138119330-3b2fd1a0-d295-4043-bc2d-49d60ac31f04.jpg)

**Comment by maruohon** [comment]
What do you see in the Load Schematics menu? Is the name there still correct? What is your system locale/character set set to?

The file name I see in the zip, and what I get when I extract it is already broken.
But if I just make a copy of the file and then rename it to the name shown in your previous message, then I basically have these two test schematics:
![image](https://user-images.githubusercontent.com/2331050/138252850-4da6253a-7987-4aad-9b8d-a347b947e0d0.png)

If I have the system locale (I'm on Linux) LC_ALL and LANG set to `en_GB.UTF-8`, then I see the file names like this, where the second file is the one where I copy pasted the name from the above message:
![image](https://user-images.githubusercontent.com/2331050/138254275-a4795df9-413e-4ae4-bc57-2c3debcaac03.png)

When I then log out of the world, then the placement config file has this (and both schematics are loaded successfully when I log back in):
![image](https://user-images.githubusercontent.com/2331050/138254445-a6acbabb-49d1-4fd9-aa1e-385b8f7d282e.png)


But if I launch the game with the LC_ALL and LANG environment variables set to `en_US.ISO-8859-1`, then I see this:
![image](https://user-images.githubusercontent.com/2331050/138253077-c81cd0bc-bebf-4c67-a3de-d3d25fc3b5ec.png)

And the placement config looks like this (if interpreted as UTF-8 in the text editor):
![image](https://user-images.githubusercontent.com/2331050/138253374-427476a6-c7e0-43f2-b2c6-0b60635c242b.png)

However with both locales, the placements are persistent and loaded successfully, as long as the same system locale was used when saving and loading the config file. So I would need to know at what stage does it get corrupted. Also, if you use area selection names with these characters, do those break when you restart the game, or does it store that correctly?

**Comment by bAdOoWindy** [comment]
What do you see in the Load Schematics menu? 
file name is correct 
Is the name there still correct? 
yes and can correct load
What is your system locale/character set set to?
windows 10 X64 region setting not enable UTF-8
Also, if you use area selection names with these characters, do those break when you restart the game, or does it store that correctly?
 it store correct
Schematics load well
area selection names correct

i load Schematics in main world 
it break when
1."save and quit to title" and back to same save , it breaks with garbled code filename
2.load Schematics in main world and leave main world back to main world break again with garbled code filename
PS:leave main world like goto "The End"
i'm trying enable UTF-8 in region setting

**Comment by bAdOoWindy** [comment]
i emptied .minecraft/config/litematica/ and load schematic. 

there is two .json file
litematica_fe80__e5bb_c30e_3f03_9b47_dim_minecraft_the_nether.json

![图片](https://user-images.githubusercontent.com/4119845/138376417-7c406959-e8a4-4570-8b9d-8b191e1110a1.png)
notepad++ down right says is utf-8,and there is no file name at all

litematica_fe80__e5bb_c30e_3f03_9b47.json
![图片](https://user-images.githubusercontent.com/4119845/138376533-42fc9b7f-623d-4b4c-a3df-55a3b222a613.png)

but i load schematic in the over world but night!

**Comment by maruohon** [comment]
So it seems like it's written to the file correctly, but then probably read from there wrong.

Try if using this malilib version fixes it or changes anything. It forces the config files to always also be read using UTF-8 encoding, instead of the system default charset or whatever it used before.
https://masa.dy.fi/mcmods/malilib/malilib-fabric-1.17.1-0.10.0-dev.26+pre.1.jar
