### ISSUE TITLE
How do you override an existing schematic [Question / Bug] 

### ISSUE THREAD

**Issue by ErrorBot1122** [maruohon/litematica#440]
Discussion Question: https://github.com/maruohon/litematica/discussions/439

I want to override my schematic because i made a mistake when saving it, but it keeps giving me this error:

![image](https://user-images.githubusercontent.com/65428515/139593242-d2431e55-10d1-42c4-ac85-70bdbb17ac20.png)

I'm not sure if it's a bug or not...

**Comment by maruohon** [comment]
You can override existing files by holding shift when you click on the Save Schematic button. The hover tooltip on the button also tells you this.
