### ISSUE TITLE
schematicRebuildReplaceAll not working + 6 modes are missing

### ISSUE THREAD

**Issue by ausberg** [maruohon/litematica#446]
I am on the beta 1.16.5 forge version found [here](https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/unsupported_temporary_forge_1.16.5/).

[This guide](https://github.com/maruohon/litematica/wiki/schematic_editing) did not work for me. Setting a keybind, switching to rebuild mode, holding the key and right-clicking with the block on the schematic does nothing. I've been messing around with it trying different combos of key pressing but nothing works.

As an aside, and maybe I should make a separate issue for this, I only have 3 of the 9 modes available when I cycle through them-- 1/9 Area Selection, 2/9 Schematic Placement, and 9/9 Rebuild Schematic. I don't see an option to choose the other modes. I know paste mode is 5/9 but it doesn't exist for me.

Is all of this just an issue with the beta 1.16.5 forge version? I haven't yet tried any of the other versions available.

**Comment by maruohon** [comment]
The main issue with those Forge versions (it's an issue in the malilib version) is that you need to log out of the world and back in for any hotkey config changes to take effect. So if you just bound the rebuild hotkey now, then it probably didn't take effect if you haven't logged out and back in yet. You will get a colored overlay when you hold that key in the Rebuild/Edit mode.

As for the 3 modes available, those are he only ones useful/usable in survival mode. The other modes are creative-mode-only, so you can also only switch to them while in creative mode, to reduce the clutter of useless modes while in survival.

**Comment by ausberg** [comment]
> The main issue with those Forge versions (it's an issue in the malilib version) is that you need to log out of the world and back in for any hotkey config changes to take effect.

Ah, that is very good to know. After relaunching the game (I know you just said re-login to world but I misread it) the hotkey now works.

> As for the 3 modes available, those are he only ones useful/usable in survival mode. The other modes are creative-mode-only, so you can also only switch to them while in creative mode, to reduce the clutter of useless modes while in survival.

Understandable. Glad it's not a bug but just a feature.

Thanks for the quick response!
