### ISSUE TITLE
Settings reset every time I launch MC

### ISSUE THREAD

**Issue by Owsleyyyy** [maruohon/litematica#447]
Hi, every time that i close my minecraft, my Litematica settings are reset (and only that mod)

**Comment by maruohon** [comment]
Check the config file at `.minecraft/config/litematica.json`. Is there maybe a permission issue with the file or the config directory? Does the config file even exist? If it does, and if you delete the file, does it get re-created properly? What settings reset, absolutely everything from the config menus? Your hard drive isn't completely full by chance?

**Comment by Owsleyyyy** [comment]
Ok so, I don't think that is a permission problem, yes the config file exist, but I've check and it's the normal settings that's in (not my setting), and yes it's everythings wich is reset, and no my hard drive isn't full. So i'm gonna try to delete the config file then restart my minecraft, thank for the help (and sorry if my english is bad, i'm french)

**Comment by Owsleyyyy** [comment]
Ok so i deleted the file and launch my game, the file get re created
Then i change my setting, close and re launch my game and the setting didn't get reset
So thank you for your help !

**Comment by Owsleyyyy** [comment]
a
