### ISSUE TITLE
After starting the game, the client will flash back directly

### ISSUE THREAD

**Issue by monsters-97** [maruohon/litematica#451]
game version 1.17.1

Module version:
malilib-fabric-1.17.1-0.10.0-dev.26
litematica-fabric-1.17.1-0.0.0-dev.20210906.183617.jar     Uploaded on September 6

After I start the game, before the mojang interface appears on the client, the client will flash back directly. In my logs, it suddenly stops after the lastest sentence, which is texture minecraft: block / sculk_ sensor_ tendril_ active with size 8x8 limits mip level from 4 to 3.

If I use the mod uploaded on July 13, everything is normal. However, the mod uploaded on July 13 will cause the problem that the schematic rendering cannot be moved. It makes me feel very painful.

**Comment by monsters-97** [comment]
This problem still occurs when I use the latest version uploaded on October 25. 

The version of lithium when starting the game is 0.7.4 or 0.7.5,

**Comment by maruohon** [comment]
Does this happen without other mods, or is it a conflict with some other mod? How much RAM do you have allocated for the game?

**Comment by monsters-97** [comment]
I think I found the problem. Because the old version of litematica can work normally, I ignore the direction of module incompatibility. Thank you for reminding me. In my test, litematica mod uploaded after September 6 is incompatible with masagadget ( version 1.1.6 ) . When I updated masagadget to version 2.0.6, the game worked normally.
