### ISSUE TITLE
Litematica for 1.18

### ISSUE THREAD

**Issue by Seeloewen** [maruohon/litematica#452]
**Is your feature request related to a problem? Please describe.**
Litematica is not yet compatible with 1.18

**Describe the solution you'd like**
Make Litematica compatible with 1.18

**Describe alternatives you've considered**
Update it to 1.18 please.

**Additional context**
/

**Comment by surfrock66** [comment]
Litematica depends on maliLib which doesn't even have an active branch for 1.18 yet.

https://github.com/maruohon/malilib/branches

**Comment by Seeloewen** [comment]
Thank you, I really hope it will get updated soon.

**Comment by StickNitro** [comment]
Looks like Malilib has updated, according to this - https://www.curseforge.com/minecraft/mc-mods/malilib/files/3544210

**Comment by DragonEggBedrockBreaking** [comment]
> Looks like Malilib has updated, according to this - https://www.curseforge.com/minecraft/mc-mods/malilib/files/3544210

There is already a fork for 1.18 litematica btw, so someone has already done the heavy lifting

**Comment by Seeloewen** [comment]
> There is already a fork for 1.18 litematica btw, so someone has already done the heavy lifting

What is the link to the fork?

**Comment by kosma** [comment]
If you really, really, really can't wait: http://github.com/vacla - not complete but good enough for basic use.
(these are obviously not supported, build and use at your own risk)

**Comment by DerOrginaleCookie** [comment]
Hey there is already a Litematica version for 1.18 because my game always crashes with the latest version that is online at Curse Forge

**Comment by kosma** [comment]
Litematica 1.18: https://masa.dy.fi/mcmods/client_mods/?mcver=1.18.0
