### ISSUE TITLE
When removing an area selection from litematica menu, the selection box remains in-game (1.18)

### ISSUE THREAD

**Issue by Nomenator** [maruohon/litematica#455]
Just like says. You can still manipulate the area selection box in-game when no area selections remain.

**Comment by maruohon** [comment]
I assume you are in the `Simple` area selection mode and not `Normal`? The Area Selection Browser is only used for the `Normal` mode selections, the `Simple` mode has its own "global" selection. If you don't want to see the selection box, either switch to the `Normal` mode (without a selection active in the browser) in the Litematica main menu (middle left), or just turn off the area selection rendering (in Visuals or with a hotkey you can set).
