### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by S3ndo** [maruohon/litematica#46]
Any ideas what i did wrong? rift work fine without litematica and malilib
Here is the log https://paste.ee/p/ItJTe

**Comment by vacla** [comment]
you need to updated malilib version 0.10.0, this can be found in file as a beta version.

**Comment by S3ndo** [comment]
> you need to updated malilib version 0.10.0, this can be found in files as a beta version.
TY very much!! I was blind when i was downloading malilib
