### ISSUE TITLE
Not loading right and floating things

### ISSUE THREAD

**Issue by Sildss** [maruohon/litematica#469]
![2021-12-27_18 28 26](https://user-images.githubusercontent.com/96742328/147494357-d520a8d6-a44b-4e24-a373-14d382ae2ec1.png)

I tried to load my a raid farm and it just bugged out and flying i weird places. I don't know why, i've restarted my game, doesn't work, deleting the mods and re dowloading them agian but it just doesn't work.

**Comment by maruohon** [comment]
I assume you found out that it's Optifine and/or shaders doing stuff? Also disabling Render Regions in Optifine might help.

**Comment by Sildss** [comment]
Thank you so much
