### ISSUE TITLE
Mod is on sum here...

### ISSUE THREAD

**Issue by Eggbruv** [maruohon/litematica#470]
alright i got myself a bug here ya know

playin on 1.18.1 fabric

playing on the latest version of litmatica 
 (litematica-fabric-1.18.0-0.9.0)

now for a description of this issue.. well lets just say the game is on drugs. Ill prove a video here in the form of a link.

https://youtu.be/zwVqglHdY7Q      <------------------------------------------------------ link

all im doin opening the menu, clicking on one of my schematics, then clicking load and the game goes YEYAOOARMMMMMM

**Comment by maruohon** [comment]
Well, haven't seen exactly that before. But first guess is try disabling shaders and re-logging to the world. If that doesn't help and you are using Optifine, then try disabling Optifine.

**Comment by Eggbruv** [comment]
yea it turning off my shaders fixed it, thanks for the help and good luck with making ur mod here lol.
