### ISSUE TITLE
everytime i press the execute it does not build it  im using fabric 1.17.1

### ISSUE THREAD

**Issue by essa47337** [maruohon/litematica#473]
I got i issue everytime i execute I does not build it and I'm using 1.17.1 fabric
anyone having same as mine

**Comment by BartTerpstra1** [comment]
please add the following details:
* full version of litematica used.
* key you bound "execute operation" to
* what operation you are trying to execute
* single player or multiplayer?
* what is your game mode?

**Comment by essa47337** [comment]
thanks for the replay and i use version litematica-fabric-1.17.1-0.0.0-dev.20210707.011234.jar
and the key bound is 0
grand hotel creation #270 
single player 
creative

**Comment by essa47337** [comment]
> please add the following details:
> 
> * full version of litematica used. version litematica-fabric-1.17.1-0.0.0-dev.20210707.011234.jar
> * key you bound "execute operation" to key bound is 0
> * what operation you are trying to execute grand hotel creation #270
> * single player or multiplayer? single player
> * what is your game mode? creative

**Comment by BartTerpstra1** [comment]
update to latest version and see if the issue persists.
seems to be 0.9.0 at time of writing.

**Comment by essa47337** [comment]
> update to latest version and see if the issue persists. seems to be 0.9.0 at time of writing.

now the game crashes

**Comment by BartTerpstra1** [comment]
did you update mailib and any other Masa mods to their latest 1.17.1 versions as well?

**Comment by essa47337** [comment]
> did you update mailib and any other Masa mods to their latest 1.17.1 versions as well?

yes I did

**Comment by BartTerpstra1** [comment]
this is now a different issue.
could you join the discord? 
https://masa.dy.fi/discord
then we can close this issue as won't fix.

**Comment by essa47337** [comment]
okie dokey

> this is now a different issue. could you join the discord? https://masa.dy.fi/discord then we can close this issue as won't fix.
