### ISSUE TITLE
Litematica ot loading

### ISSUE THREAD

**Issue by oShadowMinecraft** [maruohon/litematica#476]
Hi there! I am trying to make a litematic of a build I'm proud of in my world, and when I tried to install fabric and litematica the game crashed and had an exit code 0. I don't know what this means, maybe you will. after the crash, Minecraft will boot up fine, but whenever I press m or hold a stick there is no interface or any sign that there is a mod loaded. Like it is vanilla Minecraft. I have followed online tutorials and looked through every post I can find about this issue. not thing seems to work. I have re-installed fabric many times and still... nothing.

if it helps, 

I use forge and have set up some things in my computer to run forge
I am using fabric API and malilib library
I am playing in 1.18.1 and I am going to take the litematic from something in Hypixel SMP
![image](https://user-images.githubusercontent.com/97486746/148861602-7b5de1f3-8610-4531-82ad-a2a2141d3029.png)
![image](https://user-images.githubusercontent.com/97486746/148861671-552608d8-24a9-4e4d-abf6-23ff20f588af.png)
![image](https://user-images.githubusercontent.com/97486746/148861716-78051990-4826-45ad-8274-83cda25f72a8.png)

Thanks, Shadow

**Comment by maruohon** [comment]
I would need to see the actual crash log, which should be either in `.minecraft/crash-reports/`, or maybe just the log file at `.minecraft/logs/latest.log`. At first look everything seems fine, the mods are for 1.18 and you are using a 1.18.1 profile with the latest Fabric loader. How much memory do you have allocated for the game? You usually need at least 2 GB with Litematica installed.

**Comment by oShadowMinecraft** [comment]
.minecraft/logs/latest.log

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  FMLLoadingPlugin (ModCore_Container-1.0.jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  FMLLoadingPlugin (Levelhead-7.2 (1.8.9).jar)
  Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  TNTTimerTweaker (TNT Time-1.0 (1.8.9).jar)
  CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  FMLLoadingPlugin (AutoGL-1.0 (1.8.9).jar)
  PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  FMLLoadingPlugin (OofMod-3.0 (1.8.9).jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.5-for-MC-1.8.9.jar)
  LabyModCoreMod (LabyMod-3.jar)
  Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  BossbarTweaker (Bossbar Customizer-1.2 (1.8.9).jar)
  PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
  ModTweaker (Patcher-1.5.1 (1.8.9).jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 3/25/21 3:32 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.entity.RendererLivingEntity.field_77045_g from class net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom
	at net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom.<init>(LayerMooshroomMushroom.java:36)
	at net.minecraft.client.renderer.entity.RenderMooshroom.<init>(SourceFile:14)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:153)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.layers.LayerMooshroomMushroom.<init>(LayerMooshroomMushroom.java:36)
	at net.minecraft.client.renderer.entity.RenderMooshroom.<init>(SourceFile:14)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:153)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:481)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1061871272 bytes (1012 MB) / 1509949440 bytes (1440 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCH	perspectivemod{3.0} [Perspective Mod 3.0] (minecraft.jar) 
	UCH	oldanimations{2.4.2} [OldAnimationsMod] (minecraft.jar) 
	UCH	refractionoof{3.0} [Oof Mod] (minecraft.jar) 
	UCH	PlayerAPI{1.0} [Player API] (minecraft.jar) 
	UCH	smoothfontcore{1.8.9-1.15.1} [Smooth Font Core] (minecraft.jar) 
	UCH	level_head{7.2} [Sk1er Level Head] (minecraft.jar) 
	UCH	smoothfont{1.8.9-1.15.2} [Smooth Font] (SmoothFont-1.8.9-1.15.2.jar) 
	UCH	autotip{3.0.1} [Autotip] (Autotip-3.0.1 [1.8-1.12.2].jar) 
	UCH	modcore{0.1.47} [ModCore] (Sk1er Modcore-0.1.47 (1.8.9).jar) 
	UCH	pownspotionhud{1.0} [pownspotionhud] (1.8.9_Powns_PotionEffect_HUD_-_1.0.jar) 
	UCH	blockoverlay{2.1} [BlockOverlay] ([1.8.9] BlockOverlay-v2.1.jar) 
	UCH	Powns ArmorStatus HUD{1.0} [powns-armorhud] ([1.8.9] Powns ArmorStatus HUD - 1.1.jar) 
	UCH	pownscoordshud{1.0} [Powns' Coords HUD] ([1.8.9] Powns Coords HUD - 1.0.jar) 
	UCH	pownstogglesneak{3.0} [pownstogglesneak] ([1.8.9] Powns ToggleSneak - 3.0.jar) 
	UCH	sidebarmod{2.0} [Sidebar Mod Revamp] ([1.8.9] Sidebar Mod Revamp.jar) 
	UCH	particlemod{1.02} [Particle Mod] ([1.8.9]ParticleMod-1.02.jar) 
	UCH	alwayssharp{1.0} [AlwaysSharp] (alwayssharp-1.0.jar) 
	UCH	autogg{4.0.3} [AutoGG] (AutoGG-4.0.3 (1.8.9).jar) 
	UCH	autogl{1.0} [AutoGL] (AutoGL-1.0 (1.8.9).jar) 
	UCH	AutoWho{1.0} [AutoWho] (AutoWho-1.0.jar) 
	UCH	bossbar_customizer{1.2} [BossbarCustomizer] (Bossbar Customizer-1.2 (1.8.9).jar) 
	UCH	customcrosshairmod{0.5.1-Forge} [Custom Crosshair Mod] (crosshairmod-v0.5.1-forge-mc1.8.9.jar) 
	UCH	keystrokesmod{8.0.2} [KeystrokesMod] (Keystrokes-8.0.2 (1.8.9).jar) 
	UCH	labymod{3.7.7} [LabyMod] (LabyMod-3.jar) 
	UCH	modcore_example_mod{1.0} [ModCore Container Mod] (ModCore_Container-1.0.jar) 
	UCH	notenoughupdates{1.7.3-REL} [NotEnoughUpdates] (NotEnoughUpdates-1.7.3-RELjar.jar) 
	UCH	patcher{1.5.1} [Patcher] (Patcher-1.5.1 (1.8.9).jar) 
	UCH	text_overflow_scroll{1.3} [Scrollable Tooltips] (Scrollable Tooltips-1.3 (1.8.9).jar) 
	UCH	hypixel_auto_complete{1.0} [Hypixel Autocomplete Mod] (Sk1er Hypixel Autocomplete Mod-1.0.jar) 
	UCH	skyblockaddons{1.5.5} [SkyBlock Addons] (SkyblockAddons-1.5.5-for-MC-1.8.9.jar) 
	UCH	SkyblockExtras{2.0.4} [SkyblockExtras] (SkyblockExtras-2.0.4.jar) 
	UCH	timechanger{1.0} [TimeChanger] (TimeChanger-1.0 (1.8.9).jar) 
	UCH	tnttime{1.0} [TNT Time] (TNT Time-1.0 (1.8.9).jar) 
	Loaded coremods (and transformers): 
FMLLoadingPlugin (AutoGG-4.0.3 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
FMLLoadingPlugin (ModCore_Container-1.0.jar)
  
FMLLoadingPlugin (Scrollable Tooltips-1.3 (1.8.9).jar)
  club.sk1er.mods.overflowscroll.forge.ClassTransformer
FMLLoadingPlugin (Levelhead-7.2 (1.8.9).jar)
  club.sk1er.mods.levelhead.forge.transform.ClassTransformer
Perspective Mod ([1.8.9] Perspective Mod-3.0.jar)
  net.canelex.perspectivemod.asm.CameraTransformer
TNTTimerTweaker (TNT Time-1.0 (1.8.9).jar)
  club.sk1er.mods.tnttimer.tweaker.ClassTransformer
CorePlugin (SmoothFont-1.8.9-1.15.2.jar)
  bre.smoothfont.asm.Transformer
FMLLoadingPlugin (AutoGL-1.0 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
PatcherTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.patcher.tweaker.ClassTransformer
FMLLoadingPlugin (OofMod-3.0 (1.8.9).jar)
  us.nickfraction.oofmod.asm.EntityPlayerTransformer
  us.nickfraction.oofmod.asm.EntityArrowTransformer
  us.nickfraction.oofmod.asm.EntityFishHookTransformer
  us.nickfraction.oofmod.asm.RenderGlobalTransformer
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.5.5-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.tweaker.SkyblockAddonsTransformer
LabyModCoreMod (LabyMod-3.jar)
  net.labymod.core.asm.LabyModTransformer
Main (OldAnimationsMod v2.4.2 FORGE MC1.8.9.jar)
  com.spiderfrog.main.ClassTransformer
BossbarTweaker (Bossbar Customizer-1.2 (1.8.9).jar)
  club.sk1er.mods.core.forge.ClassTransformer
  club.sk1er.bossbarcustomizer.tweaker.ClassTransformer
PlayerAPIPlugin (PlayerAPI-1.8.9-1.0.jar)
  api.player.forge.PlayerAPITransformer
FMLLoadingPlugin (Keystrokes-8.0.2 (1.8.9).jar)
  
ModTweaker (Patcher-1.5.1 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.23' Renderer: 'GeForce GTX 1660 Ti/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.2318-1.8.9
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.23, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Shadow's Pack
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 24
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.23
	OpenGlRenderer: GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

Thanks!

**Comment by maruohon** [comment]
That log is from last March from 1.8.9. Look for a log that is actually from the current session.

**Comment by maruohon** [comment]
Also how do you actually have your game directory set up in the launcher profile? You have directories inside your `mods/` directory that normally should not be there... What is the actual game directory and active mod directory?

**Comment by oShadowMinecraft** [comment]
oop! sorry here is the current one (I think) (I'm dumb so I think I got it right this time)

also, this if it helps https://youtu.be/cWvPiGQxiV4

---- Minecraft Crash Report ----
// Oops.

Time: 12/11/21, 8:37 PM
Description: Unexpected error

java.lang.NoSuchFieldError: b
	at net.optifine.shaders.ShadowFrustum.extendForShadows(ShadowFrustum.java:67)
	at net.optifine.shaders.ShadowFrustum.<init>(ShadowFrustum.java:19)
	at net.optifine.shaders.ShadersRender.makeShadowFrustum(ShadersRender.java:743)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:401)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4964)
	at net.minecraft.v1_18.phsaaphsepsshhahhhasppaee.ashseaeshhsehpahaspsahsas(GameRenderer.java:1467)
	at net.minecraft.v1_18.phsaaphsepsshhahhhasppaee.ahsphhhhsehahpesppspahhes(GameRenderer.java:1155)
	at net.minecraft.v1_18.apsaspeeshehsehppapespsss.paehasspsepaaaaahhhssepee(SourceFile:1117)
	at net.minecraft.v1_18.apsaspeeshehsehppapespsss.hehesepapspsapapeheappsaa(SourceFile:733)
	at net.minecraft.client.main.Main.main(SourceFile:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.patcher.LunarMain.main(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.shaders.ShadowFrustum.extendForShadows(ShadowFrustum.java:67)
	at net.optifine.shaders.ShadowFrustum.<init>(ShadowFrustum.java:19)
	at net.optifine.shaders.ShadersRender.makeShadowFrustum(ShadersRender.java:743)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:401)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4964)
	at net.minecraft.v1_18.phsaaphsepsshhahhhasppaee.ashseaeshhsehpahaspsahsas(GameRenderer.java:1467)

-- Affected level --
Details:
	All players: 39 total; [psspeahssaaaeaphephpheepp['_oShadow'/133677, l='ClientLevel', x=41.50, y=87.50, z=22.50], hhhppppeeeseeshshshsppsep['Slivoxx'/133562, l='ClientLevel', x=39.63, y=86.00, z=24.72], hhhppppeeeseeshshshsppsep['Saruto0017'/133658, l='ClientLevel', x=41.50, y=86.00, z=22.50], hhhppppeeeseeshshshsppsep['56fczu77ga'/105, l='ClientLevel', x=37.50, y=86.00, z=19.50], hhhppppeeeseeshshshsppsep['v6c0sn066m'/127, l='ClientLevel', x=40.50, y=86.00, z=16.50], hhhppppeeeseeshshshsppsep['i6cp727yuw'/278, l='ClientLevel', x=37.50, y=86.00, z=25.50], hhhppppeeeseeshshshsppsep['99086u5513'/260, l='ClientLevel', x=24.50, y=81.00, z=34.50], hhhppppeeeseeshshshsppsep['y00lctyj4n'/85, l='ClientLevel', x=16.50, y=80.00, z=34.50], hhhppppeeeseeshshshsppsep['RazeRain18'/133648, l='ClientLevel', x=19.13, y=79.00, z=22.66], hhhppppeeeseeshshshsppsep['1e7560ny80'/82141, l='ClientLevel', x=24.50, y=81.00, z=10.50], hhhppppeeeseeshshshsppsep['7n0yuo729i'/95, l='ClientLevel', x=16.50, y=80.00, z=10.50], hhhppppeeeseeshshshsppsep['4r38z0s2zy'/100, l='ClientLevel', x=43.50, y=88.00, z=-0.50], hhhppppeeeseeshshshsppsep['8ztn86a8qn'/18, l='ClientLevel', x=11.50, y=80.00, z=33.50], hhhppppeeeseeshshshsppsep['rdcnv48757'/70, l='ClientLevel', x=9.50, y=80.00, z=32.50], hhhppppeeeseeshshshsppsep['7hun02et96'/108, l='ClientLevel', x=13.50, y=80.00, z=34.50], hhhppppeeeseeshshshsppsep['kff4ro3zcz'/1, l='ClientLevel', x=10.50, y=80.00, z=25.50], hhhppppeeeseeshshshsppsep['eg52hkv12q'/7, l='ClientLevel', x=11.50, y=80.00, z=22.50], hhhppppeeeseeshshshsppsep['vk47q99zfm'/13, l='ClientLevel', x=5.50, y=81.00, z=22.50], hhhppppeeeseeshshshsppsep['4z7825xilz'/24, l='ClientLevel', x=10.50, y=80.00, z=19.50], hhhppppeeeseeshshshsppsep['2524e2ebn7'/29, l='ClientLevel', x=5.50, y=81.00, z=24.50], hhhppppeeeseeshshshsppsep['9c8g0g280y'/34, l='ClientLevel', x=5.50, y=81.00, z=20.50], hhhppppeeeseeshshshsppsep['98cf951513'/39, l='ClientLevel', x=6.50, y=81.00, z=26.50], hhhppppeeeseeshshshsppsep['287k4q17ut'/44, l='ClientLevel', x=6.50, y=81.00, z=18.50], hhhppppeeeseeshshshsppsep['bosp8g8pbd'/50, l='ClientLevel', x=6.50, y=81.00, z=28.50], hhhppppeeeseeshshshsppsep['28tbr007a4'/55, l='ClientLevel', x=7.50, y=80.00, z=30.50], hhhppppeeeseeshshshsppsep['e9ce8m432g'/60, l='ClientLevel', x=6.50, y=81.00, z=16.50], hhhppppeeeseeshshshsppsep['74kw8bv889'/113, l='ClientLevel', x=12.50, y=79.00, z=29.50], hhhppppeeeseeshshshsppsep['Explorer3927'/133457, l='ClientLevel', x=14.75, y=79.00, z=11.53], hhhppppeeeseeshshshsppsep['e797a519s9'/65, l='ClientLevel', x=7.50, y=80.00, z=14.50], hhhppppeeeseeshshshsppsep['xen118eo4u'/75, l='ClientLevel', x=9.50, y=80.00, z=12.50], hhhppppeeeseeshshshsppsep['v6v2r9xo8m'/80, l='ClientLevel', x=11.50, y=80.00, z=11.50], hhhppppeeeseeshshshsppsep['g247w994pr'/90, l='ClientLevel', x=13.50, y=80.00, z=10.50], hhhppppeeeseeshshshsppsep['77o02dto65'/119, l='ClientLevel', x=12.50, y=79.00, z=15.50], hhhppppeeeseeshshshsppsep['mbjuyy9971'/264, l='ClientLevel', x=18.50, y=79.00, z=-7.50], hhhppppeeeseeshshshsppsep['FrogPixel'/131253, l='ClientLevel', x=63.00, y=86.00, z=-7.88], hhhppppeeeseeshshshsppsep['oqk16c3ns8'/124, l='ClientLevel', x=76.50, y=71.00, z=66.50], hhhppppeeeseeshshshsppsep['OnlyFools'/133625, l='ClientLevel', x=52.31, y=81.34, z=77.53], hhhppppeeeseeshshshsppsep['6y80ku2u1u'/213, l='ClientLevel', x=8.00, y=79.00, z=-24.50], hhhppppeeeseeshshshsppsep['YO2A'/133685, l='ClientLevel', x=41.50, y=87.50, z=22.50]]
	Chunk stats: 5041, 115
	Level dimension: minecraft:overworld
	Level spawn location: World: (41,87,22), Section: (at 9,7,6 in 2,5,1; chunk contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 74607869 game time, 37000 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.v1_18.hsphsshhaphheaahehaehsppa.heaahsphpeepeaephappeahph(ClientLevel.java:517)
	at net.minecraft.v1_18.apsaspeeshehsehppapespsss.hhepeapshphahsspepssshpse(SourceFile:2402)
	at net.minecraft.v1_18.apsaspeeshehsehppapespsss.hehesepapspsapapeheappsaa(SourceFile:757)
	at net.minecraft.client.main.Main.main(SourceFile:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.moonsworth.lunar.patcher.LunarMain.main(Unknown Source)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, textures, Improved Pack

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1653245720 bytes (1576 MiB) / 3221225472 bytes (3072 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2191
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 24239.24
	Virtual memory used (MB): 18860.88
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 420.32
	JVM Flags: 6 total; -XX:+DisableAttachMechanism -XX:+DisableAttachMechanism -Xms3072m -Xmx3072m -XX:+DisableAttachMechanism -XX:+DisableAttachMechanism
	Launched Version: 1.18
	Backend library: LWJGL version 3.2.3 build 13
	Backend API: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 1920x991
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Operation is not valid from the core profile.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'lunarclient:0e602c2'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, lunar (incompatible), file/Improved Pack (incompatible)
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.18_HD_U_H3
	OptiFine Build: 20211206-183717
	Render Distance Chunks: 17
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.31+Extreme
	OpenGlVersion: 3.2.0 NVIDIA 497.09
	OpenGlRenderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by oShadowMinecraft** [comment]
shoot wrong one again

**Comment by maruohon** [comment]
Check your launcher profile game directory stuff, since you have a logs and mods directory inside the `.minecraft/mods/` directory, it seems a bit suspicious... Are the logs now inside `.minecraft/mods/logs/`? Ie. do you have the game directory pointed to `.minecraft/mods/` instead of the `.minecraft` directory?

**Comment by oShadowMinecraft** [comment]
this is the path for fabric 

C:\Users\Adam Weston\AppData\Roaming\ .minecraft\mods

I went to my mods folder and now there are more folders in it - .fabric, mods, logs, resource packs and saves
[latest.log](https://github.com/maruohon/litematica/files/7850297/latest.log)

in the logs folder there was this if it helps 

![image](https://user-images.githubusercontent.com/97486746/149032986-9ec5da61-2096-4f4b-9b10-b5c43609857d.png)
![image](https://user-images.githubusercontent.com/97486746/149033025-f24a1478-d268-41f0-8b10-44386a1cb604.png)

**Comment by maruohon** [comment]
That log had almost nothing in it.

But also you should not be pointing the game directory to the mods directory. Because now you have essentially nested the ".minecraft" directory (ie. what the game uses as the main directory) inside the `.minecraft/mods/` directory, instead of it being the upper/normal `.minecraft` directory itself. Instead, if you want it to be separate from the vanilla game directory for example, then make it something like `C:\Users\Adam Weston\AppData\Roaming\.minecraft_fabric` so that it's "adjacent" to the normal `.minecraft` directory instead of nested inside it.

**Comment by oShadowMinecraft** [comment]
ok and then in that C:\Users\Adam Weston\AppData\Roaming\.minecraft_fabric folder should I just put the mods right in it, or something else?

**Comment by maruohon** [comment]
There will then be a `mods/` directory inside that. If you just launch the game once with the game directory set to that, the game and Fabric loader will automatically create the directories there.

**Comment by oShadowMinecraft** [comment]
and then just put the mods in that folder? if that's it thank you so much!!!

**Comment by oShadowMinecraft** [comment]
YES YES YES I DID IT TYSMMMMMMMMMMMMM
![image](https://user-images.githubusercontent.com/97486746/149043058-4dda76d4-42ca-43d7-8096-d58780120849.png)
 ILY <3
