### ISSUE TITLE
separate material lists for each sub-region

### ISSUE THREAD

**Issue by pfreundl** [maruohon/litematica#478]
Hi :)
It would be cool if you could display a material list per sub-region, so multiple people can work on a large project far more efficiently: 
You could choose a subregion to build, check its list, collect the materials from the project storage and get to work without allocating materials meant for other parts of the project. compared to multiple schematics this would ensure correct placement of all sub-regions and make it easier to collect all ressources for the whole project at once. 
thanks for reading!

**Comment by maruohon** [comment]
There are currently two ways to do that.
* If you hold shift when you click on the `Material List` button in the `Load Schematics` menu to create a direct schematic-based material list, you can then select the sub-region to generate the list for.
* If you create the material list for a placement (to also see the progress and still missing items), then you need to turn off all the rest of the sub-regions in the placement configuration menu. When you then refresh the material list, it will only count the stuff in the enabled sub-regions.

There is a whole bunch of improvements planned for the material list stuff still, so this might also improve in future versions, for example such that you could select the sub-regions via the material list menu while having all regions enabled in the placement.

**Comment by pfreundl** [comment]
Thank you for the fast answer!

Sorry i didn't realize it was possible already. i didn't reload the material list after toggeling the sub-regions and i didn't read the tooltip in the "load scematic" menu. would it be possible to automatically trigger a material list reload when a sub-region placement is toggeled? also maybe put a button in the material list screen, where you can open the menu to select sub-regions.  its a really great feature and a bit hard to find for nubs like me ;D this would be my take on how to present that feature more prominently, but it sounds like you already have plans to redo some stuff there. 

anyway thank you for your help and the great work you guys are doing here! litematica is really awesome!
