### ISSUE TITLE
i cant create scamatic pls help me 

### ISSUE THREAD

**Issue by CASTILLOCG** [maruohon/litematica#490]
## Please don't post simple questions on this issue tracker!
Simple questions like "How do I do X?" should instead be handled either on the Discussions area (see on the top of the page) or on Discord:
* My Discord server: https://masa.dy.fi/discord -> `#litematica`
* or the SciCraft Discord: https://discord.gg/scicraft -> `#masas-mods`
Every message on the issue tracker here sends an email to me, and a message on two Discord servers. So having simple support conversations here gets really spammy and annoying. Please use one of the above mentioned alternatives instead.

### Other rules
* **Before reporting an issue, please make sure it has not already been fixed in a later version!** Also make sure you have the latest version of **both Litematica and malilib!** There are occasionally changes that **will require** both mods to be updated at the same time, or something will break!
  * There are occasionally development versions here: https://masa.dy.fi/mcmods/client_mods/
  * Also check on CurseForge: https://www.curseforge.com/minecraft/mc-mods/litematica/files
  * See which page has the latest version. Starting with Minecraft 1.17, I will not keep all the mods for the current Minecraft version on my server anymore. There are now only mod builds on my server leading up to a new version on CurseForge. So in other words, if the mod is listed on my server, then it should be the latest version. If it's not there at all, then the latest version is on CurseForge. But check both just in case, to see what the latest version is.
* **No snapshot issues** - Don't post issues for mod versions made for Minecraft snapshots on this tracker. The snapshot versions aren't "properly" supported or tested. Snapshot versions (when or if they are available) are only provided as quick ports (when I have the time and motivation to make them) in a "might work, mostly" basis. Any issues with snapshot versions should rather be handled on Discord, see above.

### Provide at least the following information
* **Minecraft version** - Which Minecraft version are you playing on?
* **Mod version and malilib version** - Which **exact** mod version are you using?
  * Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
  * **"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.
* **A clear description of the issue** - I'm not a psychic, so you have to describe the issue thoroughly enough for me to be able to reproduce it **without knowing anything at all that is not described in the issue report**.

**Comment by CASTILLOCG** [comment]
when you have a stick on your hand you can see your in area selection mode but mine not showing i cant make any scamatics
PLS HELP my DISCORD Castillo#6826

**Comment by Coathar** [comment]
There is a toggle to enable the tool which by default is M + T. Also, in the future you should join the Discord to ask questions like this. The link can be found at the top of the prefilled text in this issue.
