### ISSUE TITLE
schematic block rendering not work

### ISSUE THREAD

**Issue by onenok** [maruohon/litematica#491]
### Mod List:
jei_1.12.2-4.16.1.302.jar
litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar
malilib-forge-1.12.2-0.10.0-dev.23.jar
OptiFine-OptiFine-1.12.2_HD_U_G5.jar
VeinMiner-1.12-0.38.2.647+b31535a.jar
worldedit-forge-mc1.12.2-6.1.10-dist.jar
Xaeros_Minimap_21.5.0_Forge_1.12.jar
### other
**Running on forge 1.12.2-14.23.5.2860**
**litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar** and **malilib-forge-1.12.2-0.10.0-dev.23.jar**
is download in [masa's site](https://masa.dy.fi/tmp/minecraft/mods/client_mods/?mcver=1.12.2)
![2022-02-08_15 29 46](https://user-images.githubusercontent.com/83169133/152938943-165decaf-c0f9-423b-ae95-83009d1263c3.png)

**Comment by maruohon** [comment]
Looks like that old versions still hasn't been fixed to work with shaders. So set shaders in Optifine to OFF instead of Internal, and then possibly restart the game or at least re-log to the world.

**Comment by onenok** [comment]
where?

**Comment by onenok** [comment]
where

**Comment by maruohon** [comment]
In Options -> Video Settings -> Shaders. You really didn't find the menu by now without it being pointed out?

**Comment by onenok** [comment]
I found it myself but thanks
