### ISSUE TITLE
Opti fine texture isn't loading correctly.

### ISSUE THREAD

**Issue by Enikimm** [maruohon/litematica#492]
## Please don't post simple questions on this issue tracker!
Simple questions like "How do I do X?" should instead be handled either on the Discussions area (see on the top of the page) or on Discord:
* My Discord server: https://masa.dy.fi/discord -> `#litematica`
* or the SciCraft Discord: https://discord.gg/scicraft -> `#masas-mods`
Every message on the issue tracker here sends an email to me, and a message on two Discord servers. So having simple support conversations here gets really spammy and annoying. Please use one of the above mentioned alternatives instead.

### Other rules
* **Before reporting an issue, please make sure it has not already been fixed in a later version!** Also make sure you have the latest version of **both Litematica and malilib!** There are occasionally changes that **will require** both mods to be updated at the same time, or something will break!
  * There are occasionally development versions here: https://masa.dy.fi/mcmods/client_mods/
  * Also check on CurseForge: https://www.curseforge.com/minecraft/mc-mods/litematica/files
  * See which page has the latest version. Starting with Minecraft 1.17, I will not keep all the mods for the current Minecraft version on my server anymore. There are now only mod builds on my server leading up to a new version on CurseForge. So in other words, if the mod is listed on my server, then it should be the latest version. If it's not there at all, then the latest version is on CurseForge. But check both just in case, to see what the latest version is.
* **No snapshot issues** - Don't post issues for mod versions made for Minecraft snapshots on this tracker. The snapshot versions aren't "properly" supported or tested. Snapshot versions (when or if they are available) are only provided as quick ports (when I have the time and motivation to make them) in a "might work, mostly" basis. Any issues with snapshot versions should rather be handled on Discord, see above.

### Provide at least the following information
* **Minecraft version** - Which Minecraft version are you playing on? 1.18.1
* **Mod version and malilib version** - Which **exact** mod version are you using? 0.11.6
  * Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu. version 0.10.1 litematica
  * **"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.
* **A clear description of the issue** - I'm not a psychic, so you have to describe the issue thoroughly enough for me to be able to reproduce it **without knowing anything at all that is not described in the issue report**.

The texture's ain't loading correctly. I read the curseforge page and it said all I needed to do was rename the optifine file to said name. I did but the result isn't exactly what I was looking for. It seems they didn't load correctly.
![2022-02-08_11 46 57](https://user-images.githubusercontent.com/75760726/153045915-f3b89ef2-3c20-4ef2-892c-c588d04f860b.png)
![2022-02-08_11 46 55](https://user-images.githubusercontent.com/75760726/153045920-d32091ee-56bc-4c4f-848f-42d7c169375d.png)
.

**Comment by maruohon** [comment]
What? Is this even related to Litematica in any way?

**Comment by Enikimm** [comment]
im not sure if its a bug or not I just dont know why this isn't loading optifine files seeing as the mod was made to follow closely to optifine. I just dont understand why it isn't loading correctly.

**Comment by maruohon** [comment]
Are you talking about the Iris mod? This is the issue tracker for Litematica, the schematic mod. This has nothing at all to do with Optifine.

**Comment by Enikimm** [comment]
wait I just realized that this is the wrong forum sorry I confused this mod with Custom Entities'
 I have way to much on my mind.

**Comment by Enikimm** [comment]
im never been good at multi tasking
