### ISSUE TITLE
easy places not work in multiplayer but server is using Open to LAN and Vpn to connect.

### ISSUE THREAD

**Issue by onenok** [maruohon/litematica#498]
### Mod List:
jei_1.12.2-4.16.1.302.jar
litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar
malilib-forge-1.12.2-0.10.0-dev.23.jar
OptiFine-OptiFine-1.12.2_HD_U_G5.jar
VeinMiner-1.12-0.38.2.647+b31535a.jar
worldedit-forge-mc1.12.2-6.1.10-dist.jar
Xaeros_Minimap_21.5.0_Forge_1.12.jar
### other
**Running on forge 1.12.2-14.23.5.2860**
**litematica-forge-1.12.2-0.0.0-dev.20191217.195055.jar** and **malilib-forge-1.12.2-0.10.0-dev.23.jar**
is download in [masa's site](https://masa.dy.fi/tmp/minecraft/mods/client_mods/?mcver=1.12.2)
###
easy places don't work, I know it might not work in the server but it is using Open to LAN and Vpn to connect
Is there any way to make the server allow easy places to work?
(I am not the host of the world)

**Comment by maruohon** [comment]
It should work if you add Tweakeroo to the client that is hosting the server, and make sure to **not disable** the `clientPlacementRotation` option, which is enabled by default. I don't remember if ForgedCarpet has the accurate placement protocol too, it might. But I think adding Tweakeroo would be easier and more reliable in this case, as I know that the protocol there is compatible and pretty generic.

**Comment by onenok** [comment]
but it hasn't 1.12.2 forge version, just has 1.12.2 litmod

**Comment by onenok** [comment]
found, THX

**Comment by onenok** [comment]
it crashes when use Tweakroo

**Comment by maruohon** [comment]
It might be a conflict with some other mod, although if you mod list is complete then you don't have that many other "weird" mods, but I haven't tested it with most of those. Can you post the crash log, otherwise I have no idea why it's crashing or what it might be conflicting with.

**Comment by onenok** [comment]
I know why it crashes, I forgot to give it its requires mod.

**Comment by onenok** [comment]
thx
