### ISSUE TITLE
Easy Place mode doesn't work well with blocks which have 'facing' tags in 1.18.1 server

### ISSUE THREAD

**Issue by UCMHCteacher** [maruohon/litematica#499]
I have already **enabled** `accurateBlockPlacement` in carpetextra and also **enabled** `carpetAccuratePlacementProtocol` and `clientPlacementRotation` in tweakroo settings, but some redstone components such as pistons, dispensers and observers still have a wrong facing when using easy place mode
Additionally, if I turn on `placementRotationFix` in carpet, these blocks have the right facing when placed if their facing is either north, south, east or west and player is facing either north, south, east or west.

### **Server Mod List:**
![server](https://user-images.githubusercontent.com/100867395/156714360-0a12ceb9-3478-4b29-a2fb-e1fc30646477.png)
running on fabric loader 0.13.3
minecraft 1.18.1

### **Client Mod List:**
![clientmods](https://user-images.githubusercontent.com/100867395/156714653-146033b3-d514-48b1-b18c-2c634f77d7a4.png)
running on fabric loader 0.13.3
minecraft 1.18.1

(I am Chinese and I am not good at English. I'm sorry if it brings inconvenience to your understanding.)

**Comment by aria1th** [comment]
its carpet's fault that only support 'certain' blocks, use this fork to support any blocks with facing : 
https://github.com/aria1th/carpet-extra/releases/tag/1.4.56.3
Idk why pr is not merged until now, but it works with any modded or vanilla blocks that have proper facing values.
and I forgot... for dropper / redstone components yes its protocolVersion

**Comment by maruohon** [comment]
Check the `easyPlaceProtocolVersion` config in the Generic category. You may need to switch it to `v2` while on the server. If Litematica doesn't see the `carpet:hello` packet from the server then it won't automatically use `v2` while in the `Auto` mode.

(The feature to automatically use `v2` on a server that sends a `carpet:hello` packet if the config is set to `Auto` was added in 0.10.0, so 0.9.x would never do that.)

**Comment by UCMHCteacher** [comment]
Thanks, this is very helpful!
