### ISSUE TITLE
Empty Material List

### ISSUE THREAD

**Issue by SangeloDev** [maruohon/litematica#500]
Basically what the title says. My material list is always empty for any schematic that I try that uses modded blocks. Any help would be appreciated

**Comment by maruohon** [comment]
Are you creating the material list directly for a schematic file from the Load Schematics screen, or for a placement via the placement configuration screen or the material list hotkey? If this is for a placement, is it a large schematic, did the block counting task complete (i.e. the missing chunks HUD text goes away from the bottom right)?

Or is it simply broken for any small schematics that have modded blocks? Do you have the mods installed that those blocks are from? Are there are errors or warning in the game console when you try to open the material list?

**Comment by SangeloDev** [comment]
> Are you creating the material list directly for a schematic file from the Load Schematics screen, or for a placement via the placement configuration screen or the material list hotkey? If this is for a placement, is it a large schematic, did the block counting task complete (i.e. the missing chunks HUD text goes away from the bottom right)?
> 
> Or is it simply broken for any small schematics that have modded blocks? Do you have the mods installed that those blocks are from? Are there are errors or warning in the game console when you try to open the material list?

It happens for every schematic I try that has any modded blocks. I've modified a building which worked great with the schematic with modded blocks and now nothing shows up

**Comment by maruohon** [comment]
Can you send me some of such schematics that are affected? And also list the mods that the schematic uses blocks from.

Does the rendering and other things work properly, and just the Material List is broken?
