### ISSUE TITLE
[1.18.2]Litematica crash when loading schematic

### ISSUE THREAD

**Issue by KohlrabitoDev** [maruohon/litematica#501]
### Provide at least the following information
* **Minecraft version** - Which Minecraft version are you playing on?
* `1.18.2`
* **Mod version and malilib version** - Which **exact** mod version are you using?
* `malilib-fabric-1.18.2-0.12.0`
  * Include the **full** mod file name which includes the build date and time for the development versions, or you can see the mod version in the title of the Litematica main menu.
  * `litematica-fabric-1.18.2-0.11.0`
  * **"Latest" is not a version!!** It's ambiguous, it's a moving target, and very often the version is not *actually* even the latest available version at that time.
* **A clear description of the issue** - I'm not a psychic, so you have to describe the issue thoroughly enough for me to be able to reproduce it **without knowing anything at all that is not described in the issue report**.
```
The game crashed as I tried placing my schematic that I took from Scicraft -> https://ufile.io/eaxflgdu
Error log -> https://pastebin.com/mf6P3qP1
```

**Comment by maruohon** [comment]
```
java.lang.ClassCastException: class fi.dy.masa.litematica.world.WorldSchematic cannot be cast to class net.minecraft.class_638 (fi.dy.masa.litematica.world.WorldSchematic and net.minecraft.class_638 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @604c5de8)
    at shcm.shsupercm.fabric.citresewn.ActiveCITs.getItemModelCached(ActiveCITs.java:137)
```
That's the CITResewn mod trying to cast the schematic world into a `ClientWorld` without checking first that it is one (which it's not).

**Comment by maruohon** [comment]
Looks to be fixed in a later version of CITResewn.
