### ISSUE TITLE
Is there a new update for the Forge version?

### ISSUE THREAD

**Issue by KrD5** [maruohon/litematica#504]
**Is your feature request related to a problem? Please describe.**

Hello, I am a gamer in Korea.
I am sad that the fabric mode is blocked on the server I have been using for 6 years.
We recommend using the Forge version, but this mod has no updates since 1.16.5

**Describe the solution you'd like**

No matter how long it took, I hope the 1.18 version will have a usable mod.

**Describe alternatives you've considered**

To be honest I don't have much to say because I don't know how difficult and difficult it is to make a Minecraft mod.

**Additional context**

**Comment by maruohon** [comment]
There is no official Forge version of Litematica yet except for 1.12.2. (Official meaning a port that I made myself - the 1.16.5 port was made by another user).

Forge ports are planned, probably for all MC versions from 1.14.4 onwards. But I will only make those ports after the mod rewrites and code clean-up and new features and improvements (that are being done in the 1.12.2 LiteLoader version at the moment) are all finished. There is a LOT of stuff to do, and I simply have no idea how long all of that is going to take. So I have no idea when the Forge ports will happen. It will likely still be several months at minimum.

**Comment by KrD5** [comment]
i See.
I don't know when
I'm glad to hear that there is a Forge version.
