### ISSUE TITLE
Can't save an area selection to a litematic - 1.14.4

### ISSUE THREAD

**Issue by EmeraldSnorlax** [maruohon/litematica#51]
I have created an area selection titled `iron_farm`, and gotten the selection over the area I want.
However, pressing Crtl + S does not bring up the save dialogue, rather it just moves my player backwards.
![Screenshot](https://i.imgur.com/n6XfI4H.png)
I have tried holding the stick, holding nothing, flying, standing on the ground, going to survival to creative and back again, and it still will not bring up the save dialogue.

I am on Litematica version `litematica-fabric-1.14.4-0.0.0-dev.20190720.191654.jar`
I am on Fabric version `0.4.8+build.159-1.14.4`
I have installed the required dependencies

If it helps, I am using 64bit Manjaro Linux, using a QWERTY-UK keyboard, OpenJDK8 (`OpenJDK Runtime Environment (build 1.8.0_222-b05) 64bit`, other java programs and mods work fine)  and no other mods except the dependencies.

**Comment by maruohon** [comment]
The default hotkey for saving should be Ctrl + Alt + S, I believe? But there is also a button to save the schematic in the Area Editor GUI (which should by default open with numpad multiply, or from the main menu button).

**Comment by EmeraldSnorlax** [comment]
crtl + alt + s did not work, but numpad * did, thanks
