### ISSUE TITLE
[Suggestion] Give shulker(s) with all needed blocks to build the schematic

### ISSUE THREAD

**Issue by erxson** [maruohon/litematica#522]
Just add button to material list menu which will give every item from material list.

**Comment by maruohon** [comment]
I don't quite understand, what is the point of this? If you use cheats, then you can just use creative mode directly, and the pick block and Easy Place already auto-give you the correct item in creative mode. Or you can just paste the entire schematic in one go which is vastly better than building it by hand in creative.

**Comment by erxson** [comment]
It is useful if you make a video where you take a shulker with all the necessary things in the beginning and build in survival mode. Or just trying to hide that you're abusing creative mode :) (sory for my bad england, translated with deepl)

**Comment by Felix14-v2** [comment]
> It is useful if you make a video where you take a shulker with all the necessary things in the beginning and build in survival mode. Or just trying to hide that you're abusing creative mode :) (sory for my bad england, translated with deepl)

For this goal you can use already existing solutions. For example, [this plugin](https://www.reddit.com/r/BlingEdit/comments/a32sat/region_info_plugin_update_b2/)  for [this datapack](https://www.reddit.com/r/BlingEdit/comments/ofop9n/1171_support/).

**Comment by erxson** [comment]
Thank you!
