### ISSUE TITLE
Add the mod to modrinth

### ISSUE THREAD

**Issue by istudyatuni** [maruohon/litematica#524]
I think it would be great to add this mod (and malilib respectively) to https://modrinth.com

Thank you for this cool project!

**Comment by fooeyround** [comment]
While, Yes this would be great, ATM Modrinth has **no** Payout of any Kind, and Masa only Uses CF for the Reward Points AFAIK, if Modrinth gets a Payment System I am 99% sure masa will switch to Modrinth. NTM how hard Masa Has Worked on these Mods.
Another issue Is AFAIK because of his Location He cannot Start a Patreon.

**Comment by Orochikaku** [comment]
Just an update, [Modrinth's Creator Monetization Program is currently in an open beta](https://blog.modrinth.com/creator-monetization-beta/)

**Comment by Orochikaku** [comment]
> While, Yes this would be great, ATM Modrinth has **no** Payout of any Kind, and Masa only Uses CF for the Reward Points AFAIK, if Modrinth gets a Payment System I am 99% sure masa will switch to Modrinth. NTM how hard Masa Has Worked on these Mods. Another issue Is AFAIK because of his Location He cannot Start a Patreon.

Just an update, [Modrinth's Creator Monetization Program is currently in an open beta](https://blog.modrinth.com/creator-monetization-beta/)

**Comment by ghost** [comment]
Any update on this?

**Comment by maruohon** [comment]
This is in-progress. But it will take me a while to upload all the old mod releases in the correct order, with proper changelogs for each release. Thus far I've done  4 of the easiest (and most useless?) of my old mods.

![Screenshot 2023-05-16 at 07-53-35 Projects - Modrinth](https://github.com/maruohon/litematica/assets/2331050/38ee68a6-2729-4d4b-a40e-07ae5b175ff6)

**Comment by ghost** [comment]
> This is in-progress. But it will take me a while to upload all the old mod releases in the correct order, with proper changelogs for each release. Thus far I've done  4 of the easiest (and most useless?) of my old mods.
> 
> ![Screenshot 2023-05-16 at 07-53-35 Projects - Modrinth](https://github.com/maruohon/litematica/assets/2331050/38ee68a6-2729-4d4b-a40e-07ae5b175ff6)
> 

That's awesome! Thank you so much for the update! :)

**Comment by srnyx** [comment]
> This is in-progress. But it will take me a while to upload all the old mod releases in the correct order, with proper changelogs for each release.

If I were you, I would just upload each latest version that supports a unique Minecraft version.
For example, for MiniHUD, you'd just upload:
- **1.8:** `1.8-0.2.0`
- **1.8.8:** `1.8.9-0.1.0`
- **1.8.9:** `1.8.9-0.4.0`
- **1.9:** `1.9-0.4.1`
- **1.9.4 & 1.10:** `1.10.2-0.9.0`
- **1.10.2:** `1.10.2-0.10.0`
- **1.11:** `1.11.2-0.9.0`
- **1.11.2:** `1.11.2-0.12.0`
- **1.12-1.12.2:** `1.12.2-0.13.1`
- etc...

**Comment by QarthO** [comment]
Any progress on this? Been over a year since the original post.

For now, could you just upload the latest version for the bigger/more popular mods of yours? Safe to assume that 90% of ur mod users are on MC 1.20+

Since you already have the projects drafted and Modrinth has an easy way to add a member to the project, I would love to help upload all the older versions and populate the change logs based on curseforges for each specific version.

**Comment by vacla** [comment]
This is masa's recent progress with uploading including painted biomes now also ![modrinth_projects_2023-10-15](https://github.com/maruohon/litematica/assets/10290022/50f44568-9fbb-4e6d-a128-d8dbc672cb25)

**Comment by Fefedu973** [comment]
Hi ! any updates ?

**Comment by einekratzekatze** [comment]
bump

**Comment by AlexanderHott** [comment]
Is there a roadmap to get litematica on modrinth?

**Comment by 1GodRage** [comment]
> ATM Modrinth has **no** Payout of any Kind, and Masa only Uses CF for the Reward Points AFAIK

Now in 2024, with Modrinth you can get Payout with paypal.

**Comment by shap-po** [comment]
+1 here

**Comment by CompeyDev** [comment]
Seems like it was published on Modrinth: https://modrinth.com/mod/litematica.
