### ISSUE TITLE
[BUG] Leaf distance is not a state

### ISSUE THREAD

**Issue by Timmie644** [maruohon/litematica#536]
is the leaf distance tag is wrong it shows a wrong block instead of wrong state as shown in the picture below
![image](https://user-images.githubusercontent.com/80573589/169707163-06139c2d-dc83-4f46-bcb5-857f4b21db10.png)

**Comment by maruohon** [comment]
Look at the Block Info Lines at the top right corner ;) (Dark Oak leaves vs. Oak Leaves)

**Comment by Timmie644** [comment]
sorry my bad didn't see it
