### ISSUE TITLE
Most tool modes stopped working in survival words.

### ISSUE THREAD

**Issue by VslyDream** [maruohon/litematica#539]
Reinstall few times, but still have only 1, 2, 9 tool modes. Sad, because easy place mod was really usefull.

Minecraft 1.18.1, litematica-fabric-1.18.1-0.10.4, malilib-fabric-1.18.1-0.11.8

**Comment by maruohon** [comment]
The other tool modes are creative-only functionality. The Easy Place mode is not a tool mode, it's just a config (with an associated toggle hotkey) that you enable to use the Easy Place block placement feature.

**Comment by VslyDream** [comment]
Thx. Don't know why, but had all tool modes in survival server for few days. Thought Easy Place mod was turned off with them.
