### ISSUE TITLE
Issues with Iris Shaders for Fabric

### ISSUE THREAD

**Issue by CreeperPeruano** [maruohon/litematica#540]
So I started using this mod so I can build my house I made in creative in my survival, but hologram doesn't render using Iris Shaders

+ FABRIC 0.14.6 - 1.18.2
+ Fabric API 1.18.2 - 0.53.0
+ Litematica Fabric 1.18.2 - 0.11.3
+ MaLiLib Fabric 1.18.2 - 0.12.1
+ Sodium Fabric 1.18.2 - 0.4.1+build.15
+ Iris Shaders Fabric 1.18.2 - 1.2.2+build.32
+ Complementary Shaders 4.4
-------------------------------------
I've found some issues while using this mods/shaders and with other shaders too
* Hologram Blocks don't appear
* Borders appear, but opacity filter doesn't work (full transparent or full opaque)
* Somehow, blocks are not rendered, but shadows do
-----------------------------------------
![renderbug](https://user-images.githubusercontent.com/103972718/172025289-94f18554-4ef9-4aef-81c5-802d685865f4.png)

**Comment by aditeya24** [comment]
Shaders currently break the schematic rendering. Toggle the shaders off and then toggle the schematic rendering off and on to fix it.

**Comment by Felix14-v2** [comment]
This seems to be fixed in [Iris 1.2.5](https://rewrite.modrinth.com/mod/iris/version/1.18.x-v1.2.5)
![Screenshot_20220607-134439](https://user-images.githubusercontent.com/75726196/172361342-e73c8e2e-46b1-4c57-88fd-75160b46e31f.jpg)

**Comment by fooeyround** [comment]
Yes. This issue may be closed now :) by masa or issue reporter
