### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by forshale** [maruohon/litematica#542]
**Is your feature request related to a problem? Please describe.**

Posting this here to get updated on when Litematica gets updated to 1.19!

**Comment by tobfos2611** [comment]
Yes I would love this mod to be updated!

**Comment by OoLunar** [comment]
There is a community-maintained port for 1.19: https://kosma.pl/masamods/

These maintainers seem to want the best for Masa and seem to genuinely support them. They link to the original mod page, they've open-sourced their ports and they seem to have ported a good chunk of Masa's mods. I don't know what Masa thinks of this, but these ported mods seem to be a good temporary replacement until Masa finishes their brilliant work
