### ISSUE TITLE
Please make this fabric version 0.13.0

### ISSUE THREAD

**Issue by NRPRED** [maruohon/litematica#551]
I was downloading litematica only to find out that it is on fabric loader version 0.12.3 and malilib is on version 0.13.0

**Comment by maruohon** [comment]
... what?

I assume you are mixing the 1.19.0 community releases of some of my mods with the "official" releases from CurseForge. You can't mix them (due to the way the version numbers were set), get all of them from the "same set" - community or official.

**Comment by eat-your-glory** [comment]
I think they removed the community version from the website and the discord
So only official now

**Comment by kosma** [comment]
The community builds for 1.19 are still available but please don't mix them with the official releases.

**Comment by eat-your-glory** [comment]
Still available? didn't you remove them from the website Kosma?

**Comment by kosma** [comment]
Please get glasses, there's a link at the bottom ;)

**Comment by eat-your-glory** [comment]
Sorry didn't see the "here" button
Have a good day both of you
