### ISSUE TITLE
Game crashes when using stick

### ISSUE THREAD

**Issue by simsen44** [maruohon/litematica#553]
Im using the newest versin of litematica "litematica-fabric-1.19.2-0.12.3" on a 2020 mac mini m1. 

when i try to do anything whilst holding the stick, like paste a schematic into the world or edit the placement my game crashes and gives me the eror code 

The game crashed whilst unexpected error
Error: java.lang.NoSuchFieldError: field_11733
Slutkod: 255

upon opening the game again the wanted commend was executed (aka the schematic got pasted or moved) but the game still crashed. 

this is very annoying >:(

**Comment by maruohon** [comment]
I assume you are playing 1.19 and not 1.19.2 then? Or do you have malilib for 1.19.0 while you are in 1.19.2?

Get all the mods for the MC version you are actually playing.

**Comment by simsen44** [comment]
oooo yhheee probably need malilib 1.19.2 and not 1.19.0...  thanks for the support
