### ISSUE TITLE
Auto Builder (Baritone shut up)

### ISSUE THREAD

**Issue by arushenst** [maruohon/litematica#555]
Please, make an automatic builder so that I can, for example, just go away to drink tea or do business, and it builds for me. I say right away that Baritone does not suit me because it is necessary that the blocks for construction be in a hot bar. Maybe there is already some kind of such mod for 1.19 factories? If there is, please tell me what kind of mod

**Comment by maruohon** [comment]
There are separate printer extension mods for auto-building. But those won't move the player automatically (AFAIK).

For also automatically moving the player you pretty much need Baritone. There has actually been work done on Baritone's auto-building and other related features recently (by someone who is on my Discord and has been working on various things such as Litematica schematic support for Baritone).

And for creative mode there is the direct Paste feature in the mod.

Printer extensions:
First one:
https://github.com/aleksilassila/litematica-printer

Second one:
https://github.com/aria1th/litematica-printer/releases

Or the version that second fork is based on:
https://github.com/jensvh/litematica-printer/releases
