### ISSUE TITLE
game crashes after joining any mc world

### ISSUE THREAD

**Issue by Agriotes** [maruohon/litematica#561]
As the title says, the game crashes after I try to join any mc world/server. 
I followed those instructions https://www.youtube.com/watch?v=aMZSXAKZzpo step by step and yet something went wrong...  I use mc 1.19, OptiFine_1.19_HD_U_H9, optifabric-1.13.8, malilib-fabric-1.19.0-0.13.0 (tried latest version as well but problem still occurs) and litematica-fabric-1.19.0-0.12.0

[crash-2022-08-19_18.31.58-client.txt](https://github.com/maruohon/litematica/files/9384094/crash-2022-08-19_18.31.58-client.txt)

**Comment by maruohon** [comment]
From q quick look that crash doesn't seem like Litematica related. Does it still happen if you just move Litematica out of the mods folder? How about if you take out Optifine and Optifabric instead?

(Optifine is more harmful than helpful for Litematica, that's one thing that tutorial video is kinda misleading about. Optifine used to be a good thing for rendering performance in 1.12.2 and earlier versions, but lately it just causes various issues and doesn't help that much... Sodium is way better for render performance in most cases.)

**Comment by Agriotes** [comment]
After i moved optifine and optifabric from mod folder it started to work. Thanks for help <3
