### ISSUE TITLE
How can I convert .litematic files to .nbt files

### ISSUE THREAD

**Issue by DoctorIDD** [maruohon/litematica#577]
Create Mod can only read .nbt files, 
I have many .litematic files but they can't be printed by schematicannon
**Please tell me how to convert .litematic files to .nbt files**
**I don't want to create a world and print .litematic file then use structure block to save to a .nbt file**

**Comment by DoctorIDD** [comment]
Add: Minecraft version is 1.18.2

**Comment by maruohon** [comment]
You can convert them via the Schematic Manager menu. Select your `*.litematic` file, and then two buttons will appear at the bottom: `Save As:` and `Schematic / Vanilla`. First click on the second button so that it says `Vanilla`, and then click on `Save As:`.

And yes this user interface is super janky. It has been re-done long ago in the 1.12.2 version, but all the 1.13+ versions still enjoy super old main development code from June 2019 :(

**Comment by DoctorIDD** [comment]
It works, but the .nbt files that be converted are very big.
All in all, thank you for your reply :D

**Comment by maruohon** [comment]
The vanilla structure template format is very memory-inefficient, so if you have large schematics, then yes the `*.nbt` files will be very large in comparison to all the other schematic formats.

**Comment by doriandel** [comment]
the thing is create only take nbt file, and there is a file size limit. So if anyone has a fix for that, it would be great haha! I'm still looking for one from my side...

**Comment by sakura-ryoko** [comment]
If there is a size limit, then it's a size limit of whatever is reading in the NBT file.

**Comment by maruohon** [comment]
@doriandel How does the limit present itself? Does Create just give an error message? What does it say exactly, is it about the file/data size, or the dimensions of the schematic (width/height/length)?  One obvious solution for size limits is to save the build in multiple smaller pieces...

**Comment by doriandel** [comment]
@maruohon It seems that it is only a "server rule" to not exceed a specific file size, so I guess it should be fine if I ask the admin to play with the config. I will update with a new comment after that!

**Comment by sunset-shimmer7** [comment]
> You can convert them via the Schematic Manager menu. Select your `*.litematic` file, and then two buttons will appear at the bottom: `Save As:` and `Schematic / Vanilla`. First click on the second button so that it says `Vanilla`, and then click on `Save As:`.
> 
> And yes this user interface is super janky. It has been re-done long ago in the 1.12.2 version, but all the 1.13+ versions still enjoy super old main development code from June 2019 :(

soo, i have no clue how to use the litematica mod, do i have to have it installed in order to do this?
edit: i run curseforge with fabric on mc version 1.20.1
