### ISSUE TITLE
Fabric mods with MultiMC won't open

### ISSUE THREAD

**Issue by EroanII** [maruohon/litematica#58]
I'm trying to run Litematica with MultiMC and I have the Fabric loader and everything, but then when I try to run the game with Litematica, the game won't open. with no Litematica on, just the loader and another mod, it opens just fine. Does anyone know what to do?

**Comment by vacla** [comment]
is malilib also added as mod with litematica?

**Comment by EroanII** [comment]
no, the only mods I have are the Fabric API (0.3.1 Build.208), Litematica (0.0.0-dev.20190720.191654) and Mod Menu. Minecraft runs perfectly with both of the other, non-Litematica mods

**Comment by SunSerega** [comment]
malilib is unility library, needed for litematica to work:
![image](https://user-images.githubusercontent.com/27270190/62989095-576d8580-be4f-11e9-81be-19cdccb4f0c3.png)

Download it here:
https://www.curseforge.com/minecraft/mc-mods/malilib

**Comment by vacla** [comment]
@EroanII did you get it working?

**Comment by EroanII** [comment]
Yes! Thank you so much!

**Comment by SunSerega** [comment]
Can you then close this issue?
