### ISSUE TITLE
Forge (sorry)

### ISSUE THREAD

**Issue by lukeyisthebest** [maruohon/litematica#590]
I know people probably constantly ask you about this. but when will litematica be available for the newer versions of Minecraft? on forge. do you have a rough time frame? or just entirely not sure yet. Thanks in advance :D

**Comment by aditeya24** [comment]
"I still have no idea of any ETAs, but I've been slowly making a little bit of progress on rewriting stuff in 1.12.2 again lately, currently cleaning up some MiniHUD stuff.
So *maybe* it might even happen at some point that I get things rewritten and cleaned up? In the past few months it kinda looked like it would never happen as I was making zero progress on anything, always too tired after work and just procrastinating away the weekends...." -masa, 2022

He has told multiple times there is no ETA and the last time he gave an ETA, it was said to finish by the end of 2020 I think. So it doesn't really matter what the ETA is, it will be done when it is done. The quoted text above is what masa responded yesterday or so to another person asking about forge 1.18.2
