### ISSUE TITLE
Litematica 1.19.2 doesnt work

### ISSUE THREAD

**Issue by YummyCoin5155** [maruohon/litematica#593]
so im trying to play a 1.19.2 server and i just realized when i play anything on my 1.19.2 pack it doesnt load litematica the controls dont pop up in the controls setting and i have a file loaded in the litematica folder to and it still wont work

**Comment by vacla** [comment]
You need to press M + C to go to the config menu and press M if you want to go to the main menu.

**Comment by YummyCoin5155** [comment]
i have done that it doesnt work

**Comment by maruohon** [comment]
Then do you have Fabric installed? Or are you on Forge? There is no Forge version for 1.19.2 yet.

**Comment by YummyCoin5155** [comment]
I figured out why its because I had a keybind for m what I feel like litematica should do is add the keybinds to the controls in Minecrafts main control settings instead of the mod having its controls in its config

**Comment by viewwee** [comment]
Me Too
