### ISSUE TITLE
Easy place on server doesnt orient blocks

### ISSUE THREAD

**Issue by RuffleSteels** [maruohon/litematica#599]
When I use easy place on my server, the comparator for example doesnt orient the way the schematic says, but it orients normally. I have also added the carpet mod's **accurateBlockPlacement** to see if that would have fixed it but still the blocks dont orient like the schematic. (It works on singleplayer, but not on any servers)

**Comment by maruohon** [comment]
Depending on the server and the mods installed, Litematica might not detect Carpet mod on the server properly. In that case you may need to force the Generic -> `easyPlaceProtocolVersion` config to the `V2` value while you play on such a "Carpet-enabled" server.

Leave it as `Auto` or `V3` in single player, and as `Slabs Only` (or `Disabled`) on non-CarpetExtra-with-`accurateBlockPlacement` servers.

**Comment by ChristopherHaws** [comment]
@maruohon Do you know of any spigot plugins that add support for easy place protocol that work with litematica?

**Comment by maruohon** [comment]
@ChristopherHaws No, I haven't heard of one.

I tried to look at the Bukkit API once to see if it would be possible to make one (not that I intended to work on one, was just curious), and based on that quick look I didn't see a way to make it work. But I'm really now familiar with the API or the entire ecosystem, so I really have no idea if it would be possible to make one.
