### ISSUE TITLE
Updating litematica fails

### ISSUE THREAD

**Issue by SunSerega** [maruohon/litematica#6]
![2019-01-07_12 50 01](https://user-images.githubusercontent.com/27270190/50764499-7b466880-127b-11e9-92d0-64dcc7432fa6.png)

It's kinda annoying to delete .litematica file in explorer every time, when i do 10-20 updates in a row.
Can you add something like messagebox, asking if it's ok to override file and with option "remember answer"?

**Comment by vacla** [comment]
If i remember correct, you can shift click Save schematic and it would overwrite the previous one.

**Comment by maruohon** [comment]
Yep, it should say `Hold shift to overwrite an existing file` when your cursor is over the `Save Schematic` button.

**Comment by SunSerega** [comment]
oh i see...
