### ISSUE TITLE
Crashes to Desktop when I go through a Nether Portal

### ISSUE THREAD

**Issue by tybowman117** [maruohon/litematica#604]
Just as the subject says, anytime a try to change dimensions (I only tested Nether Portals) my client crashes to the desktop. While troubleshooting I did receive two different Crash Reports (Exit Code 1) that I have saved the details but I did not receive Crash Reports 95% of the time I was troubleshooting. I performed a clean install of both Java and my Graphics Driver to no avail. I also tried to set the Java Path, which also did not fix anything. I have had Litematica installed for a few days in a custom Vanilla+ mod pack and just started having the crashes today. I haven't touched the mod in the slightest, ie. I did not ever try any hotkeys. Process of elimination of turning off mods and trying to go through a portal one by one determined my problem starts with Litematica. I've heard nothing but good things about this mod and would love to use it when the desire arises. Thanks.

(masa: Crash log links removed since the `hs_err_pid_*` files have the client token.)

**Comment by maruohon** [comment]
Same issue as #601, so I'm closing this one.

Basically new nvidia drivers started causing crashes with Litematica + Sodium. You probably need to go back a few driver versions for now to prevent the crash.
