### ISSUE TITLE
if i have litematica installed my mc crashes when i change dimesion

### ISSUE THREAD

**Issue by iouhgfc** [maruohon/litematica#605]
(masa: link to log removed as it contains the client token)

**Comment by Koeseb** [comment]
Same here. Did some research Apparently Nvidia fucked something up. Did Nvidia Update today and now it crashes when switching Dimension

**Comment by Hellw0rker** [comment]
Is it possible to fix this bug? Or wait for a new driver from nvidia ?

**Comment by maruohon** [comment]
Duplicate of #601.
