### ISSUE TITLE
loaded schematics turn into a mess

### ISSUE THREAD

**Issue by ADucko** [maruohon/litematica#61]
Whenever i load a schematic it turns into a massive mess. It all stretches all over and makes it basically impossible to use it. 
![2019-08-18_08 59 27](https://user-images.githubusercontent.com/48358179/63221549-e99cc300-c19a-11e9-9edf-0782ffcce6d6.png)
I'm using 1.14.4 fabric to use it and the correct version of litematica and MaLiLib.

**Comment by SunSerega** [comment]
I seen it happening with some optifine settings back when schematica was a thing. Backup yours and try mine:
[optionsof.txt](https://github.com/maruohon/litematica/files/3512800/optionsof.txt)

Also, upload at least one schematic that breaks this way for you.

**Comment by ADucko** [comment]
changing to your optifine options did the trick! 
It seems that any schematic i use turns into that mess when i have those optifine options, should i still send them? Thanks for the help btw

**Comment by vacla** [comment]
can you send the optifine settings that you used?

**Comment by ADucko** [comment]
Sure.
[optionsof.txt](https://github.com/maruohon/litematica/files/3512827/optionsof.txt)

**Comment by ADucko** [comment]
I did some extra testing and i have determined that it's using shaders that is creating this issue.

**Comment by maruohon** [comment]
Yes you need to disable Shaders and Render Regions to get rid of the two worst issues that Optifine causes. And also possibly Fast Render to fix some smaller issues. All of these are mentioned on Litematica's CurseForge page.
