### ISSUE TITLE
Trying to launch litematica for 1.19.2 crashes and say it needs to be launched in 1.19

### ISSUE THREAD

**Issue by Jamietube** [maruohon/litematica#617]
Playing on 1.19.2
Litematica Fabric 1.19.2-0.12.5
Malilib Fabric 1.19.2-0.13.0
When I try to launch the game a window pops up saying that litematica printer requires being in 1.19

![Capture195](https://user-images.githubusercontent.com/117958678/201245483-524fab88-19f1-4a33-956f-e4efceefce5b.png)

**Comment by maruohon** [comment]
Well yes then you have downloaded a 1.19 version of the printer instead of a 1.19.2 version.

https://github.com/aria1th/litematica-printer/releases
or
https://github.com/aleksilassila/litematica-printer/releases
