### ISSUE TITLE
Litematica broke down when she joined the world（1.18.2）

### ISSUE THREAD

**Issue by alazeprt** [maruohon/litematica#619]
I crashed while running lite matica to create the world, this is logs:
[minecraft-exported-logs-2022-11-13T21-44-07.log](https://github.com/maruohon/litematica/files/9997366/minecraft-exported-logs-2022-11-13T21-44-07.log)
Minecraft Version:1.18.2
Litematica Version:0.11.3
Malilib Version:0.12.1

**Comment by maruohon** [comment]
I think this is because the AutoReconnect mod has an issue when you are joining the world, which prevents Litematica's world join related code from running, and it can't create its schematic world, and then it crashes in the rendering code.

So try without the AutoReconnect mod.

**Comment by alazeprt** [comment]
After uninstalling the AutoReconnect module, Litematica runs successfully. Thank you for your help
