### ISSUE TITLE
How to stop destroying my schematic?

### ISSUE THREAD

**Issue by MegaMMC** [maruohon/litematica#62]
I downloaded the mod, made an schematic and now I'm trying to build it, but if I left click any blocks of the schematic they disappear and if I right click I place another block in the schematic(Not an actual block, it just adds a new bock projection)

**Comment by maruohon** [comment]
Sounds like you are in the Schematic Rebuild mode, which is meant for editing schematics. I probably need to rename that to Schematic Edit mode to avoid confusion.

**Comment by MegaMMC** [comment]
>  Rebuild mode

Yeah, I was on Rebuild Mode, now I changed it and it's working fine, thanks, very nice mod btw.
