### ISSUE TITLE
Crash when changing dimensions when combined with sodium

### ISSUE THREAD

**Issue by cs-deathmatch** [maruohon/litematica#620]
(Also reporting on sodium's github, as im not sure who's responsible for fixing this)

Minecraft Version: 1.19.2

Litematica version: latest, 0.12.6-pre.1

MaLaLib version: latest, 0.13.0

Sodium version: latest, 0.4.4 on modrinth, mc1.19.2-0.4.4+build.18 on the filename (their github asks for the second one, not sure if there is a difference)

Steps to reproduce:

1: install sodium alongside Litematica and MaLaLib

2: load into a world or join a server (happens on both) and go into a nether or end portal

3: game window closes upon the "Joining Word" text

video example: https://streamable.com/j8mnpd

crash log: 
[hs_err_pid101476.log](https://github.com/maruohon/litematica/files/10006722/hs_err_pid101476.log)

**Comment by maruohon** [comment]
Duplicate of #601.

**Comment by cs-deathmatch** [comment]
ah, i didnt see anything about litematica or dimensions in the title and assumed it was a different crash, apologies.
