### ISSUE TITLE
Litematica crashes the game when enabling/disabling iris shaders while game is running

### ISSUE THREAD

**Issue by Aspecky** [maruohon/litematica#621]
# Versions:
**Litematica:** litematica-fabric-1.19.2-0.12.5
**Malilib:**      malilib-fabric-1.19.2-0.13.0
**Iris:**            iris-mc1.19.2-1.4.2
**Sodium:**     sodium-fabric-mc1.19.2-0.4.4+build.18

# Drivers:
Nvidea GTX 1060
Driver version: 526.98

# Shader used:
https://minecraftshader.com/sildurs-vibrant-shaders/

# Steps to reproduce:
1) Have the four mods mentioned in *Versions* above in your mods folder
2) Download the shader above and put it in the shaderpacks
3) Launch the game and join a world, be it singleplayer or multiplayer
4) Go to Options > Video Settings > Shader Packs and enable or disable the shaders
5) ???
6) Crash

# Crash logs:
https://pastebin.com/fZ0XpDqz

**Comment by maruohon** [comment]
Probably the same as #601. Try if downgrading your graphics driver fixes it.

**Comment by Aspecky** [comment]
> Probably the same as #601. Try if downgrading your graphics driver fixes it.

Downgrading fixed the issue, any Nvidia driver version above 522.25 causes the crash.
Is there something that can be done or do we have to wait for a future driver version that doesn't cause problems?
