### ISSUE TITLE
Game crashing when entering nether with litematica

### ISSUE THREAD

**Issue by XzSnIpErxX** [maruohon/litematica#624]
![Desktop Screenshot 2022 11 26 - 19 39 48 93](https://user-images.githubusercontent.com/119133065/204106333-4d2f339a-2b97-407c-963a-db8272b46d75.png)
When I enter nether, my game crashes, but, when I remove litematica out of the mods folder, I can enter without problem, so, idk whats happening. Game version is 1.19 and all mods are 1.19, and I cant find bug report in minecraft folder

**Comment by maruohon** [comment]
See #601

**Comment by XzSnIpErxX** [comment]
I downgraded from version 526.98 to 526. 47 and nothing fixed, should I downgrado a lot more?

**Comment by maruohon** [comment]
Like it says in the comments of the linked issue, 522.25 apparently works.

**Comment by XzSnIpErxX** [comment]
oh thanks, I couldn't find it myself
