### ISSUE TITLE
Strange block placements in litematica 1.19

### ISSUE THREAD

**Issue by SlawekYT** [maruohon/litematica#625]
Hi, so i have a problem with litemactica placing blocks in strange positions. for example, originaly stair is to be facing north but in schematics its placed west. I use GrabcraftLitematic mod to get the build
![lite](https://user-images.githubusercontent.com/119143186/204115341-158ce800-1d9b-4052-a627-5272f6c4d271.png)

here is link of the build from grabcraft
https://www.grabcraft.com/minecraft/big-medieval-windmill/medieval-houses#general

**Comment by maruohon** [comment]
I don't think this has anything to do with Litematica? Litematica will show whatever is in the schematic file. Maybe the GrabcraftLitematic mod will create the file incorrectly when it comes to stair rotation?

**Comment by SlawekYT** [comment]
Yup it is problem with GrabcraftLitematic, but still cannot fix it. thanks anyway and sorry for bothering you
