### ISSUE TITLE
MC crashes when I press load schematic

### ISSUE THREAD

**Issue by voidrinix** [maruohon/litematica#626]
Hello!
MC version is 1.19.2, Mod loader quilt 0.17.7
Litematica 0.12.5 and malilib 0.13.0
 litematica-fabric-1.19.2-0.12.5.jar , malilib-fabric-1.19.2-0.13.0.jar

I left the server, logged to another, then I returned to the first server, found that my schematics were unloaded, and when I tried to load it back, minecraft crashed. Relaunch minecraft didn't help, it keeps crashing.

Crash report:
[crash-2022-12-01_20.28.07-client.txt](https://github.com/maruohon/litematica/files/10134895/crash-2022-12-01_20.28.07-client.txt)

**Comment by maruohon** [comment]
Did you add or update any mods recently? Might be a mod conflict of some kind.

One cause for similar crashes has been some other mod that throws an exception when logging in to a world, it may then prevent Litematica's initialization code from running that is supposed to create the schematic world and the renderers.

**Comment by voidrinix** [comment]
> Did you add or update any mods recently? Might be a mod conflict of some kind.
> 
> One cause for similar crashes has been some other mod that throws an exception when logging in to a world, it may then prevent Litematica's initialization code from running that is supposed to create the schematic world and the renderers.

I just rolled back all the mods that I updated today(Sodium Extra and QFAPI), rolled back the modloader but it didn't help. Could this be caused by the fact that I am using linux?

**Comment by voidrinix** [comment]
Something really strange. I joined the server, loaded the schematic and my mc hadn't crashed, but then I joined another, loaded schematic and mc client crashed.
Also crash appears only when creating placement so I can load schematic without creating placement and nothing will happen.

**Comment by maruohon** [comment]
I also use Linux, and it shouldn't affect things in that place in code.

It's most likely caused by some other mod having issues when you log into a world. Sounds like maybe it only happens on the second (and later?) world joins after a game restart?

**Comment by voidrinix** [comment]
> I also use Linux, and it shouldn't affect things in that place in code.
> 
> It's most likely caused by some other mod having issues when you log into a world. Sounds like maybe it only happens on the second (and later?) world joins after a game restart?

I found way to fix it. You need to enter nether and then go back to overworld and loaded schematics will appear
edit: it happened on the first join too

**Comment by ghost** [comment]
That's still a workaround isn't it?
