### ISSUE TITLE
when loading a litematic file with litematica the schematic doesnt show up

### ISSUE THREAD

**Issue by vqzaz** [maruohon/litematica#627]

**Comment by vqzaz** [comment]
why?

**Comment by maruohon** [comment]
How would I know if you don't provide any information?

Here are some free guesses:
* You have the mod main rendering disabled (`M + R`)
* You have the schematic rendering disabled (`M + G`)
* You are in a layer mode such as Single Layer, with the layer set outside of your current placement height range
* You have disabled the `Create Placement` checkmark in the Load Schematic menu, and you are only loading the schematic to memory, not actually placing it anywhere yet

**Comment by vqzaz** [comment]
thanks

**Comment by vqzaz** [comment]
working! ty again
