### ISSUE TITLE
[Suggestion] Add circular build guides

### ISSUE THREAD

**Issue by NitroCipher** [maruohon/litematica#63]
I think that Litematica users could really benefit from the ability to make elliptical build guides of any size

**Comment by SunSerega** [comment]
How exactly do you imagine it and in which cases it would work, where rectangular placements wouldn't be as usefull?

**Comment by maruohon** [comment]
I don't think these belong in Litematica - it's supposed to be a schematic mod, and has features that directly relate to and use schematics, such as many of the creative-mode-only extra features. In "Litematica-terms" building guides of this type would just be normal pre-made guide schematics.

However MiniHUD on the other hand has a "Shape renderer", which is planned to have various different shapes, all of which will be configurable in size etc. (Currently it only has the Despawn Sphere shape). It will have for example box, sphere, circle, ellipse, cylinder, diamond and hopefully also an equation-based free form shape renderer.

**Comment by diegogarciarojo** [comment]
any news of the custom shapes? like ellipsoid
