### ISSUE TITLE
Game crashing when loading worlds

### ISSUE THREAD

**Issue by DustinMK22** [maruohon/litematica#632]
### Provide at least the following information
Minecraft Version: 1.19.3
Mod Version:  1.19.3-0.13.0
malilib Version: 1.19.3-0.14.0
Fabric - 0.14.11
Paper Version: #343
NVIDIA driver: 527.56

I play on a multiplayer server where you can teleport to different worlds.
Every time I teleport to a world the ga
[crash Report.txt](https://github.com/maruohon/litematica/files/10252929/crash.Report.txt)
me crashes.
No matter if a litematic is loaded or not.

I hope this helps to fix the error.
Greetings
Dustin

**Comment by maruohon** [comment]
#601
