### ISSUE TITLE
Game crash on Version 1.19.2 

### ISSUE THREAD

**Issue by mcsnack** [maruohon/litematica#634]
Since the last update, my game crashes as soon as I change a dimension. I disabled the mods one by one. As soon as I remove Litematica the bug is gone. Please fix it. I put the crash log file in a doc. Would you like to pull yourself out?
Kind regards

https://docs.google.com/document/d/16IMiS_47VUE91RTUmlXSDVIY_7Ame0HUpP0dFIPkOLU/edit?usp=sharing

**Comment by vacla** [comment]
Duplicate of #601
