### ISSUE TITLE
Tool Item Not Being Recognized

### ISSUE THREAD

**Issue by StrongholdMafia** [maruohon/litematica#637]
I've been having issues recently after playing on a server where any item I set to the tool item, including the default stick, isn't being recognized. All rendering is enabled too.

**Comment by maruohon** [comment]
Have you disabled the tool item functionality? (`M + T` or Generic -> `toolItemEnabled`)

**Comment by StrongholdMafia** [comment]
I didn't even know that was a thing, to be honest, thanks. Worked a charm!
