### ISSUE TITLE
Crash on loading world after trying to place a schematic

### ISSUE THREAD

**Issue by tholeb** [maruohon/litematica#642]
* **Minecraft version** - 1.19.2
* **Mod version and malilib version**
  - litematica-fabric-1.19.2-0.12.6 
  - malilib-fabric-1.19.2-0.13.0
 
I was following this video https://youtu.be/zHZLvJgpRag?t=173, but the game crashed when I clicked on "load schematic". Now I cannot enter the solo world (creative), it crashes every time. I try to load in.

The crash report: 
![image](https://user-images.githubusercontent.com/43311443/210140445-c8103a9d-0906-451e-a394-8c49c40c96ed.png)
[crash-2022-12-31_15.37.07-client.txt](https://github.com/maruohon/litematica/files/10327481/crash-2022-12-31_15.37.07-client.txt)

The schematic has a lot a create's items.

Mod list:
![image](https://user-images.githubusercontent.com/43311443/210140398-1d4ef7ba-217c-413a-b502-ccdeab17a761.png)
![image](https://user-images.githubusercontent.com/43311443/210140409-684eb4b6-872f-465e-82e5-cdd10b1ae685.png)

I cannot enter any private worlds (existing or brand new). Removing litematica from the modlist fixes this tho.

**Comment by maruohon** [comment]
Duplicate of #636.

The Create mod is doing something weird with their block entities, and when Litematica tries to add the block entities to the schematic world, things go boom. I may need to add some try-catch around that part of the code, or maybe better yet try to construct the schematic world chunks "more sneakily", trying to avoid triggering any other mods' code from running, as it would likely just break things and cause issues if any other mods try to do anything with my schematic world.

Edit: Do you have schematics with Create blocks loaded in all of the worlds you tried to log in to? For now you can log into the worlds again (with Litematica) if you manually go and edit or delete the config files at `.minecraft/config/litematica/<worldname>_<dimension>.json`, and remove the placements for any schematics that have Create blocks in them.

**Comment by tholeb** [comment]
Ok, thanks for the help, I'll close this issue since this is a duplicate of #636
