### ISSUE TITLE
Rebuild Schematic from changed structure?

### ISSUE THREAD

**Issue by rjbarber** [maruohon/litematica#652]
Is it possible to build a schematic, make changes to the the structure that was just built, overlay the schematic on top of the changed structure, and rebuild the schematic while it is in position over the changed structure?

Only way I can figure out how to do this now is to delete the old schematic, select the area again with new area selection and save a new schematic.

Is it possible to just refresh an existing schematic based on the current placement? Or is it possible to create a new area selection from the currently loaded schematic placement so a new schematic and be created with the updated structure?

Hope this wasn't too confusing.

**Comment by maruohon** [comment]
There is currently no way to "refresh" a schematic based on what is in the world. I have new schematic edit mode functionality planned for something like that. But I'd say it's in many cases still better to just save an entirely new schematic, as that avoids the edit mode issues with block entities and entities being uneditable and staying from the initial schematic (although removing entities might get implemented).

You can create a new area selection from the placement. You need to use the "Normal"/Multi-Region mode, and then in the Area Selection Browser you have the button "From Placement" to create a new selection save file from the currently selected placement.

I think I'll also implement a helper shortcut feature that simply allows you to save a new schematic "from the placement", meaning that it will just internally grab that area selection and use it for saving, avoiding the need to do that manually.

**Comment by rjbarber** [comment]
OMG. I looked everywhere for the ability to create a selection area from the current placement. Except apparently in the right place. Thank you! I look forward to the future shortcut for this!!

**Comment by maruohon** [comment]
I guess also allowing to grab the regions from the placement via the Area Editor menu would make sense too... probably just with a confirmation popup that warns that it will overwrite/remove the current regions. And obviously this would not exist/be possible in the Simple mode Area Editor, as it can't have more than one region to match the placement. Well I guess it could check if the current placement has more than one region and then the button would be disabled with a hover tooltip to explain why if it does.

**Comment by rjbarber** [comment]
That would be great!! 

Do you want me to reopen this issue to track since it is now morphing from a help me I'm lost to potential feature update?

**Comment by maruohon** [comment]
I have my "primary todo list" in a local text file (in Dropbox), which is what I usually look at when deciding what to work on next. And the above mentioned features are already on that list. I very rarely if ever (thus far) look at GitHub issues to see what to work on next. I'm not completely (forever) ignoring GitHub issues though. I intend to go through all the open issues and check what still is relevant here and not already done or on my local todo list, after I have the main rewrite and code clean-up part of the mod overhauls done. Which is when I'll start working on the actual todo list items, adding new features and improving and modifying lots of existing functionality, and not just working on cleaning up the code base in general.
