### ISSUE TITLE
Want a function to render only one particular type of block at a time

### ISSUE THREAD

**Issue by Jackylee06** [maruohon/litematica#663]
**Is your feature request related to a problem? Please describe.**
I would like to build a map painting ( I don't know its exact name, but it's probably like a painting and can be captured through maps and can be displayed), and I find it difficult to place all blocks of the same type at a time.

**Describe the solution you'd like**
I'd like a function to render only one particular type of block in a litematica file at a time.

**Describe alternatives you've considered**
Make it able to delete all other blocks and only keep one type of block in a litematica file.

**Additional context**
None.

**Comment by maruohon** [comment]
You can delete all other blocks from the schematic via the Schematic Edit mode, using the `schematicEditBreakAllExcept` key. See the [wiki](https://github.com/maruohon/litematica/wiki/Schematic-Editing).

A separate, renderer-only feature is also planned for this type of thing.

**Comment by Jackylee06** [comment]
Thanks for answering the question! I tried and it worked. Really helped me a lot.
