### ISSUE TITLE
Materials not being detected when going in the materials tab

### ISSUE THREAD

**Issue by hall3lu** [maruohon/litematica#667]
im playing on a new host server in 1.19.3 on a paper server and whenever I try to get the material list it doesnt detect the materials in my shulker box in my inventory or anything in my inventory. I looked into one of the issues which had the similar problem and you said that it was a nbt thing with f3 + h and mine had no nbt tag. Only enchanted stuff had nbt tags and i think thats the issue. Is there a way I can install nbt tags into the server or something? In the last server host same world and files it worked but it doesnt here

**Comment by hall3lu** [comment]
i feel so dumb, never mind man. I looked at it again it was waxed copper and i had normal ones -_- 
edit: how do i delete this issue

**Comment by maruohon** [comment]
There is no way to delete issues as a user... I think? I have a delete link on the right side.
