### ISSUE TITLE
Log spam: SchematicWorldRefresher#markSchematicChunkForRenderUpdate

### ISSUE THREAD

**Issue by Fabian42** [maruohon/litematica#672]
* **Minecraft version**: 1.19.3
* **Mod version and malilib version**: litematica-fabric-1.19.3-0.13.1, malilib-fabric-1.19.3-0.14.0

I'm getting a lot of these printed to the log:

```
[19:14:54] [Render thread/INFO]: SchematicWorldRefresher#markSchematicChunkForRenderUpdate(25, -116)
[19:15:00] [Render thread/INFO]: SchematicWorldRefresher#markSchematicChunkForRenderUpdate(25, -116)
[19:15:01] [Render thread/INFO]: SchematicWorldRefresher#markSchematicChunkForRenderUpdate(31, -118)
[19:15:03] [Render thread/INFO]: SchematicWorldRefresher#markSchematicChunkForRenderUpdate(25, -116)
```

Just in the last hour, I got 15635 of these. I do not currently have any schematics loaded. I haven't actually tested whether this goes away without Litematica, but "`Schematic`" is a pretty good hint.

**Comment by maruohon** [comment]
I'm assuming you have the Generic -> `debugLogging` option enabled then?

**Comment by Fabian42** [comment]
Oh… yes! :D

I turned it off now. Is it intended with that setting? It seems pretty spammy regardless, it's about 99% of all log output.

**Comment by maruohon** [comment]
That particular message happens any time there is a block update packet from the server. Be glad you (presumably) didn't run a world eater or tree farm with that debug option enabled... :p

As for whether it's intended... yes? It's a debug message I added at some point when there were some issues with the rendering not updating for some users. You are not meant to have the debug option enabled all the time. That being said at some point I do want to add some way to only enable particular debug messages and not always all of them at once.
