### ISSUE TITLE
entities disappear after a certain height

### ISSUE THREAD

**Issue by ElArmagedonZ** [maruohon/litematica#676]
first of all I am writing this with Google translator in case something is misspelled. 

When I paste a construction with entities when I raise them to height -48 onwards they disappear while the ones below this height are still visible. Is this a mistake? 

version 1.19.3

![2023-03-17_00 29 29](https://user-images.githubusercontent.com/128124396/225831764-e2a37640-430d-44cc-afe0-35997dd89644.png)
![2023-03-17_00 29 31](https://user-images.githubusercontent.com/128124396/225831768-8c28a903-a8af-4993-9f10-94691339ba1b.png)

![2023-03-17_00 44 40](https://user-images.githubusercontent.com/128124396/225832165-91a1654e-f746-4944-9704-775041f6e65f.png)
![2023-03-17_00 44 48](https://user-images.githubusercontent.com/128124396/225832169-8ed4e04e-8e78-4a95-a596-e76d0fd55d4b.png)

**Comment by gi-b716** [comment]
I'm also using Google Translate to write this text, there may be spelling mistakes
Litematica 1.19.2 also has this error.

**Comment by maruohon** [comment]
This was a bug in the 0.12.6 version for 1.19.2 and in the 0.13.1 version for 1.19.3. I now released 0.12.7 for 1.19.2 and 0.13.2 for 1.19.3 that have a fix for this bug. (And the 1.19.4 release also has the fix.)
