### ISSUE TITLE
changing alt + middle click to another hotkey

### ISSUE THREAD

**Issue by Periculum95** [maruohon/litematica#681]
Is it possible to change the default Hotkey in "Edit Schematic" from alt + middle click to something else?
I couldn´t find any possibility in the config file neither in the Hotkey section.
Also i had a look at the Wiki: https://github.com/maruohon/litematica/wiki/Schematic-Editing

**Comment by maruohon** [comment]
I think the hotkeys used for that are `toolSelectModifierBlock1` and `toolSelectElements`. I know the names aren't really that descriptive... The same keys are used for multiple things, so it kinda makes them hard to name so that it would be obvious.

**Comment by Periculum95** [comment]
Thanks, that was what i needed to change. By default alt + 3 in my case. (1.19.3)
Best Regards
