### ISSUE TITLE
When I open the litematica menu, my game crashes

### ISSUE THREAD

**Issue by Aksh124** [maruohon/litematica#693]
### Provide at least the following information
I'm playing on 1.19.4
* **Mod version: (litematica-fabric-1.19.4-0.14.3.jar) and malilib version: (malilib-fabric-1.19.4-0.15.3.jar) - Which **exact** mod version are you using?
* **A clear description of the issue** - I'm not a psychic, so you have to describe the issue thoroughly enough for me to be able to reproduce it **without knowing anything at all that is not described in the issue report**.

I am crashing when I try to open my litematica menu (with m) heres my other mods (reference attached)
<img width="242" alt="image" src="https://user-images.githubusercontent.com/20526095/233817058-7f5a68b4-5f32-491b-b373-045054480673.png">
Note: the reason litematica is unchecked is because I am not playing with it right now.

here is the log aswell: https://paste.ee/p/ffTWv

**Comment by maruohon** [comment]
Closing as this was already answered in Discord - it was the FreeLook mod causing the crash.
