### ISSUE TITLE
Crash issue for Nvidia graphics card 531.68

### ISSUE THREAD

**Issue by eunjiMC** [maruohon/litematica#698]
Minecraft crashes with the latest version of graphics card driver, latest version of fabric, latest version of light metica mode and mailib applied.

**Comment by kosma** [comment]
Post your mod list and the crash log.

**Comment by eunjiMC** [comment]
fabric-api-0.79.0+1.19.4
malilib-fabric-1.19.4-0.15.3
litematica-fabric-1.19.4-0.14.3
tweakeroo-fabric-1.19.4-0.16.0

error
The game crashed whilst unexpected error
Error: java.lang.NoSuchFieldError: PLACEMENT_REPLACE_BEHAVIOR

Minecraft turns on, but exits when you enter the world

crash reports
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-05-02 20:53:38
Description: Unexpected error

java.lang.NoSuchFieldError: PLACEMENT_REPLACE_BEHAVIOR
	at fi.dy.masa.litematica.schematic.placement.SchematicPlacementManager.processQueuedChunks(SchematicPlacementManager.java:191)
	at fi.dy.masa.litematica.scheduler.ClientTickHandler.onClientTick(ClientTickHandler.java:32)
	at fi.dy.masa.malilib.event.TickHandler.onClientTick(TickHandler.java:36)
	at net.minecraft.class_310.handler$zlg000$malilib$onPostKeyboardInput(class_310.java:7015)
	at net.minecraft.class_310.method_1574(class_310.java:1958)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fi.dy.masa.litematica.schematic.placement.SchematicPlacementManager.processQueuedChunks(SchematicPlacementManager.java:191)
	at fi.dy.masa.litematica.scheduler.ClientTickHandler.onClientTick(ClientTickHandler.java:32)
	at fi.dy.masa.malilib.event.TickHandler.onClientTick(TickHandler.java:36)
	at net.minecraft.class_310.handler$zlg000$malilib$onPostKeyboardInput(class_310.java:7015)

-- Affected level --
Details:
	All players: 1 total; [class_746['EunJi1'/83, l='ClientLevel', x=56.62, y=-37.64, z=3.28]]
	Chunk stats: 1089, 450
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 11669 game time, 11669 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/123.zip, file/32x32겉날개.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 690185664 bytes (658 MiB) / 1409286144 bytes (1344 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2225
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 55162.35
	Virtual memory used (MB): 11246.65
	Swap memory total (MB): 38912.00
	Swap memory used (MB): 151.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.79.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.24+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.25+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.7+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.6+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.34+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.15+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.27+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.6+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.44+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.54+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.9+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.1+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.15+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.0+6cebf059f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.45+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.13+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.43+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.52+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.33+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.17+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.5+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.33+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.31+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.15+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.27+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.31+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.1+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.39+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.30+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.1+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.41+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.3+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.23+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.8+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.0+670e8ac6f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.5+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.1+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.38+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.28+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.21+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.41+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.1+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.1+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.2+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.45+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.20+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.9+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.1+da9bb835f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.3+63b515f4f4
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.14.3
		malilib: MaLiLib 0.15.3
		minecraft: Minecraft 1.19.4
		tweakeroo: Tweakeroo 0.16.0
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 522.25, NVIDIA Corporation
	Window size: 1366x719
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast

	Current Language: ko_kr
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['null'/83, l='ServerLevel[new world]', x=56.62, y=-37.64, z=3.28]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	
	nvidia driver versoin: 522.25  downgraded

**Comment by maruohon** [comment]
I have no idea how this crash is possible. It's like you somehow don't have the new `Configs` class version that is in the 0.14.3 version. Have you tried re-downloading the Litematica mod file? Or can you send the MD5 and/or SHA-1 checksum of the Litematica mod file you have currently?

**Comment by kosma** [comment]
I would suggest redownloading the mods, as something is very obviously very very wrong with our Minecraft installation...

**Comment by eunjiMC** [comment]
You have successfully downloaded a new. Thank you. It works fine. But I couldn't apply the Korean patch lang, configurs, and hotkey files that I modified. The error is probably due to this. Is there a way for me to modify this mod to Korean and use it?

**Comment by maruohon** [comment]
Nice that you didn't mention originally that you had modified the mod jar... presumably by copy pasting the modified class file from a previous mod version >_>
The 0.14.3 version added one new config option, so your old class file didn't have it, and then the code that tried to access that new config didn't find it and just crashed.

If you want the localizations then you need to recompile the mod with those localizations added to the new source code.

**Comment by eunjiMC** [comment]
I see. Thank you I want to make ko_kr recognized, where in the source is it possible? I understand that the basic is en_us, and there is also Russian language in it

**Comment by maruohon** [comment]
You can add non-config localizations (for menu buttons and texts and all the in-game messages etc.) to a lang file and make a resource pack out of it, and then load it as usual via the resource pack system in the game.

But unfortunately the current mod versions don't have localization keys for the config names and config tooltips/hover info. If you want to localize those, then you need to edit the mod source code and build a custom version of the mod.

The newer development code (currently only in 1.12.2) has all the config names and comments also in the lang file. So once that gets released at some point, then you can localizeeverything simply via a lang file in a resource pack.

Edit: For the config names and comments, you need to edit the `src/main/java/fi/dy/masa/litematica/config/Configs.java` file. You should then also edit the `gradle.properties` file and change the mod version, for example to something like `0.14.3-kr.1` so that you (and especially me, if someone would report an issue with that mod version) can see that it's a modified mod version.

And then to build the mod you need to have Java 17 JDK installed, and then you run the `gradlew build` command in a terminal inside the mod repo main directory. The built mod jar will be in `build/libs/`.

**Comment by eunjiMC** [comment]
Aha, I understand everything. There was an error because there was a change. Do you happen to know how to localize the language of mods through resource packs? I'm new to Resource Pack, so I'm not used to using Resource Pack to change the language of the existing mode

**Comment by maruohon** [comment]
Check the Minecraft wiki about how resource packs work. Basically you just need to create a specific directory structure, put the lang file there in the correct place (`assets/litematica/lang/en_us.json` for English), and add the `pack.mcmeta` file, and then create a zip archive of the directory structure. You can get the original (usually `en_us`) lang file from the mod jar file or from the source code repository. In this case you can grab it from this GitHub repo, just make sure to look in the `pre-rewrite/fabric/1.19.x` branch. Copy it as `ko_kr.json` or whatever the correct code is in your case, and then just replace all the English text with your translations.

**Comment by eunjiMC** [comment]
Thank you very much. It helped me a lot. That's really sweet of you. He's a good developer
