### ISSUE TITLE
Schematics not rendering above Y:256

### ISSUE THREAD

**Issue by czartrak** [maruohon/litematica#707]
I am playing on a server hosted on 1.19. I am using MaLiLib version 1.19.0-0.13.0 and Litematica version 1.19.0-0.12.1. I placed a schematic in the nether, and tried to raise it to proper height, but it would just stop rendering at 256

**Comment by maruohon** [comment]
Isn't the nether y range still only 0 - 255?

**Comment by czartrak** [comment]
Shoot, I didnt even know the nether had a lower build limit
