### ISSUE TITLE
[1.12.2] Crash with VBOs enabled when finishing loading schematics

### ISSUE THREAD

**Issue by HowardZHY** [maruohon/litematica#715]
### Provide at least the following information
* **Minecraft version** - Which Minecraft version are you playing on?
1.12.2

* **Mod version and malilib version** - Which **exact** mod version are you using?
Malilib 0.54.0
Litematica 0.31.3

[debug-1.log.gz](https://github.com/maruohon/litematica/files/11756820/debug-1.log.gz)

**Comment by HowardZHY** [comment]
bump

**Comment by maruohon** [comment]
The log you posted seems to contradict the description in the issue title. In the log the game seems to crash on launch because the latest LiteLoader malilib versions won't work with Forge anymore because of a mixin conflict due to some Forge changes to vanilla code.

Also what/where do you mean "FBO enabled"?

So for now you will have to use the 1.12.2 Forge versions of the mods, although they are currently based on a lot older code. And additionally you probably need to use this "nomixin" version of malilib since you have other mods that use Mixins: https://modrinth.com/mod/malilib/version/0.10.0-dev.23.nomixin

**Comment by HowardZHY** [comment]
> The log you posted seems to contradict the description in the issue title. In the log the game seems to crash on launch because the latest LiteLoader malilib versions won't work with Forge anymore because of a mixin conflict due to some Forge changes to vanilla code.
> 
> Also what/where do you mean "FBO enabled"?
> 
> So for now you will have to use the 1.12.2 Forge versions of the mods, although they are currently based on a lot older code. And additionally you probably need to use this "nomixin" version of malilib since you have other mods that use Mixins: https://modrinth.com/mod/malilib/version/0.10.0-dev.23.nomixin

Sorry I had a typo, it's Use VBOs in video settings

**Comment by HowardZHY** [comment]
And this is the correct crash log: https://mclo.gs/6l73mJ0, it happen also without OptiFine.

**Comment by HowardZHY** [comment]
> The log you posted seems to contradict the description in the issue title. In the log the game seems to crash on launch because the latest LiteLoader malilib versions won't work with Forge anymore because of a mixin conflict due to some Forge changes to vanilla code.
> 
> Also what/where do you mean "FBO enabled"?
> 
> So for now you will have to use the 1.12.2 Forge versions of the mods, although they are currently based on a lot older code. And additionally you probably need to use this "nomixin" version of malilib since you have other mods that use Mixins: https://modrinth.com/mod/malilib/version/0.10.0-dev.23.nomixin

[renderer.zip](https://github.com/maruohon/litematica/files/14157355/renderer.zip)

Here's my EntityRenderer.class mixin debug output of the crash above, idk why it didn't crash on startup with this instance

**Comment by maruohon** [comment]
Disable Render Regions in Optifine.

I don't know how you got the game to launch with the LiteLoader mod version in that above log... for me the recent LiteLoader malilib versions won't apply one of the mixins when Forge is present.

So you should rather use the Forge versions of the mods, even though they are much older atm: https://masa.dy.fi/mcmods/client_mods/

**Comment by HowardZHY** [comment]
> Disable Render Regions in Optifine.
> 
> I don't know how you got the game to launch with the LiteLoader mod version in that above log... for me the recent LiteLoader malilib versions won't apply one of the mixins when Forge is present.
> 
> So you should rather use the Forge versions of the mods, even though they are much older atm: https://masa.dy.fi/mcmods/client_mods/

That works, I'm dumb 'cause didn't realize how Optifine breaks that
