### ISSUE TITLE
Easy place direction isn't working with scarpet mod on fabric server

### ISSUE THREAD

**Issue by MightyPiggie** [maruohon/litematica#717]
Hey, I am on the latest version of litemetica, fabric and carpet mod. On my own server. Previously on 1.19.4 when I toggled the placementRotationFix on in carpet mod it worked amazing. However since the latest version it just won't place the block at al anymore. Also turning it off, will also prevent it from placing it at all. In single player it work's without any issues. So I think the problem might be carpet mod but not sure.

**Comment by adilrepas** [comment]
you need carpet extra mod and enable accurate block placement
accurateBlockPlacement true

**Comment by MightyPiggie** [comment]
> you need carpet extra mod and enable accurate block placement
> accurateBlockPlacement true

Oh yeah, I totally forgot. Thank you!
