### ISSUE TITLE
Fabric Mod Cannot be loaded

### ISSUE THREAD

**Issue by 3FeetHigh** [maruohon/litematica#72]
[latest.log](https://github.com/maruohon/litematica/files/3563263/latest.log)

Not sure what's happening here, have fabric api and malilib installed, both current versions.

**Comment by Solly-W** [comment]
This is a fabric mod, not a forge mod. You cannot load fabric mods on forge.

**Comment by 3FeetHigh** [comment]
I just realized that whoops
