### ISSUE TITLE
Minecraft Litematica not working when pressing M

### ISSUE THREAD

**Issue by kfs070310** [maruohon/litematica#722]
Hello i am just trying to put a schematic and when i press M its not popping up the menu so i cant do anything Also im on the 1.20 version of litematica

**Comment by vacla** [comment]
Try pressing , that might work

**Comment by kfs070310** [comment]
> Try pressing , that might work

didnt work :(

**Comment by maruohon** [comment]
Check on the F3 screen, do you see the orange Litematica text on the left, i.e. is the mod installed and running?

If it is, then you can access the config menu via the mod list of the Mod Menu mod to check or change your hotkey to open the Litematica main menu.

If you don't see the text, then either Litematica is not installed (to the correct MC instance), or you don't have the Fabric loader installed on that instance (shown on the top of the F3 screen).

![image](https://github.com/maruohon/litematica/assets/2331050/33aa27b9-6eef-4b60-b66a-31e16af4b9e2)

**Comment by kfs070310** [comment]
i downloaded it straight from curseforge app and it fixed itself thanks
