### ISSUE TITLE
No replacement menu on stick

### ISSUE THREAD

**Issue by MrFoxykov** [maruohon/litematica#723]
![image (1)](https://github.com/maruohon/litematica/assets/92532906/b1826d1c-8e04-4c6b-a894-0ea04700ad08)
Replacement menu bug

**Comment by maruohon** [comment]
Replacement menu? Have you disabled the tool functionality with `M + T`?

**Comment by MrFoxykov** [comment]
> Replacement menu? Have you disabled the tool functionality with `M + T`?

Doesn`t works

**Comment by MrFoxykov** [comment]
i deleted all configs and it worked
