### ISSUE TITLE
MaterialListHudScale doesn't scale, it only changes position (pushes off screen)

### ISSUE THREAD

**Issue by Nakor101** [maruohon/litematica#726]
minecraft 1.20.1
fabric loader 0.14.21
fabric-api-0.84.0+1.20.1.jar
litematica-fabric-1.20.1-0.15.0.jar june 17 2023
malilib-fabric-1.20.1-0.16.1.jar jul 03 2023
tweakeroo-fabric-1.20.1-0.17.0.jar

MaterialListHudScale moves the material list. At scale 1.0 it is in the intended position. Increasing the scale moves it up and left. Decreasing it moves it right and down. The material list will move off-screen without changing size.

Also happening for my wife with the same mods on her computer.

![1 0](https://github.com/maruohon/litematica/assets/39621131/7bb7286e-f03e-427b-8d6e-3d759c97567f)
![0 7](https://github.com/maruohon/litematica/assets/39621131/792a76fb-02ae-4c8b-b038-c1084537f21a)
![1 5](https://github.com/maruohon/litematica/assets/39621131/c401b843-bdcd-4576-942c-f3cfa185fa3f)

**Comment by maruohon** [comment]
This was fixed in version 0.15.3.
