### ISSUE TITLE
Litematica not showing schematica properly

### ISSUE THREAD

**Issue by schomm** [maruohon/litematica#73]
I put the schematica file in the schematics folder, run litematica, try to load the schematic but it doesnt show the correct blocks at all and instead just fucks me over, I'm super pissed right now since this has completely ruined my project, the fucking schematic shows completely different blocks than it should and tons of blocks are missing, this happened after I reset my computer and then re-installed schematica as normal. Super fucking pissed and I really want this issue resolved.

**Comment by vacla** [comment]
Download latest version of Litematica here where it is implemented https://masa.dy.fi/tmp/minecraft/mods/client_mods/

**Comment by schomm** [comment]
where what is implemented? is this just some spam?

**Comment by vacla** [comment]
for which version is it first of all, forgot to ask, and no this is not some spam, just trying to help

**Comment by schomm** [comment]
1.14, fabric only exists for 1.14 right

**Comment by vacla** [comment]
yeah, so download from the site i send the 1.14 version, fabric exists for 1.14.x - 1.15 but there are only 1.14.x mods for fabric

**Comment by schomm** [comment]
before i do this, what version of fabric is the best
should i go to vanilla then just download the latest

**Comment by schomm** [comment]
and also, are there any mods required along with litematica like malib

**Comment by vacla** [comment]
Which version do you need it for? You need MaliLib only for Litematica.

**Comment by schomm** [comment]
1.14.4, downloaded the newest version of it
gonna download litematica and malilib in a sec and yes i know what to do next

**Comment by schomm** [comment]
ill let you know if i get lost

**Comment by schomm** [comment]
uhh my litematica file isnt turning into a java file??

**Comment by maruohon** [comment]
Litematica requires malilib, nothing else (except the Fabric loader obviously (on 1.14+) to load the mods).

```
it doesnt show the correct blocks at all and instead just fucks me over, I'm super pissed right now since this has completely ruined my project, the fucking schematic shows completely different blocks than it should and tons of blocks are missing
```

Please clarify. What did you use to create the schematic, or did you download it from somewhere? Is it a Schematica or MCEdit schematic from 1.12 or before, using the `*.schematic` file name extension?

And as a side note, venting in the issues doesn't help anything. I just had some "news" IRL today that have me boiling already, if you start to vent here I'm going to completely fucking lose it and no good things will happen after that.

**Comment by maruohon** [comment]
And support for loading old `*.schematic` files on the 1.13+ versions of Litematica is under work, the link @vacla posted above contains my latest development builds, that are often newer than the versions on CurseForge. And since this old schematic loading support isn't yet completely finished, I haven't unloaded these builds to CurseForge yet.

**Comment by schomm** [comment]
Okay so, my litematica file didn't turn into a java file and it didnt give me the option to make it into one either, help?

**Comment by vacla** [comment]
did you downloaded the jar and put in mods folder @schomm ?

**Comment by schomm** [comment]
uhh im redownloading everything rn and just downloaded litematica, havent put anything in the mods folder yet

**Comment by maruohon** [comment]
`didn't turn into a java file` what the hell does that even mean? What are you trying to do currently?

You just put the malilib and litematica jar files you download from the link posted above, into the `.minecraft/mods/` directory. After that, assuming you have the Fabric loader installed to your Minecraft launcher, the mod should just work. You put the schematic files into the `.minecraft/schematics/` directory and that's it.

**Comment by schomm** [comment]
I've uninstalled every program and reinstalled them in a like fifth attempt to make this work, I'm in the process testing if it works now.

**Comment by vacla** [comment]
Why do you think it is not working?

**Comment by schomm** [comment]
Wish I could tell you

**Comment by vacla** [comment]
if it works, it should say Litematica in you F3 screen.

**Comment by schomm** [comment]
Oh my god, litematica isnt even working at all anymore

**Comment by schomm** [comment]
i wanna stab someone rn

**Comment by vacla** [comment]
show what is in your Mods folder

**Comment by schomm** [comment]
![folder](https://user-images.githubusercontent.com/54741506/64078588-d9c5c880-ccdc-11e9-81e9-8545ffb06c75.png)

**Comment by vacla** [comment]
you downloaded the wrong version of malilib and litematica, scroll down on the page i gave earlier and download those

**Comment by schomm** [comment]
what versions wshould i download

**Comment by maruohon** [comment]
You currently have the LiteLoader versions for Minecraft 1.12.0. You said you are on Minecraft 1.14.4, so scroll down on the page to the 1.14.4 Fabric section.

**Comment by vacla** [comment]
if you use fabric for 1.14.4, download for those for 1.14.4, if you use 1.14 download for 1.14, is self explanatory

**Comment by schomm** [comment]
Oh god I'm a fucking idiot, sorry, didn't even read the label lmao

**Comment by schomm** [comment]
Now my game is constantly crashing

**Comment by vacla** [comment]
crashlog ?

**Comment by schomm** [comment]
Didn't get a crashlog
Just says an unexpected error occured and the game crashed and a slap in the face with a shit covered hand

**Comment by vacla** [comment]
do you have fabric 1.14.4 as profile and both malilib and litematica as 1.14.4 mods downloaded?

**Comment by schomm** [comment]
I have the 1.14.4 fabric-loader aswell as malilib and litematica downloaded

**Comment by schomm** [comment]
![fffff](https://user-images.githubusercontent.com/54741506/64078684-e1d23800-ccdd-11e9-82d1-86d7506930c9.PNG)

**Comment by vacla** [comment]
can you send screenshot of your launcher profile?

**Comment by schomm** [comment]
![loader](https://user-images.githubusercontent.com/54741506/64078699-18a84e00-ccde-11e9-9d42-cf90e0950db8.PNG)

**Comment by vacla** [comment]
you download the 1.14.0 version of litematica and malilib not for 1.14.4

**Comment by schomm** [comment]
i want to fucking die

**Comment by schomm** [comment]
Game didn't crash now, gonna check if litematica will open

**Comment by schomm** [comment]
litematica works

**Comment by schomm** [comment]
schematic works

**Comment by schomm** [comment]
thannk
fucking
god

**Comment by schomm** [comment]
Alright, thanks for not having a mental breakdown due to my stupidity, have a good day.

**Comment by rebane2001** [comment]
you sure had one

**Comment by schomm** [comment]
ayee, i was actually working on mapart, what a surprise to see you here
