### ISSUE TITLE
Latest version does not show the notice board text

### ISSUE THREAD

**Issue by fgr178707** [maruohon/litematica#731]
Latest version 1.20 client read
The previous projection file notice board does not display text

![image](https://github.com/maruohon/litematica/assets/109357981/1582f39f-850d-4479-a8ae-708bc89ac801)

**Comment by maruohon** [comment]
Are you using Litematica **0.15.3**? That version was supposed to have a sign NBT data updater from pre-1.20 format.

**Comment by fgr178707** [comment]
> Are you using Litematica **0.15.3**? That version was supposed to have a sign NBT data updater from pre-1.20 format.

I am using the latest version, 0.15.3

**Comment by maruohon** [comment]
Can you send me that schematic? I must have missed something in the code then...

**Comment by fgr178707** [comment]
> Are you using Litematica **0.15.3**? That version was supposed to have a sign NBT data updater from pre-1.20 format.

NBT data updater?  
How do I proceed?

**Comment by fgr178707** [comment]
> Can you send me that schematic? I must have missed something in the code then...


[Alpha＆大叔袭击塔430K收集 by：EnderCuber.zip](https://github.com/maruohon/litematica/files/11980210/Alpha.430K.by.EnderCuber.zip)

You need to decompress the notice board inside is Chinese

**Comment by maruohon** [comment]
Are you sure you have version 0.15.3? Because it seems to be working for me.

![image](https://github.com/maruohon/litematica/assets/2331050/ceaeaa4e-7b45-4e57-a3d7-414d55eca8b8)

**Comment by fgr178707** [comment]
> Are you sure you have version 0.15.3? Because it seems to be working for me.

![image](https://github.com/maruohon/litematica/assets/109357981/16e213cc-2052-4b82-87ba-88acd8e8a21d)

I'm sure I'm using 0.15.3 Could it be a problem with my game version?
My current version of the game is 1.20
The module seems to be 1.20.1
I thought these two versions said the modules were common?

**Comment by maruohon** [comment]
I have no idea what this is showing. Check the Litematica mod version, for example in the title of the Litematica main menu. The 0.15.3 mod version was released 2 days ago.

**Comment by fgr178707** [comment]
> I have no idea what this is showing. Check the Litematica mod version, for example in the title of the Litematica main menu. The 0.15.3 mod version was released 2 days ago.

Please check this file to see if there is any text here Chinese
[白桦树厂.zip](https://github.com/maruohon/litematica/files/11981268/default.zip)
![image](https://github.com/maruohon/litematica/assets/109357981/0d143a5e-05e9-4f00-be14-eefad8810884)

**Comment by fgr178707** [comment]
The last file I redid a client, normal
and then copied it to another client
This one I did not work as above, but it still does not display
The main menu does show 0.15.3 in the title

**Comment by fgr178707** [comment]
> The last file I redid a client, normal and then copied it to another client This one I did not work as above, but it still does not display The main menu does show 0.15.3 in the title

![image](https://github.com/maruohon/litematica/assets/109357981/84690ad5-9b20-4839-a01c-a7aff501300e)
The left game version 1.20 The right game 1.20.1
Module versions are 0.15.3 loaded with the same projection file
What I suspect is that my front module may not have been updated to cause problems

**Comment by fgr178707** [comment]
I seem to know what's going on. I tried lowering 1.20.1 back to 1.20 and then the notice board stopped displaying text. 
Game version 1.20.1->1.20
Module version 0.15.3

**Comment by maruohon** [comment]
How did you even make that second schematic? It has the MC data version of 1.20 but the sign data is in the pre-1.20 format...

But yes indeed looks like the sign text does not work in 1.20 even with the 0.15.3 mod version. No idea why. But I'm not supporting 1.20 anymore anyway, just update to 1.20.1. You should even be able to play on 1.20 servers with a 1.20.1 client game version, if needed.

**Comment by fgr178707** [comment]
> How did you even make that second schematic? It has the MC data version of 1.20 but the sign data is in the pre-1.20 format...
> 
> But yes indeed looks like the sign text does not work in 1.20 even with the 0.15.3 mod version. No idea why. But I'm not supporting 1.20 anymore anyway, just update to 1.20.1. You should even be able to play on 1.20 servers with a 1.20.1 client game version, if needed.

The second diagram is a local multi-drive
If 1.20 is not supported, I tried to upgrade to 1.20.1
This is the only solution for now Thanks
