### ISSUE TITLE
Litematica causes replays by ReplayMod to lose the outer layer of a skin

### ISSUE THREAD

**Issue by SurpriseTea** [maruohon/litematica#77]
The said bug present only in multiplayer (including pure vanilla server) and only if litematica mod is present. The presence or absence of the malilib or other your mods doesn't affect the results.

**Comment by maruohon** [comment]
Does the issue disappear if you toggle off the Litematica main rendering (`M + R`) or just the schematic rendering (`M + G`) or just the block rendering using the unbound `toggleSchematicBlockRendering` hotkey? Do you use the translucent rendering? Does it also happen if you disable `betterRenderOrder` in Generic?

**Comment by SurpriseTea** [comment]
Nothing helped. I've tried before recording, in the process, before watching, after watching, but nothing helped.

**Comment by SurpriseTea** [comment]
Also, that loss is tied to the replay itself and don't go away once litematica is removed after the recording.

**Comment by maruohon** [comment]
uhhh what? O_o How is that even possible...

**Comment by SurpriseTea** [comment]
I guess litematica messes up with how replaymod _reads_ skins, because skins are saved inside the replay file.

**Comment by maruohon** [comment]
Oh are they? Well then it would make more sense. However Litematica should have nothing at all to do with player skins or player rendering. I assumed it was just the replay mod rendering being broken while playing back, if Litematica is present and the rendering is active, as that's still the only thing that would make sense to me.

**Comment by SurpriseTea** [comment]
Okay, nevermind, it was just a coincidence, replaymod's own bug was accidentally correlating with me removing the litematica %)

**Comment by maruohon** [comment]
I assume the latest response means this was just a ReplayMod bug.
