### ISSUE TITLE
Ctrl+Scroll on Linux

### ISSUE THREAD

**Issue by ilobilo** [maruohon/litematica#771]
* **Minecraft version** - 1.20.1
* **Mod version and malilib version** - 0.15.3 and 0.16.3
  * litematica-fabric-1.20.1-0.15.3.jar
  * malilib-fabric-1.20.1-0.16.3.jar
* **A clear description of the issue** - Ctrl+Scroll or Alt+Scroll doesn't work with (selection?) stick, it simply changes the current selected hotbar slot.

**Comment by ilobilo** [comment]
I just tested and I can't area select eather. Maybe it's just a config issue?

**Comment by maruohon** [comment]
Do you see the tool HUD in the bottom left when you hold the "tool item"? If not, then you have either disabled the tool item functionality (`M + T`) or the mod main rendering option (`M + R`), or you are not holding the item configured as the tool (Generic -> `toolItem`). Also note that the item currently (in the current 1.13+ mod versions) can't have any NBT data.

**Comment by ilobilo** [comment]
yes I can see the tool HUD and i used ``/give stick``

**Comment by maruohon** [comment]
Check if your `operationModeChangeModifier` hotkey is still set to left Ctrl (that's the "modifier" hotkey for changing the mode while scrolling). And `selectionNudgeModifier` for the left Alt + scroll corner/area/placement nudging.

**Comment by ilobilo** [comment]
That was the issue, thanks! I don't know how they got reset to none
