### ISSUE TITLE
Game crashed 

### ISSUE THREAD

**Issue by ArchAzraeI** [maruohon/litematica#78]
Loaded in a litematic, even saw the outline of what I had to build. But after a few seconds the game crashed, and every time i reload the world, it crashes within a few seconds. This is the game crash message: 

The game crashed whilst unexpected error
Error: java.nio.BufferOverflowException

Any help would be appreciated, thank you.

**Comment by maruohon** [comment]
Pastebin the full crash log please, that doesn't tell me anything yet really.

**Comment by ArchAzraeI** [comment]
Since I'm a retard I deleted both litematica and malilib's jar files so I could play the game, and I lost the crash log. However after seeing your reply I restored them from the recycling bin to see if I could get the crash to occur again. But for some reason everything's working fine now :/

If anything changes I'll let you know, I'm so so sorry for wasting your time on this with my stupidity. Please have a good night.

You can close this issue, and again I'm terribly sorry.

**Comment by vacla** [comment]
there should be a crashlog in ./minecraft/crash-reports/

**Comment by ArchAzraeI** [comment]
Not sure if this is what you meant by pastebin, just googled it and this is the download it gave me. Hope this helps, thank you Vacla

[minecraft_crash_report.txt](https://github.com/maruohon/litematica/files/3599345/minecraft_crash_report.txt)

**Comment by maruohon** [comment]
I think this might have been caused by Optifine. If you didn't solve it yet, then try disabling the Render Regions option in Optifine (which also breaks the rendering anyway...).

**Comment by vacla** [comment]
issue was resolved on Discord
