### ISSUE TITLE
Tool scroll not working despite Tool and all Renders being on

### ISSUE THREAD

**Issue by DragonFighterer** [maruohon/litematica#786]
It just scrolls through my hotbar if thats relevant
(the little box on the left is showing up)

**Comment by maruohon** [comment]
If the tool HUD is visible while holding the item, then check the `operationModeChangeModifier` hotkey, is it still set to left Ctrl? Also if the "advanced settings" widget for it has an orange outline indicating that it has been modified, then reset it to the defaults by right clicking it.
