### ISSUE TITLE
How do I load schematics to litematica?

### ISSUE THREAD

**Issue by eewalktub** [maruohon/litematica#79]
I have the schematic downloaded and the mods is running and all is fine but how do i actually load the schematic so that i can place it somewhere. I can;t find a tutorial please help.

**Comment by vacla** [comment]
here is an tutorial how to do it: https://old.reddit.com/r/Minecraft/comments/cqdmkk/anyone_can_help_me_how_do_i_make_schematics_with/exeug78/
