### ISSUE TITLE
1.20.2 game crashes when clicking on area editor (litematica)

### ISSUE THREAD

**Issue by Aeyth0** [maruohon/litematica#799]
Minecraft Version: 1.20.2
Mod version: fabric-1.20.2
Malilib version: malilib-fabric-1.20.2-0.17.0
litematica-fabric-1.20.2-0.16.0
Description of Issue: Whenever I click on area editor, my screen immediately goes to saving world... and then my game crashes.

**Comment by vacla** [comment]
Can you please provide the crashlog?

**Comment by Aeyth0** [comment]
I figured out the problem, thanks anyways.

**Comment by maruohon** [comment]
What was the problem?

**Comment by Aeyth0** [comment]
I was using litematica on fabric with a different client, when I used on normal minecraft launcher it worked and didn't crash.
