### ISSUE TITLE
it crash instantly, no crash report

### ISSUE THREAD

**Issue by satoru101** [maruohon/litematica#80]
i'm on 1.13.2 and use Rift, did download MaLiLib, only litematica and MaLiLib. but when start it instantly crash, i check the crash report and go no new file, i tried again this time with out the mods to see if it the API, but it ran normally, so i think it must be the mods, again i use Rift 1.13.2  and did download the required mod for litematica.

**Comment by vacla** [comment]
what does the crash say on the launcher?

**Comment by maruohon** [comment]
I assume you are using Litematica version `litematica-rift-1.13.2-0.0.0-dev.20190611.200317.jar`, which is the latest on CurseForge? Then you must use malilib version `malilib-rift-1.13.2-0.10.0-dev.19.jar`, otherwise you will get a crash due to mismatching code between the mods.

**Comment by vacla** [comment]
Also if check if there is an file in `%appdata%\.minecraft\libraries\com\github\Chocohead\Rift\jitpack-SNAPSHOT`, otherwise check for the fix in the faq of litematica

**Comment by vacla** [comment]
@satoru101 did you get it working?

**Comment by satoru101** [comment]
yes it work thank so much
