### ISSUE TITLE
Litematica files wont work

### ISSUE THREAD

**Issue by Cheefu** [maruohon/litematica#81]
A few of my Litematica files won't work after I extracted them from the bowels of deleted files. the reason for this is obvious, but I don't know how to get back my original litematica files.
![2019-09-23_20 41 52](https://user-images.githubusercontent.com/53386388/65473085-5cf1be80-de44-11e9-8cf7-01b0c54a98c1.png)
![2019-09-23_20 37 16](https://user-images.githubusercontent.com/53386388/65473089-5e22eb80-de44-11e9-826d-8f7e6a60ac1e.png)

**Comment by Cheefu** [comment]
I can send them over if anyone wants to tinker with them, as they are no good to me.

**Comment by maruohon** [comment]
I'm closing this as this is not an issue in the mod, if the files were simply corrupted externally.
