### ISSUE TITLE
x或z轴的单层显示

### ISSUE THREAD

**Issue by Adogs1** [maruohon/litematica#811]
I hope to add a function similar to rendering a single-layer projection at a specified height in the x-axis or z-axis direction, because some machines require horizontal construction, having a single-layer projection on the x-axis or z-axis will be much more convenient!!

**Comment by maruohon** [comment]
It has always been there:
![image](https://github.com/maruohon/litematica/assets/2331050/7ddf9ebb-b4c0-4929-beaa-a62194615755)

**Comment by Adogs1** [comment]
Thank for your help！
