### ISSUE TITLE
Schematic not loading

### ISSUE THREAD

**Issue by hidebuff** [maruohon/litematica#812]
I recently installed litematica for my bigger builds and machines, but I ran into an issue. Every schematic I use just appears as one block and idk how to fix it.

![2024-02-01_17 38 27](https://github.com/maruohon/litematica/assets/158531157/bfaf46f5-117f-45d2-bdcd-dcd93d222a74)

**Comment by maruohon** [comment]
It says `Regions: 0`, so it was either generated or saved incorrectly. It doesn't contain any sub-regions and thus it doesn't have blocks. Also the name seems to be empty (unless you renamed the placement).

Did you save this schematic, or download it from somewhere?

**Comment by hidebuff** [comment]
Alright I fixed the issue. I was renaming the file names to .litematic from .schem and that was corrupting the file in return, leaving me with no schematic. Thanks for the help!

**Comment by maruohon** [comment]
Ah. It doesn't really "corrupt" it, but Litematica currently assumes the file name extension indicates the schematic format, and it doesn't have a fallback "format snooper" yet. So if you change the file name extension then it doesn't recognize it as the format that it actually is, and thus it won't load it properly either.

This also affects a number of schematics downloaded from some web sites, as they may have them renamed for whatever reason (maybe the site doesn't allow the correct file name extension for example). And those then usually fail to load as-is.

In case you ever need it, here are a couple of "image guides" on how to tell the correct format, if you open the schematic file for example with NBTExplorer:
- https://i.imgur.com/Z1g8wL8.png
- https://i.imgur.com/F5HsuVn.png
