### ISSUE TITLE
Some litematic properties seem to be ignored

### ISSUE THREAD

**Issue by elegos** [maruohon/litematica#818]
* **Minecraft version** - 1.20.4 (with Fabric)
* **Mod version and malilib version** - Litematica 0.17.0 // malilib 0.18.1

I'm developing a grabcraft 2 litematic converter (mostly for fun), and I found out that either I messed up something, or the .litematic files have BlockStates with some properties that are being ignored by Litematica (or so it seems).

In particular, I tried to set the doors' `hinge` ('left' or 'right') and the bed's `part` ('head' or 'foot'), but they will default in-game (hinge left, part foot).

I wish I found a tool to read the block states of the created litematic, but I found none (maybe I could write one...). For now I attach the generated .litematic file (it's a small house, doors are on ground and first floor, beds on first floor).

Thank you for the support, either being mine or your bug :D

--> the schematic (zipped due to github restrictions) [Fantasy Town Small House 2.zip](https://github.com/maruohon/litematica/files/14285254/Fantasy.Town.Small.House.2.zip) <--

**Comment by maruohon** [comment]
In this particular case, if you have the blocks in the correct place but not in the correct state, then you are mostly interested in what you have in the palette. And thus simply using NBTExplorer to look at the schematic's NBT data is quite sufficient: https://github.com/jaquadro/NBTExplorer/releases

You seem to be missing most of the properties of at least some of the blocks.

For example the doors should normally have all these properties:
![image](https://github.com/maruohon/litematica/assets/2331050/d411d120-bdec-4f17-aed1-5195c6036647)

![image](https://github.com/maruohon/litematica/assets/2331050/27e511e1-bf40-4019-b305-119bccc17a49)


But in the schematic data, there are only 1 or 2 properties per block state for the doors:
![GH818_block_states_1](https://github.com/maruohon/litematica/assets/2331050/a851798c-1f50-4383-a228-194a3cfa3f03)
![GH818_block_states_2](https://github.com/maruohon/litematica/assets/2331050/3f042955-6bb6-43f3-925d-43f1e5f6367c)

**Comment by elegos** [comment]
According to https://minecraft.fandom.com/wiki/Block_states the missing props should default to the various values. In the screenshots though I see the doors without the hinge prop, for instance. I'll investigate it. Thanks for the tool :)

**Comment by elegos** [comment]
Ok, definitively was an issue with my tool not reporting the property.

Knowledge sharing: properties have all defaults, so if they're not all there, they're not invalid.
