### ISSUE TITLE
Entities from schematics do not paste because of incorrect command

### ISSUE THREAD

**Issue by BerdinskiyBear** [maruohon/litematica#83]
Pasting schematic into the world on the server will not summon entities and /summon commands will be not executed with an error like this:
![image](https://user-images.githubusercontent.com/56161020/66213120-53d8db00-e6e9-11e9-88be-c84347a5a998.png)
This error occurs if the system language is set to one that does not use a point (full stop) as a decimal separator, but Minecraft server always expects a decimal point regardless of the system language.
For example, this is what Litematica sends if system system language is set to Russian:
`/summon minecraft:hopper_minecart 12,500000 40,000000 99,500000`
but it is supposed to send this:
`/summon minecraft:hopper_minecart 12.500000 40.000000 99.500000`

idk if it is possible to make formatter ignore system language and always use point as decimal separator

**Comment by vacla** [comment]
@BerdinskiyBear which version are you using of litematica and minecraft?
does it work if you use it in english?

**Comment by maruohon** [comment]
Yes that will be an easy fix, those are just easy to miss/forget when first implementing things... Which Minecraft version are you on? Or I guess I should do quick temporary bugfixes for this on all versions, even though the "final fix" needs to be in 1.12 and will get merged forward when I have the time to do the next merges from 1.12 to 1.13.2 and then to 1.14.4

**Comment by BerdinskiyBear** [comment]
@vacla, yes, this feature works if system language is set to English

@maruohon, I am using 1.14.4 but I have been experiencing this issue on all versions since 1.13.2

**Comment by maruohon** [comment]
There are now fixed builds for 1.14.4 (and LiteLoader 1.12.0 and 1.12.2) here: https://masa.dy.fi/tmp/minecraft/mods/client_mods/?mcver=1.14.4

I'll leave the 1.13.2 fix for later, it will happen when I next merge the 1.12 code to 1.13.2.
