### ISSUE TITLE
Schematics not showing blocks properly in render

### ISSUE THREAD

**Issue by harryfrodsham** [maruohon/litematica#85]
Hi,

I'm trying to use the "hologram" render of the schematic, and it just appears as a blank box with nothing in it.

Yes, my schematic rendering is turned on and I am using the latest version of the mod (I installed it about 3 hours ago from posting this)

Any help on the matter would be appreciated.

Cheers

Edit: here is the picture, on the left you can see the schematic, and on the right is what i'm trying to render: 

https://imgur.com/a/aoBBRTm

**Comment by vacla** [comment]
did you load the schematic again at the left?

**Comment by SunSerega** [comment]
Try without optifine. There are some optifine settings (like shaders) that break rendering.
Also, go to setting menu (M+C by default) and look in layers tab.

**Comment by harryfrodsham** [comment]
I do not have Optifine and I have all layers on.

**Comment by harryfrodsham** [comment]
Vacla,the first time i placed it it was invisible.

**Comment by maruohon** [comment]
How high is that placement? If it goes over the world build height, it essentially won't exist in the schematic world. If that is not the issue, then try enabling the `statusInfoHud` option in the `Info Overlays` category (for a moment) to quickly see if something rendering related is toggled off.

**Comment by harryfrodsham** [comment]
Hi maruohon, it seems the reason it wasn't showing up is because the schematic was placed over the build height. Thanks for your help! 

(I can't believe it was such a simple error)

Cheers

**Comment by maruohon** [comment]
This tells me I need to add a warning message when this happens. :)
