### ISSUE TITLE
Certain Action Causes Loading World Crashes 1.21

### ISSUE THREAD

**Issue by burnt-bacon** [maruohon/litematica#859]
I'm using 1.21 Fabric API, Litematica, and MaLiLib, been learning the mod when some kind of action with the Litematica tool (stick) causes game to crash. It's usually either shift + m1 with the stick or double clicking m1 that has caused these issues, but I could be wrong. Trying to load back in (multiplayer or singleplayer) instantly displays "Saving World" and crashes. The worlds function as normal in a vanilla launch of minecraft.

The crash report is below:

[crash-2024-06-15_23.13.25-client.txt](https://github.com/user-attachments/files/15856167/crash-2024-06-15_23.13.25-client.txt)

Attempted fixes include restarting launcher, downloading Sodium 1.21 for fabric and turning down render distance to target rendering based issues, loading in on vanilla and moving the player and removing the stick before reloading in fabric. No success so far except one outlier where all placed and previewed schematics were absent, leading to an empty world.

**Comment by sakura-ryoko** [comment]
Upgrade your build of litematica and malilib, this error was fixed in sakura.2

**Comment by burnt-bacon** [comment]
Can't believe I didn't check for an updated build. sakura.2 fixed it, thank you for your help!
