### ISSUE TITLE
1.21 Scroll wheel not working

### ISSUE THREAD

**Issue by CreefYT** [maruohon/litematica#867]
**Minecraft version** - 1.21

**Mod version and malilib version** - litematica-fabric-1.21-0.18.999-sakura.12.jar & malilib-fabric-1.21-0.19.999-sakura.6

* **A clear description of the issue** - I have just installed these 2 versions of litematica and malilib and added them to my mods. Everything seems to be working fine apart from the scroll wheel. I can't use the scroll function for the commands. I tried with left CTRL and it didn't change tool modes. I also tried ALT with scroll wheel to move the schematic and it didnt work. It always just scrolls in the hotbar instead. I have googled this problem but I haven't find a solution for me in specific. When I have the stick in hand I see the tool mode in the bottom left and I'm on Windows 11 since I saw some problems on Mac. I tried using litematica once in 1.20 and I didn't have the problem then. I also tried removing all the other mods in my mod folder but that didn't work either.

**Comment by sakura-ryoko** [comment]
It seems like a configuration issue, as the scrolling tool modes works fine in my own testing.

**Comment by maruohon** [comment]
Check your `operationModeChangeModifier` hotkey, is it still bound to left Ctrl? That's the key you hold while scrolling to change the tool mode. Although if Alt + scroll nudge doesn't work either, then you would have multiple hotkeys unset for some reason...

**Comment by CreefYT** [comment]
> Check your `operationModeChangeModifier` hotkey, is it still bound to left Ctrl? That's the key you hold while scrolling to change the tool mode. Although if Alt + scroll nudge doesn't work either, then you would have multiple hotkeys unset for some reason...

Yes I checked that hotkey already. Also tried to change it to another and didn't work.

**Comment by maruohon** [comment]
How many other mods do you have, can you try without most other mods than the "masa mods" suite? It kind of sounds like it might be a conflict with the mouse scroll event handler with something, if all scrolling functionality is broken. That's assuming you do see the tool HUD when you are holding the item, like you mentioned you do.

Basically seeing the tool HUD while holding the item is an indication that the tool is enabled and recognized (assuming you are not in Schematic Edit mode, as in that mode it always shows), so the only remaining possibilities are the hotkey not being activated, or the scroll events just not firing. I assume other Litematica hotkeys still work, for example the main menu hotkey? So all hotkeys aren't broken?

**Comment by CreefYT** [comment]
> How many other mods do you have, can you try without most other mods than the "masa mods" suite? It kind of sounds like it might be a conflict with the mouse scroll event handler with something, if all scrolling functionality is broken. That's assuming you do see the tool HUD when you are holding the item, like you mentioned you do.
> 
> Basically seeing the tool HUD while holding the item is an indication that the tool is enabled and recognized (assuming you are not in Schematic Edit mode, as in that mode it always shows), so the only remaining possibilities are the hotkey not being activated, or the scroll events just not firing. I assume other Litematica hotkeys still work, for example the main menu hotkey? So all hotkeys aren't broken?

As I said in my first post, I tried removing all mods from the mods folder apart from litematica and malilib and still had the same problem. I can click M and go to the menu and swap tool modes through there so it is usable just really annoying not being able to use the scroll wheel with commands. It just scroll in the hotbar even to I press CTRL with the stick in hand when I see the overlay.

**Comment by sakura-ryoko** [comment]
Still, I cannot replicate the issue.  Tweakeroo, Lithium, and all installed.

**Comment by maruohon** [comment]
What are your mouse scroll settings set to in the vanilla controls menu? (sensitivity and is discrete scrolling enabled?)

**Comment by CreefYT** [comment]
> What are your mouse scroll settings set to in the vanilla controls menu? (sensitivity and is discrete scrolling enabled?)

![Screenshot 2024-07-04 012054](https://github.com/maruohon/litematica/assets/62450107/43068bdc-9192-4d7b-8e82-af92a36999b3)

discrete scrolling was disabled but turning it on didn't fix it

**Comment by maruohon** [comment]
Try enabling the `mouseScrollDebug` option in the malilib configs (`A + C`) and then do some scrolling up/down and post the debug output from the game console/log.

**Comment by CreefYT** [comment]
![grafik](https://github.com/maruohon/litematica/assets/62450107/f7345111-bb48-4bd0-ad47-84166aa5bccc)

Do you mean this?

**Comment by maruohon** [comment]
Yes, and that looks normal, malilib is receiving the scrolls and the amount is +/- 1.0 so it's fine there. So that just leaves either Litematica mouse scroll handler not being registered, or it still being a hotkey issue somehow. You haven't modified the advanced settings for those modifier hotkeys, right? The small colored widget next to the hotkey button, does it have a white or an orange outline? If it's orange, then right click it to reset it to the defaults.

**Comment by sakura-ryoko** [comment]
The settings that masa is referring to should match this screen shot:

![2024-07-04_11 48 38](https://github.com/maruohon/litematica/assets/116967773/38cd3eca-d74e-45c5-bce7-f85ab2bd1197)

If it does not, Right Click to set Defaults.

**Comment by CreefYT** [comment]
Alright,

for some reason every one of those squares wre turned orange and I don't know how that happened. I reset every setting and now it works! Thank you.
