### ISSUE TITLE
problem with loaded schematic in litematica

### ISSUE THREAD

**Issue by Walter736** [maruohon/litematica#868]
i got a issue with loaded litematica schematics in 1.21.

![Screenshot 2024-07-04 020327](https://github.com/maruohon/litematica/assets/174664084/5cd7efb8-744d-4504-86e6-1ebed3b020ee)
i play on litematica v0.18.999-sakura.11 and MaLiLib v0.19.999-sakura.6

**Comment by sakura-ryoko** [comment]
reload your sodium settings.  This is normal when upgrading versions of sodium and the settings change over.
