### ISSUE TITLE
1.21 Litematica (Sakura) easy place mode not working and if i set numpad key to keybind also doesnt work

### ISSUE THREAD

**Issue by harrrobe** [maruohon/litematica#871]
The title really explains it all i have made sure easy place mode is on

**Comment by sakura-ryoko** [comment]
Version, etc ?  Easy Place has been fixed a few different ways not long ago.

**Comment by harrrobe** [comment]
I literally downloaded it the day I sent it on the version marked "2 days ago" I'm pretty sure it was version 17 for 11.21
easy place mode toggle works but easy place mode itself doesn't
also if I assign the keypad to a hotkey it doesn't work

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sakura-ryoko** [comment]
Are you on a server ?  Easy Place Mode requires server side support

**Comment by harrrobe** [comment]
no this is my single player tester world I use for mods

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by sakura-ryoko** [comment]
What are your Easy Place Mode settings ?

Generally you'd want them to be like this:

![2024-07-12_10 40 47](https://github.com/user-attachments/assets/562bb7b0-2d65-4c5b-ac1b-a2bbc1cb152d)

**Comment by harrrobe** [comment]
they are default but easy_place_mode = true and easy place key bind is set to something+apostrophe

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sakura-ryoko** [comment]
Does your Advanced Keybind settings look like this ?

![2024-07-12_11 07 29](https://github.com/user-attachments/assets/15308974-7df3-42fe-972f-07b0cbb828cc)

If not, try Right Clicking to "set as defaults" for the keybind.

**Comment by harrrobe** [comment]
oh no it works now I set it to not the keypad as it says at the bottom "easy place mode = true" when I press apostrophe but with the keypad it doesn't do that

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sakura-ryoko** [comment]
Yes because `easyPlaceToggle` normally changes the behavior of the Vanilla 'BUTTON_2' aka your standard block placing button, and toggling it OFF means your back to using Vanilla mechanics.

**Comment by harrrobe** [comment]
well that isn't happening

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sakura-ryoko** [comment]
What is your Easy Place `USE` key binded to ?

**Comment by harrrobe** [comment]
I don't know I'll check when I get home

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sakura-ryoko** [comment]
OK, well whatever KEY you have it bound to, then you would need to `TOGGLE` Easy Place Mode ON, and then LOOK AT the block that you want to place in the Schematic; and then press the `USE` key, where at default is bound to `BUTTON_2`, aka your right Mouse Button.

**Comment by harrrobe** [comment]
I'm pretty sure it should be on its default because I definitely changed the one that said toggle easy mode instead of easy mode use but I'm not sure I should be home soon though

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by harrrobe** [comment]
> What is your Easy Place `USE` key binded to ?

ok so i updated to version 18 it still didnt work so i went into the keybind settings and saw easy place use was on none key which i didnt do so i set it to `BUTTON_2` And it worked 
also using the keypad for keybinds works now as well
