### ISSUE TITLE
A bug with the text

### ISSUE THREAD

**Issue by VonikGH** [maruohon/litematica#899]
Hello, how to fix this bug with text display
![изображение_2024-10-08_153145570](https://github.com/user-attachments/assets/ec576525-623d-4fc7-a80c-3bb6e529459b)

![изображение_2024-10-08_153130446](https://github.com/user-attachments/assets/2602f2ba-9ee4-4658-a993-e481c1ce22a9)

**Comment by VonikGH** [comment]
![изображение_2024-10-08_153346637](https://github.com/user-attachments/assets/fd58667c-75dc-43d2-8e64-d85e6fa03b01)

**Comment by sakura-ryoko** [comment]
you have either the wrong malilib installed; or something else messing with the lang files.

**Comment by VonikGH** [comment]
What are the lang files? I reinstalled the malilib library. Nothing has changed.
