### ISSUE TITLE
Schematic Overlay not properly rendering on 1.18.2 Fabric

### ISSUE THREAD

**Issue by mkdir-saint52** [maruohon/litematica#904]
Litemativa v.0.11.5
https://github.com/user-attachments/assets/2e46d309-a381-4c6c-a60f-378f402ccdf5

**Comment by maruohon** [comment]
Do you have Optifine or shaders on? Many shader packs mess with the overlay rendering.

**Comment by mkdir-saint52** [comment]
I have some mods installed to substitute some Optifine features on Fabric. I will try using litematica after uninstalling them. 

Thank you! :)
