### ISSUE TITLE
I changed a keybind to open the menu

### ISSUE THREAD

**Issue by Icebluewolf** [maruohon/litematica#91]
I changed a key bind to open the menu because it was conflicting other mods but now I don't know what it is. Is there a way to reset it or to find out what it is?

**Comment by vacla** [comment]
if it is for 1.14.x or higher, look in .minecraft/config/litematica.json, name of keybind should be something like the name of the menu

**Comment by maruohon** [comment]
Assuming you are on 1.14.4, in the September builds and later (from here: https://pena2.dy.fi/tmp/minecraft/mods/client_mods/) you can also use the Mod Menu mod to open the Litematica config GUI via the gear button in the Mod Menu GUI. In future versions of malilib there will also be a combined view of all hotkeys from the mods that use malilib's keybind system.

But currently, without Mod Menu, you'd have to look in the config file @vacla mentioned to see or change the current hotkey if you don't remember it and thus can't open either the Litematica main menu (`M`) or the config menu (`M + C`) directly.
