### ISSUE TITLE
Minecraft not starting - Fabric 0.16.9 tells me to get MaLiLib 0.22.1, latest is 0.22.0.

### ISSUE THREAD

**Issue by Skyguy7878** [maruohon/litematica#914]
Minecraft version - 1.21.3 Fabric 0.16.9 (Latest Fabric version)
Mod version and malilib version - Litematica 1.21.3-0.20.1, MaLiLib 1.21.3-0.22.0 (Both latest)
Description of the issue - Minecraft will not start with both of the mods in their latest versions installed. Fabric loader tells me to get what is past the latest version of MaLiLib (tells me to get 0.22.1, but the latest public version is 0.22.0. Additionally, trying to open Minecraft with other versions of Litematica or MaLiLib compatible with 1.21.3 results in the same issue.
![image](https://github.com/user-attachments/assets/0982ad86-0832-4d7c-8b28-283967ddbff4)

**Comment by maruohon** [comment]
Version 0.22.1 was removed from Modrinth because it had some issues. But there is now version 0.22.2 since yesterday.

**Comment by Skyguy7878** [comment]
I've just been made aware, thank you very much though. 0.22.2 isn't in my launcher for some reason, but I got it! 
![image](https://github.com/user-attachments/assets/0f4e2f6a-fa90-44c4-8a2a-aa6369237bd4)
