### ISSUE TITLE
Litematica schematic is a single block cyan outline

### ISSUE THREAD

**Issue by logslmao** [maruohon/litematica#917]
As said in the title, its a single block cyan outline, i made 3 schematics, all of which have this issue

Minecraft version: 1.21

Version of mods: Litematica: litematica-fabric-1.21-0.19.53, Litematica Printer (if needed): litematica-printer-1.21-3.5.0-sakura.4, Mailib: malilib-fabric-1.21-0.21.4 

![image](https://github.com/user-attachments/assets/9359460a-5aa5-4da4-a61d-4fdcfcca1ddf)

Yes, i have enabled rendering of schematics, Yes, all render layers are active, no i am not using optifine OR shaders. I loaded them and they dont work

Reproduction steps:
Create a schematic
Save the schematic
Attempt to load it in either a server or singleplayer world

**Comment by maruohon** [comment]
If you only see a 1x1x1 outline, then that's probably the origin point, and this is the "accidental manual origin issue". See here for more info: https://github.com/maruohon/litematica/issues/751#issuecomment-1671611897

**Comment by logslmao** [comment]
Thank you! It works now!
