### ISSUE TITLE
VCS failing to load any version's schematic

### ISSUE THREAD

**Issue by emilyavi** [maruohon/litematica#918]
Version: 1.21.1, Litematica v0.19.53, MaLiLib v0.21.4

VCS does not work at all: saving a version and re-loading it causes a `Failed to load schematic for the current version` error.
this stems from the project .json files storing the filenames without an extension, which in turn causes `FileType.fromFile` to always return `INVALID`

**Comment by emilyavi** [comment]
fixed - https://github.com/maruohon/litematica/pull/919#issuecomment-2564520569
note: i believe this bug still affects builds 0.14.7 (MC 1.19.4) up to and including build 0.17.4 (MC 1.20.3-1.20.4)

**Comment by maruohon** [comment]
These are in the 0.17.4 release for MC 1.20.4, but not yet in any older MC version releases. I pushed the `1.20.x` branch (for 1.20.4) now.
