### ISSUE TITLE
As soon as you enter the server, it crashes

### ISSUE THREAD

**Issue by Yummy-cookie** [maruohon/litematica#926]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-12-22 11:25:57
Description: Unexpected error

java.lang.ClassCastException: class fi.dy.masa.litematica.world.WorldSchematic cannot be cast to class net.minecraft.class_638 (fi.dy.masa.litematica.world.WorldSchematic and net.minecraft.class_638 are in unnamed module of loader 'knot' @55f3ddb1)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$gcf000$valkyrienskies$renderShipBlockEntityInShipyard(SodiumWorldRenderer.java:1570)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:347)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$dfa000$iris$addToList(SodiumWorldRenderer.java:583)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:306)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$gcf000$valkyrienskies$renderShipBlockEntities(SodiumWorldRenderer.java:1596)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:269)
	at knot//net.minecraft.class_761.handler$fea000$sodium$onRenderBlockEntities(class_761.java:17599)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1372)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)
	at knot//net.minecraft.class_757.method_3192(class_757.java:880)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$gcf000$valkyrienskies$renderShipBlockEntityInShipyard(SodiumWorldRenderer.java:1570)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:347)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$dfa000$iris$addToList(SodiumWorldRenderer.java:583)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:306)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.redirect$gcf000$valkyrienskies$renderShipBlockEntities(SodiumWorldRenderer.java:1596)
	at knot//me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:269)
	at knot//net.minecraft.class_761.handler$fea000$sodium$onRenderBlockEntities(class_761.java:17599)
	at knot//net.minecraft.class_761.method_22710(class_761.java:1372)
	at knot//net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['YGYG'/362, l='ClientLevel', x=2.41, y=64.00, z=-14.67]]
	Chunk stats: 1024, 462
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2839 game time, 2839 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at knot//net.minecraft.class_638.method_8538(class_638.java:458)
	at knot//net.minecraft.class_310.method_1587(class_310.java:2406)
	at knot//net.minecraft.class_310.method_1514(class_310.java:826)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Minecraft-Mod-Language-Modpack-Converted-1.20.1.zip, fabric, file/MASA-Motdv1.0.zip, file/subtitle-color-highlights-v1-2.zip, file/repottery-v1-3-2.zip, file/Vervada-s-enhanced-plants.zip, file/unique-spawn-eggs-v1-5.zip, file/【钠-汉化资源包】SodiumTranslations.zip, railways:green_signals, railways:legacy_palettes, railways:legacy_semaphore, file/【材质包】梧桐加减法Re 2.1.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 22.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 501296472 bytes (478 MiB) / 1912602624 bytes (1824 MiB) up to 9193914368 bytes (8768 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
	Identifier: Intel64 Family 6 Model 62 Stepping 4
	Microarchitecture: Ivy Bridge (Server)
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: AMD Radeon RX 580 2048SP
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x6fdf
	Graphics card #0 versionInfo: DriverVersion=31.0.21921.1000
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 34740.24
	Virtual memory used (MB): 25333.96
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 50.77
	JVM Flags: 11 total; -Xmx8766m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		additionaladditions: Additional Additions 6.0.1
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		advancementplaques: Advancement Plaques 1.6.7
		ambientsounds: AmbientSounds 6.1.4
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		armortip: Armortip 1.0.0
		balm-fabric: Balm 7.3.10
			kuma_api: KumaAPI 20.1.9-SNAPSHOT
		bellsandwhistles: Create: Bells & Whistles 0.4.5
		betteradvancements: Better Advancements 0.4.2.25
		betterf3: BetterF3 7.0.2
		betterpingdisplay: Better Ping Display 1.1.1
		bigcontraptions: Create: Big Contraptions 1.0
		bookshelf: Bookshelf 20.2.13
		botarium: Botarium 2.3.4
			team_reborn_energy: Energy 3.0.0
		candlelight: [Let's Do] Candlelight 1.2.13
		carryon: Carry On 2.1.2.7
		chat_heads: Chat Heads 0.13.7
		cherishedworlds: Cherished Worlds 6.1.7+1.20.1
		cloth-config: Cloth Config v11 11.1.136
			cloth-basic-math: cloth-basic-math 0.6.1
		copycats: Create: Copycats+ 2.1.4+mc.1.20.1-fabric
		create: Create 0.5.1-j-build.1631+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.11-4
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_brewing: Porting Lib Brewing 2.3.8+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.8+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.8+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.8+1.20.1
			porting_lib_models: Porting Lib Models 2.3.8+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.8+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.8+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.8+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.79-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_dd: Create: Dreams & Desires 0.1d
			dsbg: Detected setBlock Be Gone 1.0
		create_jetpack: Create Jetpack 4.2.1
			flightlib: Flight Lib 2.1.0
		create_new_age: Create: New Age 1.1.2
		createaddition: Create Crafts & Additions 1.2.4
		createbigcannons: Create Big Cannons 5.7.2
			ritchiesprojectilelib: Ritchie's Projectile Library 2.0.0-dev+mc.1.20.1-fabric-build.182
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
		createframed: Create: Framed 1.5.8+1.20.1
		createoreexcavation: Create Ore Excavation 1.5.4
			chunk-storage-api-fabric: Chunk Storage Api Fabric 1.0.4
		createrailwaysnavigator: Create Railways Navigator 1.20.1-beta-0.7.1
			dragonlib: DragonLib 1.20.1-2.2.22
		createutilities: Create Utilities 0.3.0+1.20.1
		creativecore: CreativeCore 2.12.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		croptopia: Croptopia 3.0.3
		crystal_clear: Crystal-Clear 0.0
		customskinloader: CustomSkinLoader 14.21.2
		dark-loading-screen: Dark Loading Screen 1.6.14
		doapi: [Let's Do] API 1.2.15
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		dynamic_fps: Dynamic FPS 3.7.7
			net_lostluma_battery: battery 1.3.0
		edgelesschatscreen: Edgeless Chat Screen 1.1.5
		enchdesc: EnchantmentDescriptions 17.1.19
		endersdelight: Ender's Delight Refabricated 1.20.1-1.0.2.refabricated
		ends_delight: End's Delight refabricated-1.20.1-2.5
		epherolib: EpheroLib 1.2.0
		expandeddelight: Expanded Delight 0.3.2
			omega-config: OmegaConfig 1.4.0+1.20.1
		extendedgears: Extended Cogwheels 2.1.1-1.20.1-0.5.1.f-fabric
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.13.0+kotlin.2.1.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.1.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.1.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.26.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.15.6
		farmersdelight: Farmer's Delight 1.20.1-2.2.4+refabricated
			mm: Manningham Mills 2.3
			porting_lib_accessors: Porting Lib Accessors 2.3.8+1.20.1
			porting_lib_base: Porting Lib Base 2.3.8+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.8+1.20.1
				porting_lib_common: Porting Lib Common 2.3.8+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.8+1.20.1
				porting_lib_gui_utils: Porting Lib Gui Utils 2.3.8+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.8+1.20.1
			porting_lib_config: Porting Lib Config 2.3.8+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.8+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.8+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.8+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.8+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.8+1.20.1
				porting_lib_core: Porting Lib Core 2.3.8+1.20.1
		fastipping: Fast IP Ping 1.0.5
		fastquit: FastQuit 3.0.0+1.20+
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.1
		ftblibrary: FTB Library 2001.2.6
		ftbultimine: FTB Ultimine 2001.1.5
		fusion: Fusion 1.1.1
		garnished: Create: Garnished 2.0.2+1.20.1-fabric
			create_dragon_lib: Create Dragon Lib 1.4.2
		highlighter: Highlighter 1.1.9
		ias: In-Game Account Switcher 9.0.2-alpha.1
		iceberg: Iceberg 1.1.25
		immersive_aircraft: Immersive Aircraft 1.1.5+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		indium: Indium 1.0.34+mc1.20.1
		interiors: Create: Interiors 0.5.6
		inventoryprofilesnext: Inventory Profiles Next 1.10.11
		invmove: InvMove 0.8.4
		iris: Iris 1.7.5+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		irisflw: Iris Flywheel Compat 1.1.2
		java: Java HotSpot(TM) 64-Bit Server VM 22
		jei: Just Enough Items 15.20.0.105
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 4.0.2
		litematica: Litematica 0.15.4
		lithium: Lithium 0.11.2
		malilib: MaLiLib 0.16.3
		mc-homes: mc-homes 1.4+1.20.1
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modernui: Modern UI 3.11.1.1
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.7
			com_vladsch_flexmark_flexmark: flexmark 0.64.8
			com_vladsch_flexmark_flexmark-util-ast: flexmark-util-ast 0.64.8
			com_vladsch_flexmark_flexmark-util-builder: flexmark-util-builder 0.64.8
			com_vladsch_flexmark_flexmark-util-collection: flexmark-util-collection 0.64.8
			com_vladsch_flexmark_flexmark-util-data: flexmark-util-data 0.64.8
			com_vladsch_flexmark_flexmark-util-dependency: flexmark-util-dependency 0.64.8
			com_vladsch_flexmark_flexmark-util-format: flexmark-util-format 0.64.8
			com_vladsch_flexmark_flexmark-util-html: flexmark-util-html 0.64.8
			com_vladsch_flexmark_flexmark-util-misc: flexmark-util-misc 0.64.8
			com_vladsch_flexmark_flexmark-util-sequence: flexmark-util-sequence 0.64.8
			com_vladsch_flexmark_flexmark-util-visitor: flexmark-util-visitor 0.64.8
		modmenu: Mod Menu 7.2.2
		morechathistory: More Chat History 1.3.0
		mousetweaks: Mouse Tweaks 2.26
		nethersdelight: Nether's Delight 1.0.0
			disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		oceansdelight: Ocean's Delight fdrf-fabric-1.0.2-1.20
		pineapple_delight: Pineapple Delight 1.0.12
		presencefootsteps: Presence Footsteps 1.10.1+1.20.1
			kirin: Kirin UI 1.15.6+1.20.1
		railways: Create: Steam 'n' Rails 1.6.9+fabric-mc1.20.1
		rechiseled: Rechiseled 1.1.6
		rechiseledcreate: Rechiseled: Create 1.0.2+a
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		replaymod: Replay Mod 1.20.1-2.6.20
		serverpingerfixer: Server Pinger Fixer 1.0.4
		skinlayers3d: 3d-Skin-Layers 1.7.4
		sliceanddice: Create Slice & Dice 3.3.1
		sodium: Sodium 0.5.11+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sodiumdynamiclights: Sodium Dynamic Lights 1.0.9
		sodiumoptionsapi: Sodium Options API 1.0.8
			mixinsquared: MixinSquared 0.2.0-beta.6
		sophisticatedbackpacks: Sophisticated Backpacks 1.20.1-3.20.17.1.60
		sophisticatedcore: Sophisticated Core 1.20.1-0.7.10.1.78
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.17+a
		t_and_t: Towns and Towers 1.12
		tipsmod: Tips 12.1.8
		tpaplusplus: TPA++ 1.6.0-1.20.x-UNTESTED-BETA-3
		valkyrienskies: Valkyrien Skies 2 2.3.0-beta.5
		videotape: VideoTape 1.4.0
		waystones: Waystones 14.1.6
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
		xaerominimap: Xaero's Minimap 24.6.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.20.1-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.20.1-Fabricer
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon RX 580 2048SP GL version 4.6.0 Core Profile Context 24.9.1.240813, ATI Technologies Inc.
	Window size: 1920x1051
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Minecraft-Mod-Language-Modpack-Converted-1.20.1.zip, fabric, file/MASA-Motdv1.0.zip (incompatible), file/subtitle-color-highlights-v1-2.zip (incompatible), file/repottery-v1-3-2.zip (incompatible), file/Vervada-s-enhanced-plants.zip (incompatible), file/unique-spawn-eggs-v1-5.zip (incompatible), file/【钠-汉化资源包】SodiumTranslations.zip, railways:green_signals, railways:legacy_palettes, railways:legacy_semaphore, file/【材质包】梧桐加减法Re 2.1.zip
	Current Language: zh_cn
	CPU: 20x Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

**Comment by sakura-ryoko** [comment]
Your problem is trying to use valkyrienskies

**Comment by Yummy-cookie** [comment]
> i
Thank you

**Comment by Yummy-cookie** [comment]
> Your problem is trying to use valkyrienskies

Thank you
