### ISSUE TITLE
My Schematic model is not shown in normal game!

### ISSUE THREAD

**Issue by LJ-YT** [maruohon/litematica#93]
After saving my world in Litematica, I can view the Schematic model with Fabric version. However, I can't view it in normal game 1.14.4! I want to play the map without using any mod. Please help!

**Comment by vacla** [comment]
if you want to see the schematic/litematic, the only way is with litematica.

**Comment by LJ-YT** [comment]
Thanks for your help! I will try to paste them in the world. Also, I have 2 big schematics placed. I hope saving them won't crash the game...
